### ISSUE TITLE
Plots!

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#10]
Yes, those things. We need some of them.

**Comment by jake-westfall** [comment]
We now have nice built-in functionality for plotting the results (ModelResults.plot(), which is essentially pm.traceplot() plus some niceties), and for plotting the priors, at least for fixed effects (through Model.plot() or ModelResults.plot(kind='priors')). Are there other obvious plotting candidates? Or can we consider this issue more or less closed?

**Comment by tyarkoni** [comment]
Okay with me to close; future plot requests should be through new issues.
