### ISSUE TITLE
build failing due to temporary pymc3 / pandas incompatibility

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#102]
[See resolved pymc3 issue](https://github.com/pymc-devs/pymc3/issues/2172)

This is already fixed on the pymc3 master, but not sure how long until it's fixed on the PyPI version.

**Comment by twiecki** [comment]
Yeah, we really need to push a new release. Soon!

**Comment by tyarkoni** [comment]
Closing this, as it's fixed by the new PyMC3 release.
