### ISSUE TITLE
Posterior predictive checks

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#106]
We should add some functionality for doing easy posterior predictive checks. Minimally we should be able to produce posterior predictive samples for arbitrary predictor values. Ideally there could also be some nice plotting functionality or something.

As a starting point, @aflaxman suggests a pattern like:

    import numpy as np, pandas as pd, pymc3 as pm, bambi
    
    df = pd.DataFrame({'p':np.random.normal(size=400)})
    
    # blank out some values, for which I would like to impute
    df.loc[np.random.choice(df.index, size=200, replace=False), 'p'] = np.nan
    
    model = bambi.Model(df, dropna=True)
    results = model.fit('p ~ 1')
    
    ppc = pm.sample_ppc(model.backend.trace, model=model.backend.model, samples=50)
    ppc['p'].shape  # hoping for (50, 400, 1)

**Comment by aflaxman** [comment]
Here is a hack that builds on the pattern above to provide the results I am after:
```
import numpy as np, pandas as pd, pymc3 as pm, bambi

df = pd.DataFrame({'p':np.random.normal(size=400)})

# blank out some values, for which I would like to impute
df.loc[np.random.choice(df.index, size=200, replace=False), 'p'] = np.nan

model = bambi.Model(df, dropna=True)
results = model.fit('p ~ 1')

model2 = bambi.Model(df.fillna(0))
model2.fit('p ~ 1', run=False)
model2.build('pymc')

ppc = pm.sample_ppc(model=model2.backend.model, trace=model.backend.trace, samples=50)
assert ppc['p'].shape == (50, 400, 1)
```

Building the model twice is uncool, but I couldn't figure out a way to do it right in the time I had to explore it today.

**Comment by ahartikainen** [comment]
Stan is implementing standalone `generated quantities` which would make this more or less easier for Stan models.
