### ISSUE TITLE
Better ordering of variables in plot()

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#114]
I'm not sure how the order of variables is determined at the moment (probably just by the order of the dict keys when requested), but in practice, there isn't usually any rhyme or reason to the default order in the plot (though this can be manually controlled with `varnames`). We should probably default to at least grouping the fixed and random effects--and potentially grouping within the latter based on some simple guesses about parameter names (e.g., all the `1|*` terms and `_sd` terms get grouped separately).

**Comment by aloctavodia** [comment]
Is this solved?

**Comment by tyarkoni** [comment]
Looks that way; guess I forgot to close it. Thanks for the reminder (will get to your PRs ASAP, @aloctavodia—thanks!).
