### ISSUE TITLE
advi raises typeerror

### ISSUE THREAD

**Issue by wcbeard** [bambinos/bambi#115]
calling `model.fit(backend='pymc3', run=True, method='advi')` raises `TypeError: __init__() got an unexpected keyword argument 'transformed_vars'`.

Looks like this happens in the `run` method [here](https://github.com/bambinos/bambi/blob/e1abd5dd4d2aecd2e8474d4ee6d3191a0193a53e/bambi/backends/pymc.py#L168), since the `PyMC3ADVIResults` is [only defined with the arguments](https://github.com/bambinos/bambi/blob/e1abd5dd4d2aecd2e8474d4ee6d3191a0193a53e/bambi/results.py#L402) `model, params`.

**Comment by jake-westfall** [comment]
Yep, looks like you're right. Thanks for pointing this out. I don't think our tests currently include ADVI at all, otherwise this definitely would have been caught. We need to add this to our tests.

**Comment by tomicapretto** [comment]
@aloctavodia maybe this is not an issue anymore?
