### ISSUE TITLE
Better specification of random effects

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#12]
Currently random effects must be specified by passing a list that only accepts the pipe operator, and none of the other standard formula operators (e.g., 'subject|group' is fine; '(1+subject)|group' breaks). In the long term we should eventually handle all the operators accepted by lme4, but a shorter-term solution is to check that no invalid operators are passed, and raise an error message if any are detected (e.g., '1+subject|group' will raise an exception). This ensures that people don't run into unexpected behavior where the model runs without complaint, but fits the wrong model.

**Comment by jake-westfall** [comment]
It seems like one of the important cases to be able to handle here is adding random slopes for interaction terms, which in lme4 look something like `(X1:X2|subj)` or `(X1*X2|subj)`.

**Comment by Gilles86** [comment]
> It seems like one of the important cases to be able to handle here is adding random slopes for interaction terms, which in lme4 look something like (X1:X2|subj) or (X1*X2|subj).

I was just gonna post a feature request for exactly that :).

Nice work, this package already!
