### ISSUE TITLE
model.fit() produces "AttributeError: 'NoneType' object has no attribute 'groups'"

### ISSUE THREAD

**Issue by oliver-contier** [bambinos/bambi#126]
When I call the following:

`
model = Model(df)
results = model.fit("Answer ~ Block*ED",
                    family='bernoulli',
                    random=['Block|sub'])
`

I get this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-115-6998395cd8f0> in <module>()
      3 results = model.fit("Answer ~ Block*ED",
      4                     family='bernoulli',
----> 5                     random=['Block|sub'])
      6 

/Users/Oliver/anaconda2/envs/run_hmax/lib/python2.7/site-packages/bambi/models.pyc in fit(self, fixed, random, priors, family, link, run, categorical, backend, **kwargs)
    279             if not self.built or backend != self._backend_name:
    280                 self.build(backend)
--> 281             return self.backend.run(**kwargs)
    282 
    283         self._backend_name = backend

/Users/Oliver/anaconda2/envs/run_hmax/lib/python2.7/site-packages/bambi/backends/pymc.pyc in run(self, start, method, init, n_init, find_map, **kwargs)
    162                 self.trace = pm.sample(samples, start=start, init=init,
    163                                        n_init=n_init, njobs=njobs, **kwargs)
--> 164             return self._convert_to_results()
    165 
    166         elif method == 'advi':

/Users/Oliver/anaconda2/envs/run_hmax/lib/python2.7/site-packages/bambi/backends/pymc.pyc in _convert_to_results(self)
    206             else:
    207                 return [key]
--> 208         levels = sum([get_levels(k, v) for k, v in shapes.items()], [])
    209 
    210         # instantiate

/Users/Oliver/anaconda2/envs/run_hmax/lib/python2.7/site-packages/bambi/backends/pymc.pyc in get_levels(key, value)
    203                         return ['{}|{}_offset{}'.format(key.split('|')[0],
    204                                 *re.match(r'^(.+)(\[.+\])$', x).groups())
--> 205                                 for x in self.spec.terms[re1.group(1)].levels]
    206             else:
    207                 return [key]

AttributeError: 'NoneType' object has no attribute 'groups'
---------------------------------------------------------------------------

This is the standard output:

Auto-assigning NUTS sampler...
Initializing NUTS using advi...
Average Loss = 4,054.2:  69%|██████▉   | 34453/50000 [01:16<00:34, 448.48it/s]
Convergence archived at 34500
Interrupted at 34,499 [68%]: Average Loss = 9,050.6
Sequential sampling (2 chains in 1 job)
NUTS: [Block|sub_offset, Block|sub_sd_log__, 1|sub_offset, 1|sub_sd_log__, Block:ED, ED, Block, Intercept]
100%|██████████| 1500/1500 [02:16<00:00, 10.97it/s]
100%|██████████| 1500/1500 [02:19<00:00, 10.74it/s]
There were 14 divergences after tuning. Increase `target_accept` or reparameterize.
There were 63 divergences after tuning. Increase `target_accept` or reparameterize.
The estimated number of effective samples is smaller than 200 for some parameters.

---------------------------------------------------------------------------

When removing the `random=['Block|sub']` argument, the model runs without problems.

I'm running this in a jupyter notebook (jupyter version 1.0.0) on a macOS 10.13.6 system and using a python 2.7.15 anaconda environment. This error also occurs when using either the latest bambi release installed via pip or bambi 0.1.1 installed via GitHub.

If I understand this correctly, this has something to do with pymc (my version is 2.3.6, apparently the latest). Or am I getting something wrong? I also get this kind of error when changing the random effects structure (e.g. only random intercepts).

I really appreaciate your package by the way.
Thanks!

**Comment by jake-westfall** [comment]
I just looked at this for a couple minutes, but it looks like the `.levels` attribute of the `RandomTerm` object representing `Block|sub` is messed up in some way. The elements of `.levels` are not conforming to the format that the regular expression expects:
https://github.com/bambinos/bambi/blob/0d0afe18d738308dcb63a3502e1dfc4cba3f143b/bambi/backends/pymc.py#L204

**Comment by aloctavodia** [comment]
Is this still a problem?

**Comment by tyarkoni** [comment]
I'm not able to reproduce this—I can get it to run fine with fake data and an identical model specification. It suppose it could be some weird interaction with the particular dataset in question, but barring a follow-up, or someone else having the same issue, I think it can be closed.
