### ISSUE TITLE
Support MAP estimation

### ISSUE THREAD

**Issue by hacktuarial** [bambinos/bambi#128]
It would be nice to fit a bambi Model and get just the MAP estimate of the parameters, instead of full MCMC sampling. Usage would look something like

```
from bambi import Model
model = Model(df).fit('y ~ x1 + x2', run=False)
map_est = model.fit(method='MAP')
```
The last argument would get passed to the pymc3 backend, and would invoke `pm.find_MAP`

**Comment by ahartikainen** [comment]
For PyStan this would mean calling `optimize`. 

Do we have any idea about when MAP is going to fail? High dimensions (dims = 5+ / 10+?), hierarchical models?

**Comment by aloctavodia** [comment]
Not sure this is a practice we should encourage. PyMC3 will show a warning when `pm.find_MAP` is used.
