### ISSUE TITLE
statsmodels imports, replace sm

### ISSUE THREAD

**Issue by josef-pkt** [bambinos/bambi#130]
(I'm just following up a link and briefly browsed the source)

`bambi/priors.py` imports `statsmodels.api`
This is not recommended for library use because it imports all of statsmodels and large parts of scipy.
Most of the time it is more efficient and faster in loading to just import the relevant submodules or objects, e.g. just `GLM` class and `families` module

e.g.
```
from statsmodels.genmod.generalized_linear_model import GLM
from statsmodels.genmod import families
```
https://gist.github.com/josef-pkt/61039ab6dc7fb8b502caf5f2050111c0

**Comment by camenpihor** [comment]
Hey! If this issue is open I would be interested in helping out :)

**Comment by aloctavodia** [comment]
Thank you!

**Comment by camenpihor** [comment]
Sorry! I am new to contributing. How do I gain permission to push and create a PR? I have the update ready to go :)

**Comment by aloctavodia** [comment]
1. Fork Bambi by clicking on the 'Fork' button near the top right of the main repository page. This creates a copy of the code under your GitHub user account.

2. Clone your fork of the Bambi repo from your GitHub account to your local disk, and add the base repository as a remote:

   ```bash
   $ git clone git@github.com:<your GitHub handle>/bambi.git
   $ cd bambi
   $ git remote add upstream git@github.com:bambinos/bambi.git
   ```

3. Create a ``feature`` branch to hold your development changes:

   ```bash
   $ git checkout -b my-feature
   ```

   Always use a ``feature`` branch. It's good practice to never routinely work on the ``master`` branch of any repository.

4. Project requirements are in ``requirements.txt`` run:

   ```bash
   $ pip install -r requirements.txt
   ```

5. Develop the feature on your feature branch. Add changed files using ``git add`` and then ``git commit`` files:

   ```bash
   $ git add modified_files
   $ git commit
   ```

   to record your changes locally.
   After committing, it is a good idea to sync with the base repository in case there have been any changes:
   ```bash
   $ git fetch upstream
   $ git rebase upstream/master
   ```

Then push the changes to your GitHub account with:

   ```bash
   $ git push -u origin my-feature
   ```

6. Go to the GitHub web page of your fork of the Bambi repo. Click the 'Pull request' button to send your changes to the project's maintainers for review. This will send an email to the committers.

**Comment by camenpihor** [comment]
Thanks :)
