### ISSUE TITLE
Working with ArviZ

### ISSUE THREAD

**Issue by ahartikainen** [bambinos/bambi#132]
Hi,

I was wondering if BAMBI package would be interested in working / using ArviZ InferenceData (xarray dataset) and using our plotting tools?

ArviZ works with both PyStan and PyMC3.

Also we would be interested in implementing regression plots, but basically we need some good framework for this to work.

https://github.com/arviz-devs/arviz/issues/313
https://github.com/arviz-devs/arviz/issues/512

cc. @ColCarroll @canyon289 @aloctavodia @GWeindel @junpenglao

**Comment by tyarkoni** [comment]
Hi @ahartikainen,

This sounds like an interesting potential direction, but it would probably require someone else to step up as a core contributor/maintainer, as Bambi development has largely stalled due to competing time commitments. I'll leave this open in case someone else  wants to take it on at some point.

**Comment by aloctavodia** [comment]
Hi guys! At the moment I do not have the time to step up as a core contributor of Bambi, but I am really interested. I may have the time in a couple of months. @tyarkoni (besides the open issues) there is some road-map of to-do list I (or anyone willing to contribute) should pay attention?

**Comment by tyarkoni** [comment]
@aloctavodia that would be great! There isn't any explicit road-map though, no. One thing that would be nice to have in principle is a tensorflow-probability back-end, but I think at this point it probably makes sense to wait for PyMC4 (which will be built on tensorflow) instead.

**Comment by aloctavodia** [comment]
Thanks for the info @tyarkoni. I agree we should wait for PyMC4.

**Comment by GWeindel** [comment]
Hi all,

I would be happy to contribute in a more significant way but given my lack of expertise in package creation/maintenance in python and the little time I can spend on projects outside my PhD, I'm unsure about the amount of work/added value I can put in the project. I keep you posted if my situation changes.

**Comment by aloctavodia** [comment]
We could also use diagnostics from ArviZ not just plots :-)

**Comment by ahartikainen** [comment]
I'm also happy to contribute and hopefully help with PyStan specific stuff. We have some future plans that could help this lib.

**Comment by aloctavodia** [comment]
Closing, as ArviZ is now used for plots and diagnostics.
