### ISSUE TITLE
Drop support for Python 2.7

### ISSUE THREAD

**Issue by aloctavodia** [bambinos/bambi#138]
2019 will be the last year for Python 2.7 official support. Also ArviZ only works with Python 3.x and next PyMC3 release will be Python 3.x only.

**Comment by aloctavodia** [comment]
I have created a roadmap related to this issue. Please feel free to make changes https://github.com/bambinos/bambi/wiki/Roadmap

**Comment by camenpihor** [comment]
Hi @aloctavodia just checking in to see if there is anything I can help with in preparation for dropping support for Python2 :)

**Comment by aloctavodia** [comment]
Hi @camenpihor thanks for offering help. We should do a release and then we can work on this and the rest of the roadmap. Is this OK with you?

@tyarkoni what do you think?

**Comment by aloctavodia** [comment]
I think this issue is solved now, what do you think @camenpihor?
