### ISSUE TITLE
Use "Squash and merge" as the default option for merging

### ISSUE THREAD

**Issue by aloctavodia** [bambinos/bambi#139]
instructions are here https://help.github.com/en/articles/configuring-commit-squashing-for-pull-requests

**Comment by tyarkoni** [comment]
I'm not really a fan of this approach. IMO if the git history is cluttered with too many minor commits, that's on the developer to squash locally; I don't like the idea of throwing away information by default. Is it possible to leave the default as-is but allow the option to squash and merge on a case-by-case basis?

**Comment by aloctavodia** [comment]
Sure, no problem.
