### ISSUE TITLE
tech-debt-like stuff

### ISSUE THREAD

**Issue by aloctavodia** [bambinos/bambi#145]
Following the discussion in #143 about the "tech-debt-like stuff" I will suggest we leave that for the next release and instead focus on doing the last Pyhon 2.x. Of course this is just a suggestion I am totally open to other options. At least with black I would like to not apply it all at once in a single PR as formatting can be too aggressive. Instead we should incorporate it slowly as part of every PR. Thoughts?

**Comment by camenpihor** [comment]
I agree! (especially with the code formatting single PR suggestion). 

Are there issues that are applicable to the Python 2.x release that you think are beginner friendly, or are a reach learning-wise but do-able?

**Comment by tyarkoni** [comment]
Sounds good to me.

**Comment by aloctavodia** [comment]
@camenpihor Here is a draft of a roadmap https://github.com/bambinos/bambi/wiki/Roadmap, I guess we should restrict to issues that are more or less critical and improve the documentation. You should definitely be able to help us!

**Comment by aloctavodia** [comment]
@camenpihor maybe something we can work now is #81.

**Comment by camenpihor** [comment]
@aloctavodia On it! I'm also working my way through the notebooks right now (making sure that I can get them to run and that I can understand them)

**Comment by camenpihor** [comment]
Should we mark this issue as complete? Or add a todo list of tech-debt-like stuff? Or something else?
