### ISSUE TITLE
Add R-like t-test interface as a special case

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#15]
To facilitate adoption and familiarize naive users with the package, we should add a package-level `ttest()` method that just wraps `add_term()` or `fit()` calls, and has the same arguments as R's `t.test` function.

**Comment by tyarkoni** [comment]
I'm having second thoughts about this. It's easy enough to implement--the PyMC3 devs already have [a working example](https://pymc-devs.github.io/pymc3/notebooks/BEST.html) of Kruschke's BEST approach--but it seems like feature creep. Thoughts? Maybe the way to go is to add it as an example, but not add it to the core package. Sound good?

**Comment by jake-westfall** [comment]
That sounds like a good approach.
