### ISSUE TITLE
Deploying new documentation to https://bambinos.github.io/bambi/

### ISSUE THREAD

**Issue by camenpihor** [bambinos/bambi#152]
Just didn't want this to be forgotten! 

Previous discussion in https://github.com/bambinos/bambi/pull/148 acknowledged that we wanted to use github pages, but that we needed a maintainer who has access to settings to do it. https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

**Comment by camenpihor** [comment]
@aloctavodia @tyarkoni Thanks for your help with the documentation PR :) Created this so that we don't forget to deploy it

**Comment by twiecki** [comment]
https://bambinos.github.io/bambi/
