### ISSUE TITLE
Add `long_description` to setup.py

### ISSUE THREAD

**Issue by ColCarroll** [bambinos/bambi#155]
The pypi page will render a markdown or rst `long_description` field. In pymc3 we just do 

```python
with open(join(PROJECT_ROOT, 'README.rst'), encoding='utf-8') as buff:
    LONG_DESCRIPTION = buff.read()
...
setup(...
          long_description=LONG_DESCRIPTION,
          ...
)
...

```

**Comment by ColCarroll** [comment]
Er, this is the page where it would show up, after the 2.7 release in #138 : https://pypi.org/project/bambi/

**Comment by camenpihor** [comment]
@ColCarroll what has your experience been with a README.rst instead of markdown?

**Comment by ColCarroll** [comment]
Oops. I don't like writing .rst, but it is begrudgingly necessary for nice Sphinx docs. 

Note that for pypi to work right, you have to add `long_description_content_type="text/markdown",` to the setup.py. See https://github.com/ColCarroll/ridge_map/blob/master/setup.py for details.
