### ISSUE TITLE
Formula in priors

### ISSUE THREAD

**Issue by manhnguyen48** [bambinos/bambi#174]
Hi, 

Is it possible to specify a formula for prior? 

Say I have the formula as follows: 

y ~ b0 +  b1x1 + z 

where z is group level id. 
I understand how to specify priors for b0 and b1 and how to get varying slopes and intercepts for each z. However, I want to specify priors for z such that it's a linear combination of another set of variables, essentially introducing group-level characteristics that allow me to pool similar groups together:

z ~ Normal(b0 + b2x2, 1)

Many thanks,

**Comment by tyarkoni** [comment]
No, there's no way to do this. Sorry!
