### ISSUE TITLE
Improved ModelResults.summary()

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#18]
Currently `ModelResults.summary()` just wraps PyMC3's summary() method. It would be good to return basic information about the model--number of terms, number of columns, description of priors used, number of samples run, collinearity diagnostics from the term _setup() calls, etc.

We may also want to suppress (or truncate) the reporting of all random effect parameter estimates by default, since they can spew a lot of output at the user.

**Comment by palday** [comment]
+1

Maybe a summary like `brms` or `rstanarm` do in the R ecosystem. The PyMC3 summary would still be accessible via the `pymc3.summary(model)` for those cases where you want to treat the model fit as 'just' a normal PyMC3 model.

**Comment by jake-westfall** [comment]
f7f0cd17440bccaec1f89b069e186ff62fe9f28f provides some improvements (including suppressing output for the individual random effects, as mentioned above), but it would still be nice to have some basic model info included in the summary as well.

**Comment by jake-westfall** [comment]
Other things to add:

- Basic info about number of chains, samples per chain, total samples, burn-in period
- Diagnostic stats for each parameter (effective_n and gelman_rubin)

**Comment by jake-westfall** [comment]
Closed by 028d9918015c5cdf9aa3eeb9085059ec08bc5ffe.
