### ISSUE TITLE
Source installation of v0.2.0 is broken

### ISSUE THREAD

**Issue by ocefpaf** [bambinos/bambi#195]
The source dist does not have a required file `requirements.txt`.

**Comment by aloctavodia** [comment]
Thanks for the report. The files on githhub have the `requirements.txt` file and the file on pip does not (actually the file is there but not on the root directory). I was able to install bambi doing `pip install bambi`. Could you?

**Comment by ocefpaf** [comment]
> Thanks for the report. The files on githhub have the `requirements.txt` file and the file on pip does not (actually the file is there but not on the root directory). I was able to install bambi doing `pip install bambi`. Could you?

With the sdist from PyPI? No. The wheel work though b/c that was probably generated locally on a git checkout with that file. You'll have to add a MANIFEST.in file and list that file as part of the `sdist`.

Steps to reproduce,

```
pip install bambi --no-binary :all:
```

**Comment by aloctavodia** [comment]
OK, thanks for the hints. I will not be able to fix this until tomorrow, but I will try to fix this ASAP.
