### ISSUE TITLE
custom Family/link when running regression

### ISSUE THREAD

**Issue by Spaak** [bambinos/bambi#206]
I'm trying to use bambi to model reaction time data as the dependent variable, for which a Wald distribution is appropriate. In the past I've used pymc3 directly quite extensively, but I really like the brevity by which I can construct models with many random effects etc. in bambi. So, now I'd like to do the same using bambi.

I see that there is some machinery for providing custom families/priors in the regression etc., but I cannot figure out how to tell bambi to use a specific pymc3 distribution as the likelihood for the observed data. Any pointers?

In pymc3, I would do something like

```
...set up prior structure to capture regression, ends up in modelled_mu...
...add prior for residual term resid_lam (analogous to sigma in normal distribution)...

y = pm.Wald('y', mu=modelled_mu, lam=resid_lam, observed=mydata)
```

I basically want to figure out how to do that very last step, where everything before is captured by a bambi model. Any help is much appreciated!

**Comment by tyarkoni** [comment]
My recollection (it's been a while, and I don't have time to dig into the code at the moment) is that the link function is handled by statsmodels at the moment. So unfortunately you can't specify arbitrary PyMC3 distributions; the family you want has to be implemented in statsmodels, and support there is unfortunately pretty limited.

**Comment by aloctavodia** [comment]
Right at the moment the family has to be implemented in statsmodels. The number of families supported by statsmodels is a little bit larger than the ones implemented in Bambi, so qe can update this. Still not custom distribution for the moment.

**Comment by Spaak** [comment]
Thanks for the quick replies both. For now I managed to get this working by doing the following (note I'm using a gamma distribution now instead of Wald/inverse gaussian like I originally wanted, as the latter gave me sampling headaches with an identity link function (which I need to get interpretable results).

```python
model = bambi.Model(df)
# set up regression with some model.add... calls

# custom likelihood
prior = bambi.Prior(
    name='Gamma', # refers to pymc3 class name
    mu=np.ones(1),  # overwritten by hierarchical regression tree
    sigma=bambi.Prior("HalfStudentT", nu=4, sigma=df.rt.std())
)
family = bambi.Family(
    name='gamma', # irrelevant I think?
    parent='mu', # parameter linked to the regression
    prior=prior,
    link='identity' # identity link to get interpretable results
)

# custom statsmodels families class because a class is required by bambi, not an instance
class MyGamma(sm.genmod.families.Gamma):
    def __init__(self):
        super(MyGamma, self).__init__(
            link=sm.genmod.families.links.identity)

family.smfamily = MyGamma

model.add('rt ~ 0', family=family)
```

And then `model.build` and `model.fit` work like a charm!

Just for my understanding: I think the main reason adding arbitrary PyMC3 distributions (that don't have a counterpart in statsmodels) is non-trivial right now is because of the calculation of the default priors, right? (I tried to see whether I could contribute this functionality relatively easily but then I ran into the default prior machinery and gave up.)
