### ISSUE TITLE
Update Bambi on Conda Forge

### ISSUE THREAD

**Issue by canyon289** [bambinos/bambi#208]
Trying to follow docs but ArviZ doesn't accept bambi object for summary, and ArviZ raises exception

```
from bambi import Model
import arviz as az
model = Model(hibbs)
results = model.fit('vote ~ growth', samples=1000, chains=4)
az.summary(results)
```

![image](https://user-images.githubusercontent.com/7213793/85937896-c4013f80-b8bc-11ea-9f3a-b4463df0efac.png)

### Docs
https://bambinos.github.io/bambi/index.html
![image](https://user-images.githubusercontent.com/7213793/85937901-d7aca600-b8bc-11ea-843f-e8d258077979.png)

**Comment by canyon289** [comment]
FYI, I'm happy to help fix. Its just late for me now and I need to head to bed. Will revisit in following days

**Comment by ahartikainen** [comment]
Or should we fix this in ArviZ?

**Comment by aloctavodia** [comment]
You have an old version of bambi. The latest 0.2.0 returns an InferenceData object. How did you install bambi?

**Comment by canyon289** [comment]
I installed from conda as shown in the docker file. Seems like we should update bambi on conda. I can figure that out

**Comment by canyon289** [comment]
I realized I hadnt pushed the branch yet cause I dont have permissions and didnt fork! sorry

![image](https://user-images.githubusercontent.com/7213793/85949606-9643e700-b90c-11ea-90e7-41466e4a59eb.png)

**Comment by canyon289** [comment]
K did some research. It's because of some `requirements.txt` issue from last release. Will keep this issue open until next release so we can track

https://github.com/bambinos/bambi/issues/195
https://github.com/conda-forge/bambi-feedstock/pull/2

**Comment by aloctavodia** [comment]
This should be fixed now, right?

**Comment by canyon289** [comment]
Looks like it 
https://anaconda.org/conda-forge/bambi
![image](https://user-images.githubusercontent.com/7213793/103182920-eec85280-4863-11eb-8550-ba91f33765a4.png)

**Comment by sterlinm** [comment]
Just FYI may want to push 0.4.0 to conda-forge. Apologies if that's already in progress!

**Comment by tomicapretto** [comment]
> Just FYI may want to push 0.4.0 to conda-forge. Apologies if that's already in progress!

Thanks for the reminder, it is now updated
