### ISSUE TITLE
add support for Gaussian processes

### ISSUE THREAD

**Issue by aloctavodia** [bambinos/bambi#215]

**Comment by tjburch** [comment]
I know that [Gumbi](https://johngoertz.github.io/Gumbi/index.html) exists, borrowing heavily from here - I wonder if maybe it makes sense to outsource GPs to that, rather than creating a similar approach within Bambi?

**Comment by tomicapretto** [comment]
Continue the discussion in https://github.com/bambinos/bambi/issues/579
