### ISSUE TITLE
Add Median and Median Absolute Deviation as helper dictionary?

### ISSUE THREAD

**Issue by canyon289** [bambinos/bambi#223]
Do we think we should add a helper dictionary for Median and MAD_SD because its used so often in Regression and Other Stories? 

Basically asking if we just include this dictionary as part of bambi somewhere so its convenient for folks to use, especially as they read the book and try and reproduce the code

![image](https://user-images.githubusercontent.com/7213793/86523161-23130700-be1d-11ea-8012-fbd757e9ab57.png)

**Comment by aloctavodia** [comment]
ArviZ itself should be a better place to add this and other helper functions.

**Comment by canyon289** [comment]
Got it. Will move this issue

**Comment by canyon289** [comment]
Moved to ArviZ
