### ISSUE TITLE
[Feature Request] Factor strings instead of index

### ISSUE THREAD

**Issue by canyon289** [bambinos/bambi#224]
It would be nice if bambi could include factor/contrast label in the names like stan_glm does

```
from bambi import Model
import pandas as pd


earnings = pd.read_csv("https://raw.githubusercontent.com/avehtari/ROS-Examples/master/Earnings/data/earnings.csv")
earnings.head()

earnings["c_height"] = earnings["height"] - 66
model = Model(earnings[na_filter])
fit_4 = model.fit('weight ~ c_height + male + C(ethnicity)', samples=1000, chains=4)
```

![image](https://user-images.githubusercontent.com/7213793/87844050-f83d9f80-c86d-11ea-8ba4-8d905550ab2f.png)
![image](https://user-images.githubusercontent.com/7213793/87844058-0ab7d900-c86e-11ea-8b6f-25716dc0bc6e.png)

**Comment by tomicapretto** [comment]
This has been partially addressed in #277 and now prior/posterior plots have better labels. However, summary tables still suffer from this problem. Just leaving the note for the record and keeping the issue open.

**Comment by tomicapretto** [comment]
Isn't this issue covered [here](https://github.com/arviz-devs/arviz/commit/226d1418a959529f887c627dc751f6627bdbd345)?

**Comment by aloctavodia** [comment]
closing, feel free to open if not yet solved
