### ISSUE TITLE
Add Bayesian R^2 method

### ISSUE THREAD

**Issue by canyon289** [bambinos/bambi#225]
See this example notebook from Regression and Other Stories as to why

https://avehtari.github.io/ROS-Examples/Rsquared/rsquared.html

**Comment by aloctavodia** [comment]
ArviZ has something similar https://arviz-devs.github.io/arviz/generated/arviz.r2_score.html

**Comment by canyon289** [comment]
Gooooddd point. Maybe I can extend that one with a link function argument to allow for the binomial case
