### ISSUE TITLE
Replace the use of “random effects” and “fixed effects” terms

### ISSUE THREAD

**Issue by aloctavodia** [bambinos/bambi#236]
We need to replace those terms and also add documentation explaining, what we exactly mean by those terms and other terms commonly used for the same. 

We could use [this](https://mc-stan.org/rstanarm/articles/glmer.html) as a template.

We agreed on using "common terms" and "group specific term"

**Comment by tyarkoni** [comment]
Just chiming in to say that while I support replacing the terminology in the code and docs as suggested above, I would recommend keeping the fixed/random language in at least the example notebooks that focus on psychology/social science data, as I think that language will be much more familiar to the people likely to read these notebooks.

**Comment by canyon289** [comment]
@tyarkoni would it be acceptable if we changed it but provided a guide up top? While I recognize the terms are more useful for one community, or goal is to find a way to bridge all communities

**Comment by tyarkoni** [comment]
@canyon289 sure, that makes sense. I agree that the examples should ideally be comprehensible to as many people as possible.

**Comment by canyon289** [comment]
Awesome, thank you for the feedback. Cant express how much we appreciate it
