### ISSUE TITLE
Rename level names when returning categorical variables

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#24]
Patsy will rename categorical variables sequentially, but it's helpful to return results to the user with the original level values for interpretability's sake. By default, we would ideally back-project extracted column names to the original level names in the data passed in. This may or may not be easily feasible given the current implementation, but we should take a look.

**Comment by jake-westfall** [comment]
Closed by 332645f66cfcb9d5b8fdcb3d81885928d3db9481, f7f0cd17440bccaec1f89b069e186ff62fe9f28f, and 384db90a21dbad0ca9703a606c91c90f3a77cbf2.
