### ISSUE TITLE
Add tests for the full range of models we support

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#26]
Adding tests for different models should be a high priority. I don't think we need to check for numerical correctness of output just yet (though we'll get there), but we do want to make sure the number of parameters we get back for each term is right, etc. We should add at least one test for every major permutation of model we can support (e.g., fixed effects alone; fixed effects with one random intercept term; crossed random effects; etc.).

I think these can probably be specified with the formula syntax for now, though I think a better approach would ultimately be to specify the same model using both the high and low-level APIs, and then check for equivalency of results (in addition the checking that the trace looks right).

**Comment by tyarkoni** [comment]
I don't know if we have *complete* coverage, but it seems pretty comprehensive. I'll close this for now and we can add new tests as needed.

**Comment by jake-westfall** [comment]
I think our coverage of LMMs is pretty much complete -- I'm about to push one final test for the last model type I can think of that's not currently being tested (cell-means fixed effects with multiple other random effects). However we don't test any GLMMs yet.
