### ISSUE TITLE
Replace `UserWarning: Modeling the probability that...` with a message

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#262]
When you fit a logistic regression with Bambi you can specify which level of the response variable is considered a success. 

For example, 

```python
model = bmb.Model(data)
fitted = model.fit('income[>50K] ~ age + hs_week + sex + race',  family='bernoulli')
```
Which raises the following warning

```python
# UserWarning: Modeling the probability that income=='>50K'
```

Shouldn't this be a message instead of a warning?  
I find it counter intuitive to have a warning for something that is normal usage and not an indication of misbehavior.

**Comment by aloctavodia** [comment]
Agreed, Additionally we should probably use [logging](https://docs.python.org/3/library/logging.html) instead of warning, not only for this case but in general.
