### ISSUE TITLE
Use the same color palette for all the example notebooks

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#268]

**Comment by aloctavodia** [comment]
Are we going to use a default style from matplotlib or arviz, something like "arviz-white"? Or some Bambi specific style?

**Comment by tomicapretto** [comment]
I was thinking about arviz-darkgrid. Is there any drawback about using it as default?

**Comment by aloctavodia** [comment]
no drawback

**Comment by tomicapretto** [comment]
Closing since #282
