### ISSUE TITLE
Plot or summarize priors

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#27]
Since the priors are now adapted to the data, we should have some way of showing the user what the parameters actually were. Either a `plot_priors()` method comparable to the kdeplots produced by `traceplot()` or some kind of `summarize_priors()` that produces a table of distribution names and parameters would do the trick.

**Comment by jake-westfall** [comment]
I like the idea of `plot_priors()`, which should make it pretty much impossible for users not to understand what the priors are. That said, most of the plots will just be a bunch of identical-looking panels of Normal and HalfCauchy distributions, where the difference is just in the scale of the axes -- this redundancy is not necessarily problem, but it just means the plots may induce an eye-glazing reaction at first.

**Comment by tyarkoni** [comment]
Agreed, but I think clarity is the most important thing here; I'm happy to bore users to tears as long as they understand what's going on. 🙂

**Comment by jake-westfall** [comment]
In general I do think that the avoidance of redundancy is an overrated criterion for plots and tables.

**Comment by jake-westfall** [comment]
I have some somewhat janky code that plots priors in the [ESCS multiple regression notebook](https://github.com/bambinos/bambi/blob/master/examples/ESCS_multiple_regression.ipynb), but it doesn't yet work in the general case.

**Comment by jake-westfall** [comment]
0b02417 implements this for all fixed effect parameters and the residual SD (in normal models), but it doesn't yet plot the priors for the random effect variances.
