### ISSUE TITLE
modeling with pystan support in bambi

### ISSUE THREAD

**Issue by sreedta8** [bambinos/bambi#273]
Hi

I have ran a model successfully with bambi using pymc3 as the backend. I attempted to run the same model but specifying *backend="stan"* and the model failed with the following message:

WARNING:pystan:Maximum (flat) parameter count (1000) exceeded: skipping diagnostic tests for n_eff and Rhat.

Model summary using *az.summary(results6)* gives the following message(repreated many times).

WARNING:arviz.stats.stats_utils:Shape validation failed: input_shape: (1, 500), minimum_shape: (chains=2, draws=4) 

How should I interoret these warnings and correct them? In addition, how can I increase the number of tuning steps or change the adapt_delta to prevent messages such as: 

WARNING:pymc3:The acceptance probability does not match the target. It is 0.8787839418090507, but should be close to 0.8. Try to increase the number of tuning steps.

**Comment by ahartikainen** [comment]
```
WARNING:pystan:Maximum (flat) parameter count (1000) exceeded: skipping diagnostic tests for n_eff and Rhat.
```

At the end of fitting, pystan does some diagnostics, but some of the diagnostics are expensive, so if there are too many parameters, it will skip them and lets user to check these manually if they want to do it.

The other error can be fixed installing latest github version

    pip install git+https://github.com/arviz-devs/arviz

**Comment by sreedta8** [comment]
@ahartikainen 

thanks for getting back and thanks for your work on these libraries that such as *bambi and arviz* that make it easier for non-programmmers to access state-of-the-art Bayesian tools. I posted a separate message about continued support for *pystan* in *bambi*. I hope the current support continues.
I will install the latest *arviz* and report back on the error. Thanks again.

**Comment by aloctavodia** [comment]
You can pass the `target_accept` argument to `fit`

**Comment by sreedta8** [comment]
@aloctavodia thank you for that tip. I will use it. I also had the opportunity to use your book Bayesian Analysis with PyMC3 (2ed). The explanation provided using the lake to describe how MH and HMC work will remain etched in my understanding forever. That entire chapter was a great introduction to non-mathematician such as I.  I use that now when I train other applied modelers. I have used the first edition too. I really enjoyed the books. I have recommended your book to others I work with in probabilisitc modeling. I shared my feedback on your book notebooks github website. Thank you for your wnderful efforts across these spectrum of tools.

@ahartikainen I installed the latest version of arviz from github using the command you provided. The *arviz* warnings still persist. I will try to create a bambi specific environment in anaconda and check if the warnings go away. Is there a environment.yml file you would recommend I use to create such an environment using conda so that I would have the correct dependencies installed.

**Comment by ahartikainen** [comment]
How many chains do you use?

**Comment by sreedta8** [comment]
I use ```chains=2``` option. What is the recommended number of chains?

```arviz.stats.stats_utils - WARNING - Shape validation failed: input_shape: (1, 500), minimum_shape: (chains=2, draws=4)```

**Comment by sreedta8** [comment]
I restarted my jupyter notebook and reran the entire analysis and the *arviz* warnings went away @ahartikainen. Just for my understanding what caused the error in the first place which the github version isable to address? Thanks for your help.
