### ISSUE TITLE
pystan backend support

### ISSUE THREAD

**Issue by sreedta8** [bambinos/bambi#274]
Hi 

Thanks to all the developers and contributors who develop(ed) bambi - In the R side, I use *brms* similarly as a front-end for *stan* and was excited to see *bambi* as a front-end to *pymc3 and pystan*. I read that the support for *pystan* will not continue in future releases. I would like to see this not be the case. I would like to contribute documentation and tutorial examples that demonstrate the use of *bambi* with both of these tools. I'm not an expert programmer and hence I cannot help on the developmend end. However, I apply Bayesian modeling across a range of industries and love to help support *bambi* and it's use for both *pymc3* and *pystan*.Having a tool such as *bambi* that allows both of these libraries is huge plus and I think it should be maintained. 

How should I go about developing the examples and who should I contact with finished examples / tutorials? I believe I can capture the perspective of a large number of applied users, for whom the entire Bayesian world is intimidating be it in R or Python.I would like to help in this regard. I would also like to see the support for *pystan* maintained.

Sree

**Comment by aloctavodia** [comment]
Hi @sreedta8 Thanks for you offer, documentation and tutorials are always welcome and valued! The decision to stop supporting pystan is mostly related to the lack of time from the current developers to support multiple backends. 

You can submit the examples as Pull Requests, you may find this [guide](https://github.com/bambinos/bambi/blob/master/CONTRIBUTING.md) useful. You can share more or less early drafts of the examples, specially if you need  feedback or have doubts.

**Comment by sreedta8** [comment]
@aloctavodia Thanks for that clarification with regards to supporting *pystan*. Are there plans to replace *pystan* with another library as a backend or will it be support only for *pymc3 / pymc4* for the foreseeable future(due to the constraints of time)? How much time commitment is required to maintain a backend such as "pystan"? I may jump into the deepend just to get grips of advanced programming with pystan, bambi and python. 

I'm a new user of github and may have questions after I develop the examples. Thanks for the link to the guide. I will look at it and get back to one of you with either questions or feedback.

**Comment by canyon289** [comment]
Hey @sreedta8. First off thanks for your enthusiasm! We're glad you're finding use in bambi and even more thrilled you're looking to help. By posting here you've definitely contacted the right people and we're happy to help you get started :)

The time commitment to maintain a package usually isn't too high, maybe 5 hours a week or so. The subtle difference though is it takes much more time to onboard and develop a package. However from personal experience I must say you learn a lot, and it feels good to be able to contribute so the effort is worth it!

As of now the plan I'm most aware of is that we use PyMC3 as a backend. (PyMC4 has also been deprecated)

Whether you want to contribute docs or contribute to the pystan backend were here to support you. As for the github stuff dont worry, it gets easier over time!

**Comment by sreedta8** [comment]
@canyon289 thank you for those encouraging words. Thanks for your work on *bambi* and *arviz*. Thanks for sharing additional details on the question of time committment. 

I'm an intermediate level user of Python for analytics purposes but I have been in advanced analytics and data science for the past 27 years. So I can contribute significantly towards documentation / tutorials / package testing. I would like to give back to this field and its' researchers and users in any way that I can. 

Thanks once again and I look forward to working with all of you and contributing to these initiatives.
