### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound] - "Anaconda Distribution"

### ISSUE THREAD

**Issue by MrCull** [bambinos/bambi#280]
The markup version of the readme that is displayed for the main page in this repo contains the following bad link:

"Anaconda Distribution"
Status code [404:NotFound] - Link: https://www.continuum.io/downloads

**Extra**

This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fbambinos%2fbambi
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=bambinos

--

I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or log an “Issue”.

**Comment by tomicapretto** [comment]
Thank you for this issue @MrCull! Great tool btw!
