### ISSUE TITLE
Contrasts

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#29]
We need to add support for contrasts, probably in an `add_contrast()` method that parallels `add_term()`.

**Comment by jake-westfall** [comment]
With the new `MCMCResults` class, users can retrieve the MCMC samples for any/all parameters as a pandas DataFrame using `results.to_df()` and then manipulate them however they wish, including computing "contrasts" i.e. linear transformations of the parameters. This seems easy enough that I'm not sure we really need additional functionality to support this kind of thing. Okay to close?

**Comment by tyarkoni** [comment]
Yep!

**Comment by tyarkoni** [comment]
Re-opening after twitter discussion with @junpenglao.

**Comment by junpenglao** [comment]
It is personal taste but I found having a 2D array as DM much easier to work with (also for figuring out the contrast). I found in the test you can get the DM by doing:
```python
X0 = np.asarry([tuple(t.data[:, lev]) for t in model0.fixed_terms.values()
              for lev in range(len(t.levels))])
```
Is there a more straightforward API for this?

**Comment by tyarkoni** [comment]
Don't think there is (but @jake-westfall can confirm). But there should be!

**Comment by junpenglao** [comment]
hmm, also fyi: doing
```python
X0 = np.asarry([tuple(t.data[:, lev]) for t in model0.fixed_terms.values()
              for lev in range(len(t.levels))])
```
The column order is different compare to the output from `fitted.to_df()`. Even more annoying is that `model.fixed_terms.keys()` change order every time I rerun? Is it not a OrderedDict?

**Comment by jake-westfall** [comment]
We actually have a couple lines of code in `Model.build()` that builds the fixed-effects design matrix (actually a pandas dataframe) in order to compute a few diagnostic stats, but then we don't currently store the design matrix. So it would be really simple to store that design matrix as an attribute of the Model. But maybe an accessor method in the MCMCResults object would be nicer?
