### ISSUE TITLE
Removing geweke in ArviZ broke something

### ISSUE THREAD

**Issue by canyon289** [bambinos/bambi#297]
Failure shown in CI. I havent investigated this yet
https://travis-ci.org/github/bambinos/bambi/jobs/758874610#L1098

Ok now looked into it. It looks like a PyMC3 issue

**Comment by tomicapretto** [comment]
I think this is not a problem anymore. Can we close this?

**Comment by canyon289** [comment]
I think to too. PyMC3 I believe is updated
