### ISSUE TITLE
Delete/modify Model.dm_statistics

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#307]
The object `Model.dm_statistics` has two main usages now.

1. Provides the `PriorScaler` with the mean values that are used to scale some terms, i.e.

https://github.com/bambinos/bambi/blob/d986fc72cbd654be2ceeccf310f1cfaa42e584f7/bambi/priors.py#L202-L204

and

https://github.com/bambinos/bambi/blob/d986fc72cbd654be2ceeccf310f1cfaa42e584f7/bambi/priors.py#L335-L336

2.  To raise an error when there's "perfect collinearity" between predictors, i.e. 

https://github.com/bambinos/bambi/blob/d986fc72cbd654be2ceeccf310f1cfaa42e584f7/bambi/models.py#L203-L211

I think we can improve the current approach by doing the following

For usage `#1`, we can keep computing these means without needing to fit the models and obtaining all the other statistics.  
For usage `#2`, we could check if the design matrix is full rank. 

I could make a PR if we agree. And note that current behaviour in `#2` prevents Bambi to work with sparse settings.

**Comment by aloctavodia** [comment]
agreed

**Comment by tomicapretto** [comment]
Closing with #309
