### ISSUE TITLE
Feature request: Multinomial regression

### ISSUE THREAD

**Issue by ricardoV94** [bambinos/bambi#318]
Using the softmax link for categorical outputs.

**Comment by tomicapretto** [comment]
Hi @ricardoV94, thanks for the suggestion! It makes total sense. If nobody handles this within the next week, I will work on it.

Thanks again for the idea!

**Comment by jlevy44** [comment]
Thanks!

**Comment by ricardoV94** [comment]
By the way, there was some discussion in a pymc3/resources issue about multinomial models, specially on the difference between category intercepts (where you should have at most k-1 coefficients), and shared and non-shared coefficients for predictors in multinomial models (where you can have one or k coefficients): https://github.com/pymc-devs/resources/issues/117#issuecomment-714343532

I found the two references there very helpful to understand these types of GLM. Most Python libraries offer only a limited subset of multinomial models (e.g., non-shared coefficients for k-1 categories).

**Comment by tomicapretto** [comment]
@ricardoV94 thanks for the reference! I'm going to have a deeper look at it when working on this. Unfortunately, I had to work on other things in Bambi that were more urgent. We're planning to do a release after #349 is merged, and then multinomial models will be one of the first things (or the first thing) we are going to do.

**Comment by tomicapretto** [comment]
@ricardoV94 I don't know if you know [Categorical Data Analysis by Alan Agresti](https://www.wiley.com/en-us/Categorical+Data+Analysis%2C+3rd+Edition-p-9780470463635). I used that book in college and was really helpful. I'm reading it again to refresh this multinomial regression stuff before coding.

**Comment by ricardoV94** [comment]
Yeah Agresti is a classic. Haven't heard about the second one.

On a practical standpoint I think the R library (second link in the referenced comment I shared before) is a reasonable way to specify this type of models.

It something like `y ~ X1 | X2 | X3` where X1 to X3 correspond to these different types of coefficients (shared[1], distinct[k-1], distinct[k]):

* X1 are used for cases where in each observation the different categories have different values for the same variable and you want to weight them on the same scale (e.g. price in dollars)
* X3 are like X1 but you want to use different weights for the different categories (e.g. travel duration by airplane vs travel duration by bus).
*X2 (which should probably be the first) are for those variables that vary across observations but not across categories (e.g. the socioeconomic status of the person making the choice). Intercepts are part of this category.

**Comment by huangziwei** [comment]
thank you very much for this new update! Will it be available on PyPi soon?

**Comment by tomicapretto** [comment]
@huangziwei I would like to work on #432 and/or #422 before having a new release. I'm not sure if that's doable before finishing the year. Maybe we can have a new release in the first month of 2022 :)

**Comment by tomicapretto** [comment]
@ricardoV94 I know it's been quite a long time,but finally we have multinomial regression as well as categorical regression in Bambi :). See #490 .

You can see the code in the tests if you're interested in more examples. https://github.com/bambinos/bambi/blob/3658ff88d99d2926757b1de9173a438198d5ff3f/bambi/tests/test_predict.py#L257-L304

**Comment by ricardoV94** [comment]
Awesome @tomicapretto, I'll have a look
