### ISSUE TITLE
In add_term interface, adding random slopes overwrites corresponding fixed slope

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#32]
Here is a random slopes model specified both via the formula interface and the add_term interface:

    # build model using formula
    modelA = Model(crossed_data)
    modelA.fit('Y ~ continuous', random=['continuous|subj'], run=False)
    modelA.build()

    # build model using add_term
    modelB = Model(crossed_data)
    modelB.add_y('Y')
    modelB.add_intercept()
    modelB.add_term('continuous', random=False)
    modelB.add_term('subj', random=True)
    modelB.add_term('continuous', split_by='subj', random=True)
    modelB.build()

The model specified via the formula interface ends up with the expected terms:

    modelA.terms
    # OrderedDict([('Intercept', <bambi.models.Term at 0x196889c50>),
    #              ('continuous', <bambi.models.Term at 0x1968864a8>),
    #              ('subj', <bambi.models.RandomTerm at 0x19683a908>),
    #              ('continuous|subj', <bambi.models.RandomTerm at 0x19686f438>)])

But the model specified via add_term, which I believe should be the equivalent model, has lost the fixed slope:

    modelB.terms
    # OrderedDict([('Intercept', <bambi.models.Term at 0x19686f0b8>),
    #              ('continuous', <bambi.models.RandomTerm at 0x196950358>),
    #              ('subj', <bambi.models.RandomTerm at 0x196950ef0>)])

The random terms labels don't match, as you've noted elsewhere, but that's not really a big deal because the terms themselves are the same. Anyway, this problem likely has something to do with the fact that the label for the random slopes coincides with the label for the corresponding fixed slope.

**Comment by tyarkoni** [comment]
This should be solved in the changes I'm about to push. I've now replaced `split_by` with an `over` argument that behaves just like the `|` operator. The result is that when you call `add_term('condition', random=True, over='subject')`, you know get a term with the label `"condition|term"` by default. I've edited all the tests and am just waiting on them to pass before pushing.

**Comment by jake-westfall** [comment]
Cool :)

**Comment by tyarkoni** [comment]
Closing this, as it should be taken care of by fc672d47, as described above.
