### ISSUE TITLE
Categoricals do not have information about which category they come from

### ISSUE THREAD

**Issue by twiecki** [bambinos/bambi#322]
This is probably not easily solvable but if there's a categorical, the posterior only shows `x[0]`, `x[1]` but the label information is lost. Perhaps in a summary table (https://github.com/bambinos/bambi/issues/321) this information could be added, like it's present in `dm_stats`.

**Comment by tomicapretto** [comment]
I'm not sure where you see the posterior shows `x[0]`, `x[1]`, etc. The following is one of the examples from the documentation and shows the levels of the categorical variables when we pass it to `az.summary()` or `az.plot_trace()`

![image](https://user-images.githubusercontent.com/25507629/113620870-43ccef00-9631-11eb-85ae-595658ca6eb3.png)

![image](https://user-images.githubusercontent.com/25507629/113620917-55ae9200-9631-11eb-8bf9-42bec4b0fd31.png)

I'm thinking these labels may be redundant, but that could be fixed without much effort.

**Comment by twiecki** [comment]
Huh, yeah that's exactly what I'm looking for but that's not what I got (I got 0, 1, ...). Let me see if I can recreate.

**Comment by tomicapretto** [comment]
Maybe related to ArviZ version?

**Comment by canyon289** [comment]
@twiecki, you know the drill if this is still an issue reopen it.
