### ISSUE TITLE
For categorical outcomes, tell user which event is being modeled 

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#35]
When the outcome is categorical, such as in logistic regression, and the outcome consists of, say, strings such as 'yes' and 'no', bambi makes some decision about which event to model (i.e., whether the estimated probabilities are P(y='yes') or P(y='no'), but this decision is silent. We should print a standard message with the model output (or even during fitting?) that lets users know which event is being modeled. If the outcome is an array of 0's and 1's, then one can probably assume that it is modeling P(y=1) (and in fact I've verified that this is true in at least one case), but even here it would be nice to be assured.

**Comment by jake-westfall** [comment]
In at least one dataset (the ANES dataset I'm working on), when given an integer array of 0s and 1s as an outcome, bambi decides to model P(y=0), exactly opposite of what one expects.

**Comment by tyarkoni** [comment]
That's... bizarre. No idea why that would happen. Will take a look if you can't figure it out, but for now maybe just manually invert the coding so we can wrap up the paper. :)

**Comment by tyarkoni** [comment]
Any chance the column was coded as an object in the pandas DataFrame, even though it was supposed to be an int? Sometimes pandas assigns a conservative dtype when it reads in a file. If that happened here, I think it would actually explain your observation. When `pd.get_dummies` is called, I think it creates levels in order of occurrence. So if you had a 1 before a 0, the two columns would be 1 and 0, and then if drop_first=True (which is the default), you would end up with the second column coding for presence of 0.

If that's not it, then I'm out of ideas.

**Comment by jake-westfall** [comment]
I'm pretty sure I checked that it had the column had dtype=int, but in any case, I'll get to the bottom of this soon.

**Comment by jake-westfall** [comment]
Well, I guess the good news is that I can't seem to recreate, even on the same datatset, the behavior of the model choosing to model the 0s when the outcome is an integer array of 0s and 1s. So now the task is just to:

- Print an informative message with the either during the model-building or mode-summary stages letting the user know for sure which event is being modeled
- Ideally, install some mechanism for letting the user decide this in advance that is more elegant than computing the 0-1 array to use as the outcome before initializing the Model.

**Comment by jake-westfall** [comment]
Closing because this will be addressed by the new_summary branch PR.
