### ISSUE TITLE
How to implement predictions

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#357]
I would like to implement a `Model.predict()` method. My original idea was to replicate `predict()` in R, where we pass a data frame and obtain predictions for the mean response. However, @aloctavodia helped me to realize we should consider both predictions for the mean response and predictions for the response variable (like what is being done with `Model.posterior_predictive()` but also available for out-of-sample data).

So, what I have in mind is something as follows 

```
predictions = model.predict(idata, kind, xdata=None)
```

where `kind = "mean"` returns predictions in terms of the mean response (i.e. g^-1(x'b)) and `kind="response"` returns the posterior predictive distribution. If `xdata` is a data frame, predictions are made using the new data set (out of sample predictions). If not, predictions are made using the original sample (in sample predictions).

What I would like to discuss

* We already have a `Model.posterior_predictive()` method that samples the posterior predictive distribution, using the observed values for the predictors. There's overlap between this method and the one I want to implement. Should we keep both? Only one? I don't want to have two methods doing something similar (or the same thing), but we have to be aware dropping `Model.posterior_predictive()` is another API change and can break existing code. Maybe a deprecation warning?
* Argument names and default behavior.
* Anything you would like to add to this discussion.

Linking #356, where this feature is requested.

**Comment by ioannis12** [comment]
hello, 

congrats for the work. 
I have a model,  model = Model('A ~ 0 + B + C  + D +  (1|E)', f_delta, family = 'bernoulli')
I would like to make predictions on test set, any idea how the predict function looks like?
There is a predict function in the neg binomial example but is not for mixed effects models. 

cheers

**Comment by tomicapretto** [comment]
Hi @ioannis12 

This is an example of how you could do it for mixed-effects models. I used simulated data so it may differ from yours. 


```python
import bambi as bmb
import numpy as np
import pandas as pd

from scipy.special import expit
```

My simulated data

```python
f_delta = pd.DataFrame({
    "A": np.random.choice([0, 1], size=100),
    "B": np.random.normal(size=100),
    "C": np.random.normal(size=100),
    "D": np.random.normal(size=100),
    "E": ["Group 1"] * 25 + ["Group 2"] * 25 + ["Group 3"] * 25 + ["Group 4"] * 25
})
```

Same model

```python
model = bmb.Model('A ~ 0 + B + C + D + (1|E)', f_delta, family = 'bernoulli')
idata = model.fit()
```

I just grab some samples from my original data to act as a test data, here you will have your test data.

```python
# Select some random rows from the original data
rows = np.random.choice(np.arange(data.shape[0]), size = 20)
f_delta_2 = f_delta.iloc[rows, :]
```
 Take the posterior from the inference data result, and stack chains and draws.

```python
posterior = idata.posterior.stack(sample=["chain", "draw"])
```

And now, perhaps, the most tricky part. In mixed-effects models, you have something like 

$y = X\beta + Zu$, so we need to construct both X and Z, for the common and group-specific parts respectively. Here we use a method from the internal design object in the model. This is what we want to avoid people from doing with a higher-level implementation of predictions. But since it's not available yet, here we go.

```python
X = model._design.common._evaluate_new_data(f_delta_2).design_matrix
Z = model._design.group._evaluate_new_data(f_delta_2).design_matrix.toarray()
```

The coefficients beta and u are taken from the posterior.

```python
# Coefficients for common and group specific parts
β = np.vstack([np.atleast_2d(posterior[name]) for name in model.common_terms])
# I just grab the only group-specific term in the model. Otherwise you could use a comprehension as above,
# but using `model.group_specific_terms`.
u = np.vstack([np.atleast_2d(posterior["1|E"])])
```

And finally, compute the linear predictor and pass it to the `expit()` function (to convert from log-odds to probability scale). You can summarize the posterior for each individual with the mean, or any other function you want. Or you can just keep the posterior!

```python
predictions = expit(np.dot(X, β) + np.dot(Z, u))
predictions.mean(1)
```
```
array([0.72031907, 0.42519583, 0.56074857, 0.4676208 , 0.43403285,
       0.4408966 , 0.49711422, 0.49851915, 0.41220761, 0.57956251,
       0.59578587, 0.63213104, 0.53078604, 0.68282899, 0.43710477,
       0.49711422, 0.52201541, 0.35639774, 0.64629308, 0.35083164])
```

**Comment by ioannis12** [comment]
sweet, I just tried it out and it's working :D
congratulations again for your work!

**Comment by gregorystrubel** [comment]
Hello @tomicapretto,

Thanks a lot for your work.

Did you consider to use prediction function to plot response respect to a particular predictor variable ? 

The use case is the same described in the cell 17 of https://docs.pymc.io/pymc-examples/examples/generalized_linear_models/GLM-logistic.html

I think it could replace the deprecated pm.plot_posterior_predictive_glm function if we could link the result of prediction function to ArviZ plot functions (for example plot_hdi). Furthermore, it will permit to not rewrite the model.

But this will need to use ArviZ format for the output.

**Comment by tomicapretto** [comment]
Hi @gregorystrubel. Yes, this is something I want to definitely implement in Bambi. There are a couple of things before that in my TODO list like adding more model families, but it will come after that. At that time, I'm going to link the PR here so you can see the progress or make any comments if you want.

**Comment by ioannis12** [comment]
hello, 

sorry to bother you again, I have another question about mixed models, how would the prediction look like if in my previous example a random slope is added. 
The model would be like, model = Model('A ~ 0 + B + C + (1 + E|D)', f_delta, family = 'bernoulli')

kind regards

**Comment by tomicapretto** [comment]
@ioannis12, what if you do everything as above, except the following part?

```python
# Coefficients for common and group specific parts
β = np.vstack([np.atleast_2d(posterior[name]) for name in model.common_terms])
u = np.vstack([np.atleast_2d(posterior[name]) for name in model.group_specific_terms])
```
And then, again as above
```
predictions = expit(np.dot(X, β) + np.dot(Z, u))
predictions.mean(1)
```

**Comment by ioannis12** [comment]
thank you for the prompt reply!

`predictions = expit(np.dot(X, β) + np.dot(Z, u))
`

I'm getting this error when I run it 


> predictions = expit(np.dot(X, β) + np.dot(Z, u))
> Traceback (most recent call last):
> 
>   File "<ipython-input-35-28623832fcf0>", line 1, in <module>
>     predictions = expit(np.dot(X, β) + np.dot(Z, u))
> 
> ValueError: operands could not be broadcast together with shapes (844,4000) (1688,4000)

**Comment by tomicapretto** [comment]
I think that is a problem with formulae, the library that parses model formulas. Could you update to last formulae version? I think that is 0.1.1. If that doesn't work, try with the development version please.

**Comment by ioannis12** [comment]
I just updated from 0.1.0 to 0.1.1. but now when I run the Model() I get another error message:

> ValueError: The response term must be of class Term, not <class 'formulae.terms.terms.Term'>.

**Comment by tomicapretto** [comment]
And what if you install Bambi from the development version? I'm using Bambi development version, and formulae 0.1.1 and I can't reproduce the problem, i.e., the following works

```python
import bambi as bmb
import numpy as np
import pandas as pd

f_delta = pd.DataFrame({
    "A": np.random.choice([0, 1], size=100),
    "B": np.random.normal(size=100),
    "C": np.random.normal(size=100),
    "D": np.random.normal(size=100),
    "E": ["Group 1"] * 25 + ["Group 2"] * 25 + ["Group 3"] * 25 + ["Group 4"] * 25
})

model = bmb.Model('A ~ 0 + B + C + D + (1|E)', f_delta, family = 'bernoulli')
idata = model.fit()
```

Do 

```
pip uninstall bambi
pip uninstall formulae
pip install formulae # this should be 0.1.1
pip install git+https://github.com/bambinos/bambi.git
```

**Comment by ioannis12** [comment]
yes, that works!
thank you for your help!

**Comment by tomicapretto** [comment]
@ioannis12 @gregorystrubel the PR #372 implements predictions for Bambi. Feel free to leave your suggestions if you want. Thanks!

**Comment by gregorystrubel** [comment]
Thanks a lot Tomas

Le mar. 13 juil. 2021 à 13:59, Tomás Capretto ***@***.***> a
écrit :

**Comment by tomicapretto** [comment]
#372 has been merged.
