### ISSUE TITLE
ValueError: Factor on right hand side of group specific term must be a single term.

### ISSUE THREAD

**Issue by zwelitunyiswa** [bambinos/bambi#358]
Thanks for all the great work with Bambi. It has been a godsend for my work.

I tried to implement the following formula:

y ~ time * tx + (time | therapist/subjects)

which expands to:

y ~ time * tx + (time | therapist:subjects) + (time | therapist)

and I get the following error:

"ValueError: Factor on right hand side of group specific term must be a single term"

Is it possible to implement three-level conditional hierarchical models or am I simply writing this incorrectly? If I am writing it incorrectly, how would I need to reformat it to work with bambi/formulae?

**Comment by tomicapretto** [comment]
Hi! Thanks for opening this issue!

It's actually something I missed when working in formulae. It's nothing wrong on your end at all. 

I'll try to fix it as soon as possible (< week). As far as I recall it shouldn't be too much work. I'll let you know here when formulae is updated. 

Thank you again for reporting this problem and sorry for the inconveniences.

**Comment by zwelitunyiswa** [comment]
No problem! Thank you so much. I appreciate all the work you and the team have done over the past couple of months. It's amazing where you guys are taking Bambi.

**Comment by tomicapretto** [comment]
@zwelitunyiswa I've opened a PR in formulae to have interactions in the group part of group-specific effects. Could you install formulae from that PR and let me know if it is working as expected for your problem?

**Comment by zwelitunyiswa** [comment]
I installed the PR in Formulae using:

!pip install scipy==1.5.4 # fixes scipy.linalg khatri_roa issue
!pip install bambi==0.5.0
!pip install git+https://github.com/bambinos/formulae.git@refs/pull/31/head

import scipy 
import numpy as np
import pandas as pd
import altair as alt
import arviz as az
import pymc3 as pm
import formulae
import bambi as bmb

I tried running the following formula:
 
score ~ quarters_elapsed * status + (quarters_elapsed|state/provnum)

but get the same error. 

I attached some screenshots that might be useful.
![Screen Shot 2021-05-22 at 8 16 16 PM](https://user-images.githubusercontent.com/32966743/119244081-cd317580-bb3a-11eb-955e-93fd771bf1f7.png)
![Screen Shot 2021-05-22 at 8 16 42 PM](https://user-images.githubusercontent.com/32966743/119244083-cf93cf80-bb3a-11eb-9b67-f0f283601bc2.png)

**Comment by tomicapretto** [comment]
formulae is one of Bambi's dependencies. I'm not an expert on this, but I think that formulae version 0.10.0 is being installed when you install Bambi. Then, when you do `!pip install git+https://github.com/bambinos/formulae.git@refs/pull/31/head`, it does not install anything because formulae version 0.10.0 is already installed. 

Could you try removing Bambi and formulae, and then installing them in this order?

```
pip install git+https://github.com/bambinos/formulae.git@refs/pull/31/head
pip install bambi
```

**Comment by zwelitunyiswa** [comment]
You are right. I reversed the order and now the PR works. I have attached an image showing the sampler running, with the state factor showing. 

![Screen Shot 2021-05-22 at 9 03 42 PM](https://user-images.githubusercontent.com/32966743/119244735-682d4e00-bb41-11eb-84a1-8cad752c7b65.png)

**Comment by tomicapretto** [comment]
That's great!

I'm leaving this issue open because the PR isn't finished yet. Just let me know if there's something not working as expected.

And thanks for the warm words earlier! :smile:

**Comment by zwelitunyiswa** [comment]
Much deserved, mate. Thank you again.

**Comment by zwelitunyiswa** [comment]
I am not sure if this related? When I make the models more complex I get this error [see attached].

Another I get is one that is division by 0 (this one might be on my dataset, which I have to check). 

![Screen Shot 2021-05-24 at 9 30 54 AM](https://user-images.githubusercontent.com/32966743/119355207-fce39900-bc72-11eb-95c1-ec915068f8d0.png)

**Comment by tomicapretto** [comment]
Hmm.. That error is coming from PyMC3, but may be something wrong on Bambi's end. Could you show me the output when you print `model` before calling `model.fit()`? There we should see the priors Bambi selected

**Comment by zwelitunyiswa** [comment]
Here you go.

![Screen Shot 2021-05-24 at 9 55 05 AM](https://user-images.githubusercontent.com/32966743/119358045-3964c400-bc76-11eb-9cad-6ea3472293d6.png)

**Comment by tomicapretto** [comment]
What happens if you use the following formula? 

`"score ~ quarters_elapsed * state + (quarters_elapsed | state:provnum) + (quarters_elapsed | state) + (status | state) "`?

I suspect there is a problem with `"(quarters_elapsed:status|state)"`. As far as I can tell, both `quarters_elapsed` and `status` are categoric. I suspect the interaction is not working.

**Comment by tomicapretto** [comment]
If there's a chance you could share a dataset that looks like your data (it does not necessarily need to be your data) I could try to replicate the issue and find a solution for the problem. I tried to come up with a fake dataset on my side but I'm not sure about some variable types.

**Comment by zwelitunyiswa** [comment]
Ok. I will simulate data like mine. I have meetings the next couple of hours but will send when I free up.

**Comment by tomicapretto** [comment]
@zwelitunyiswa do you still have problems with the model you were trying to fit?

**Comment by zwelitunyiswa** [comment]
Hi Tomi, 

Sorry for the delay. I was traveling for business.

The model is still working. I was trying this model:

model = bmb.Model('score ~ time * status + (time | id:state) + (1 | state) + (0 + status | id) + (0 + time | state) + (0 + time:status | state)',
                  data2
                  )

The model check runs fine. But when I run the fit, I get "Input dimension mis-match. (input[0].shape[1] = 7, input[1].shape[1] = 2)" 

I can get it to start running if I apply group_specific priors:

priors={'group_specific':bmb.Prior('Normal', mu=0, sigma=bmb.Prior('HalfNormal', sigma=.018))}

model = bmb.Model('score ~ time * status + (time | id:state) + (1 | state) + (0 + status | id) + (0 + time | state) + (0 + time:status | state)',
                  data2,
                  priors=priors
                  )

I then either get the error from above, or the session just crashes. 

Here is the link to the test data: [link to data](https://raw.githubusercontent.com/zwelitunyiswa/public_data/master/bambi_data.csv)

This thing has me stumped.

**Comment by zwelitunyiswa** [comment]
> quarters_elapsed * state + (quarters_elapsed | state:provnum) + (quarters_elapsed | state) + (status | state)

**Comment by zwelitunyiswa** [comment]
I tried your model as well:

model = bmb.Model('score ~ time	 * state + (time | state:id) + (time | state) + (status | state)',
                  data2,
                  priors=priors
                  )

But when I run the fit, I get "Input dimension mis-match. (input[0].shape[1] = 7, input[1].shape[1] = 2)" . The same error as above.

**Comment by zwelitunyiswa** [comment]
I did not mean to close this issue. Hit the wrong button.

**Comment by tomicapretto** [comment]
Hi @zwelitunyiswa, no problem about the delay! I'm currently working on the issue, modifying several things under the hood that should fix your issue. Thanks for sharing your data, I will use it to test my modifications :smile:

**Comment by zwelitunyiswa** [comment]
Great. Thank you. As an aside, I am thinking of starting a Bayes for Business blog series using Bambi/PYMC 3 as the tools, with the emphasis on Bambi. I can write the articles and do the setup, would you interested in proofing on the technical side? I would of course attribute/cite you and your work with Bambi.

**Comment by tomicapretto** [comment]
Yes, I would really like to review your work! Thanks!

**Comment by tomicapretto** [comment]
I've updated PR #359 and it _seems_ to work.  Some notes:

* Install Bambi from that PR. You first have to update formulae to version 0.1.0 (I've just released it).
* I've tried the following model formulas
  + `"score ~ time * status"` works.
  + `"score ~ time * status + (0 + status|id)"` works.
  + "score ~ time * status + (time:status | state) + (0 + status|id)"  works, with some divergences.
  + `"score ~ time * status + (time | state / id) + (time:status | state) + (0 + status|id)"` _seems_ to work, but I gave up beacuse the sampler was taking to long (estimated in more than 1:30 hr)
* I have multiplied the score by 100. It helped the sampler.

In my opinion, using `id` as a grouping variable is causing problems here. It has 1303 levels for the data you shared, which means we have 1303 group-specific effects! And we have 10154 observations. 

Well, have a try on your side, and let me know if thins work or not

**Comment by zwelitunyiswa** [comment]
Thanks, Tomi. The sampling is now working! You are sheer class, mate.

Let me test for the next day or so, and I will let you know how the model(s) turn out. To speed up testing, I decreased the time factors from eight down to three. 

![Screen Shot 2021-06-12 at 4 10 29 PM](https://user-images.githubusercontent.com/32966743/121788131-c5447e80-cb98-11eb-9a9d-461981a4723b.png)

**Comment by tomicapretto** [comment]
#359 has been merged. The original issue about `ValueError: Factor on right hand side of group specific term must be a single term.` is fixed. Please don't hesitate to open another issue if you have any problems with the model you've shared here.
