### ISSUE TITLE
Add `Likelihood` class

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#364]
From our [Getting Started](https://bambinos.github.io/bambi/master/notebooks/getting_started.html#Families) section, this is how you create and use a custom family.

```python
from bambi import Family
import theano.tensor as tt

# Specify how the Bernoulli p parameter is distributed
prior_p = Prior('Beta', alpha=2, beta=2)

# The response variable distribution
prior = Prior('Bernoulli', p=prior_p)

# Set the link function. Alternatively, we could just set
# the link to 'logit', since it's already built into Bambi.
# Note that we could pass in our own function here; the link
# function doesn't have to be predefined.
link = tt.nnet.sigmoid

# Construct the family
new_fam = Family('bernoulli', prior=prior, link=link, parent='p')

# Now it's business as usual
model = Model("admit ~ gre + gpa + rank", data, family=new_fam)
results = model.fit()
```

Wouldn't it make more sense to have a `likelihood` argument instead of the existing `prior` one? I think we could have a `Likelihood()` class for this purpose, which would be clearer than using `Prior()` to specify the likelihood.

And actually, this part

```python
# Specify how the Bernoulli p parameter is distributed
prior_p = Prior('Beta', alpha=2, beta=2)

# The response variable distribution
prior = Prior('Bernoulli', p=prior_p)
```
is misleading because `p` does not have that prior when the model is built because it is declared as the `parent`.

**Comment by aloctavodia** [comment]
I agree this is weird. But the weird thing is the need to define 

prior = Prior('Bernoulli', p=prior_p)

Instead of just doing something like.

prior = Prior('Beta', alpha=2, beta=2)
new_fam = Family('bernoulli', prior=prior, link=link, parent='p')

**Comment by tomicapretto** [comment]
But this "prior" `prior = Prior('Beta', alpha=2, beta=2)` is not used, that Beta distribution goes nowhere in the model. 

This is what I mean with the `Likelihood` class.

```python
class Likelihood(name, priors=None, parent=None):
    """
    'parent' must not be in 'priors'. 'parent' is inferred from the 'name' if it is a known name

    Parameters
    ----------
    name: str
        Name of the likelihood function (PyMC3 distribution name)
    priors: dict
        Optional dictionary that contains prior distributions for auxiliary parameters in the likelihood. 
    parent: str
        Optional specification of the name of the mean parameter in the likelihood.
        This is the parameter whose transformation is modeled by the linear predictor.
    """
```

This would be the thing for logistic regression

```python
link =  tt.nnet.sigmoid
likelihood = Likelihood("Bernoulli")
Family('bernoulli', likelihood=likelihood, link=link)
```

and this would be for normal linear regression

```python
link = lambda x: x
priors = {"sigma": Prior("HalfStudentT", nu=4, sigma=10)}
likelihood  = Likelihood("Normal", priors = priors)  
Family('gaussian', likelihood=likelihood, link=link)
```

---

In the future, this could also enable us to work with custom PyMC3 distributions. Instead of passing a name, you pass the 
PyMC3 distribution, and specify both `priors` and `parent`.

**Comment by aloctavodia** [comment]
But my point is that it should be used.  Otherwise you need to define a likelihood using a Prior class, or introduce a Likelihood class, as you are suggesting. But conceptually it will be much more simple and clear if we have just prior and families (or priors and likelihoods), not prior, likelihood and families.

**Comment by aloctavodia** [comment]
Or maybe instead of having a Prior and Likelihood class, we should have a Distribution class (as pymc have). And now that we are here, what about a Potential and DensisityDist?
