### ISSUE TITLE
Drop statsmodels dependency?

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#37]
It turns out that `pd.stats.api.ols` internally calls statsmodels, so we haven't actually eliminated the statsmodels dependency. We can either switch to `np.linalg.lstsq`, or just explicitly call statsmodels. The pandas stats API is actually deprecated, so we'll need to change either way. I'd prefer to avoid requiring statsmodels, since we're only using it for least-squares fitting, but if you prefer its interface to numpy's for the stuff in `Model.build()`, @jake-westfall, that's fine.

**Comment by tyarkoni** [comment]
Actually, on the assumption that we'll eventually use statsmodels as an alternate back-end for at least some models, it might be worth leaving in.

**Comment by jake-westfall** [comment]
Yes, also I think we will ultimately need to replace those OLS calls with logistic regression calls (or, more generally, GLM calls) when fitting GLM(M)s, as discussed in #34, so we probably won't be able to avoid a statsmodels dependency in any case.

**Comment by tyarkoni** [comment]
Okay, closing and re-adding statsmodels as a dependency.
