### ISSUE TITLE
Binomial Family

### ISSUE THREAD

**Issue by zwelitunyiswa** [bambinos/bambi#371]
@tomicapretto 

Quick question. I notice you are adding the Student-T and Beta families. Are there are plans to add the Binomial family like in BRMS, like so?

  brm(data = d, family = binomial,
      pulled_left | trials(1) ~ 1 + prosoc_left,
      prior = c(prior(normal(0, 10), class = Intercept),
                prior(normal(0, 10), class = b)),
      seed = 10)

Thanks for your kind attention.

**Comment by tomicapretto** [comment]
Hi @zwelitunyiswa! 

I've been thinking about adding the binomial family. It's something that will definitely happen in the future, but it's not the priority now. After adding t and beta, I'll try to add splines. 

In addition, I'm not sure if the brms notation is the approach we may use in Bambi for the LHS of the formula. That would mean the pipe operator has two very different meanings, which is something I'd like to avoid.

**Comment by zwelitunyiswa** [comment]
Cool. Thank you.

**Comment by tomicapretto** [comment]
@zwelitunyiswa this addition is happening in #386

**Comment by zwelitunyiswa** [comment]
This is great news! Thanks for letting me know.

**Comment by tomicapretto** [comment]
#386 has been merged
