### ISSUE TITLE
add citation file

### ISSUE THREAD

**Issue by aloctavodia** [bambinos/bambi#405]
Not sure if this works with arxiv IDs if not we can wait until the paper gets published. 
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files

**Comment by aloctavodia** [comment]
This add an entry to the Github repository sidebar. Not sure if Google Scholar scrawls github for references. In our case we want to add an [arxiv entry](https://arxiv.org/abs/2012.10754), so that's already on Google Scholar profiles.

**Comment by tomicapretto** [comment]
Done https://github.com/bambinos/bambi/pull/407
