### ISSUE TITLE
Logistic Regression doesn't match manual model

### ISSUE THREAD

**Issue by JohnGoertz** [bambinos/bambi#428]
I'm performing logistic regression with a dataset of 40 patients diagnosed positive/negative with 4 predictors, but my results using Bambi aren't matching my results when I set up the model manually. ~Also, the posterior predictive "spaghetti plots" I get using bambi's `model.predict` don't seem right.~

I've put together a reproducible colab notebook using surrogate data: https://colab.research.google.com/drive/1PV0wZU9nKucfrqjVTqMfpZtbSEVXYg2x?usp=sharing.

You can see the posteriors are quite different between the two models, ~but there's another issue with Bambi's posterior predictive results. The "probability space" curves obtained using `bmb_model.predict(bmb_idata, data=new_data, kind='mean')` should be monotonic sigmoids, yet you can see some of the samples are non-monotonic (particularly for "D"). Additionally, the logit of the probability should give a straight line, but those below are curved. Maybe I'm using `predict` wrong, but if that's the case how do I retrieve the conditional probabilities/log-odds?~ (EDIT: This was my fault, but others may make the same mistake. See comment below. The discrepency between posteriors remains.)

### Model:
```python
# Initialize the fixed effects only model
bmb_model = bmb.Model('Dx ~ 0 + ' + ' + '.join(genes), cntr_patients_f, family="bernoulli")

# Fit the model using 10000 on each of 4 chains
bmb_idata = bmb_model.fit(draws=10000, chains=4, random_seed=SEED)
```
### Posterior:
![image](https://user-images.githubusercontent.com/9869969/141654317-4f92d953-c657-4a6b-99ad-f76d280a2e6b.png)
### Posterior predictive:
![Bambi regression probability space](https://user-images.githubusercontent.com/9869969/141655337-fe5655df-3724-46da-a0f0-e164b3cde57d.png)
![Bambi regression log-odds space](https://user-images.githubusercontent.com/9869969/141655335-cbe0c8dd-a0d1-41a3-b9e2-20711461d9c5.png)

### Model
```python
coords = {'gene': genes, 'sample': cntr_patients_f.index}
with pm.Model(coords = coords) as model:
    data = pm.Data('data', cntr_patients_f[genes].values, dims=('sample','gene'))
    
    # Use bambi's auto-scaled priors
    prior_mus = np.zeros(len(genes))
    prior_sigmas = np.array([prior['sigma'] for prior in bmb_model.scaler.priors.values()])
    
    slopes = pm.Normal('slopes', prior_mus, prior_sigmas, dims='gene')
    
    logit_p = pm.Deterministic('logit_p', pm.math.sum(data*slopes, axis=1))
    p = pm.Deterministic('p', pm.math.invlogit(logit_p))
    _ = pm.Bernoulli('Dx', p=p, observed=cntr_patients_f.Dx.values)
    
    idata = pm.sample(draws=10000, chains=4, return_inferencedata=True, random_seed=SEED)
```
### Posterior:
![image](https://user-images.githubusercontent.com/9869969/141654337-f1d348be-b2fe-4aa7-a35c-94fa4a988860.png)
### Posterior predictive:
![Manual regression probability space](https://user-images.githubusercontent.com/9869969/141654419-a84c0b7b-7f5e-4212-a965-379060e1c8d5.png)
![Manual regression log-odds space](https://user-images.githubusercontent.com/9869969/141654414-dc72e038-c380-4c9a-8db6-789fd818ad3a.png)

**Comment by JohnGoertz** [comment]
Initially I thought Bambi's `model.predict` was giving weird results, but turns out I had copied the example a little too uncritically. Specifically, [this section](https://bambinos.github.io/bambi/main/notebooks/logistic_regression.html#Spaghetti-plot-of-model-predictions) suggests averaging across chains:

```python
# Compute mean across chains
posterior_mean = clinton_fitted.posterior["vote_mean"].values.mean(0)

# Select 1000 draws
posterior_mean = posterior_mean[:1000, :]
```

That approach for my data gives these plots:

![Chain-averaged result log-odds space](https://user-images.githubusercontent.com/9869969/141660303-2106f05c-1ef3-4487-a0ab-7c2a72406ff6.png)

![Chain-averaged result probability space](https://user-images.githubusercontent.com/9869969/141660323-76570c40-a1c5-4f52-a30a-210d5b9be91d.png)

I think this is incorrect, since it leads to samples that are non-monotonic in probability space and non-linear in log-odds space. I think subsampling the chains/draws is better:

```python

# Select 1000 draws
n_samples = 1000
n_chains = 4
n_draws = 10000
rng = np.random.default_rng()
chain = rng.integers(0, n_chains, n_samples)
draw = rng.integers(0, n_draws, n_samples)

posterior_mean = clinton_fitted.posterior["vote_mean"].values[chain, draw, :]
```

This approach gives the updated plots in the previous post.

The example should probably use this method. I think it has the same artifacts, but they're less visible because of the narrower range.

**Comment by tomicapretto** [comment]
John, 

Thanks for opening the issue and the highly detailed comments and the notebook!

Some points:

1. You're right when you say taking the mean between chains is a bad idea. That's a mistake I'm going to fix ASAP. Thanks for reporting it :)
2. For the difference in the results, I still need to check the models on my side. I'll try to come back with a better response tomorrow when I can sit down in my computer.

Again, thanks for the detailed notebook!

**Comment by tomicapretto** [comment]
I've been working on this a little. Let's say we have the following models (they should all be the same model!)

```python
# Bambi model
bmb_model = bmb.Model('Dx ~ 0 + ' + ' + '.join(genes), cntr_patients_f, family="bernoulli")
bmb_idata = bmb_model.fit(draws=10000, chains=4, random_seed=SEED)

# PyMC Model 1 (the one you shared)
prior_mus = np.zeros(len(genes))
prior_sigmas = np.array([prior['sigma'] for prior in bmb_model.scaler.priors.values()])

coords = {'gene': genes, 'sample': cntr_patients_f.index}
with pm.Model(coords=coords) as pm_model_1:
    data = pm.Data('data', cntr_patients_f[genes].values, dims=('sample', 'gene'))
    slopes = pm.Normal('slopes', prior_mus, prior_sigmas, dims='gene')
    logit_p = pm.Deterministic("logit_p", pm.math.dot(data, slopes))
    p = pm.Deterministic('p', pm.math.invlogit(logit_p))
    _ = pm.Bernoulli('Dx', p=p, observed=cntr_patients_f.Dx.values)
    
    pm_idata_1 = pm.sample(draws=10000, chains=4, return_inferencedata=True, random_seed=SEED)

# PyMC Model 2
# Like the one you shared, but using X directly, without pm.Data, and only coords for coefficients
X = cntr_patients_f[genes].values
with pm.Model(coords=coords) as pm_model_2:
    slopes = pm.Normal('slopes', prior_mus, prior_sigmas, dims='gene')
    logit_p = pm.Deterministic("logit_p", pm.math.dot(X, slopes))
    p = pm.Deterministic('p', pm.math.invlogit(logit_p))
    _ = pm.Bernoulli('Dx', p=p, observed=cntr_patients_f.Dx.values)
    
    pm_idata_2 = pm.sample(draws=10000, chains=4, return_inferencedata=True, random_seed=SEED)

# PyMC Model 3
# Doing the same than what's being done in Bambi under the hood
with pm.Model() as pm_model_3:
    bA = pm.Normal("A", mu=0, sigma=prior_sigmas[0])[None]
    bB = pm.Normal("B", mu=0, sigma=prior_sigmas[1])[None]
    bC = pm.Normal("C", mu=0, sigma=prior_sigmas[2])[None]
    bD = pm.Normal("D", mu=0, sigma=prior_sigmas[3])[None]
    
    b = tt.concatenate([bA, bB, bC, bD])
    logit_p = pm.math.dot(X, b)
    p = pm.math.invlogit(logit_p)
    pm.Bernoulli("Dx", p=p, observed=cntr_patients_f.Dx.values)
    pm_idata_3 = pm.sample(draws=10000, chains=4, return_inferencedata=True, random_seed=SEED)

# PyMC Model 4
# Similar to model 3, but without using dot product
with pm.Model() as pm_model_4:
    bA = pm.Normal("A", mu=0, sigma=prior_sigmas[0])
    bB = pm.Normal("B", mu=0, sigma=prior_sigmas[1])
    bC = pm.Normal("C", mu=0, sigma=prior_sigmas[2])
    bD = pm.Normal("D", mu=0, sigma=prior_sigmas[3])
    
    logit_p = bA * X[:, 0] + bB * X[:, 1] + bC * X[:, 2] + bD * X[:, 3]
    p = pm.math.invlogit(logit_p)
    pm.Bernoulli("Dx", p=p, observed=cntr_patients_f.Dx.values)
    pm_idata_4 = pm.sample(draws=10000, chains=4, return_inferencedata=True, random_seed=SEED)
```

Let's see the summaries

```python
az.summary(bmb_idata)
```
![image](https://user-images.githubusercontent.com/25507629/141679738-e3fe7df2-06c0-40f5-9c2f-18596c02823c.png)


```python
az.summary(pm_idata_1, var_names=["slopes"])
```

![image](https://user-images.githubusercontent.com/25507629/141679744-b6275fab-e76e-44e5-bedb-03b044e8055e.png)


```python
az.summary(pm_idata_2, var_names=["A", "B", "C", "D"])
```

![image](https://user-images.githubusercontent.com/25507629/141679750-36021f1e-a693-428e-8a61-131ad66a2ce2.png)


```python
az.summary(pm_idata_3, var_names=["A", "B", "C", "D"])
```

![image](https://user-images.githubusercontent.com/25507629/141679757-65067245-f94c-461a-a00a-f5dd7762640d.png)


```python
az.summary(pm_idata_4, var_names=["A", "B", "C", "D"])
```

![image](https://user-images.githubusercontent.com/25507629/141679776-d371a7d4-285e-4286-995a-a16edeca9356.png)

We can see all the models match, except the one with PyMC that you shared. To be honest, I don't know what's going on. I think they should be the same, but there's definitely something going on that we are missing.

@aloctavodia maybe you are more familiar with PyMC internals or have seen this behavior before?

**Comment by JohnGoertz** [comment]
Thanks for taking such a thorough look at this!

But this is odd, our results don't agree. For me, models 1 (my original) and 2 (using dot product) match each other, and only the Bambi model and models 3 and 4 all match. I've updated the colab, and see below:

```python
bambi : 0.6.3
pymc3 : 3.11.4
arviz : 0.11.4
theano : 1.1.2
numpy : 1.19.5
```

```python
az.summary(bmb_idata)
```
![image](https://user-images.githubusercontent.com/9869969/141693491-0a8e41df-b8ba-4dbc-b5eb-e1880875e5da.png)


```python
az.summary(pm_idata_1, var_names=['slopes'])
```
![image](https://user-images.githubusercontent.com/9869969/141693500-0c0fc2de-91f2-4d78-a8b5-42e874ff8a66.png)

```python
az.summary(pm_idata_2, var_names=['slopes'])
```
![image](https://user-images.githubusercontent.com/9869969/141693514-ca547cbb-7288-4b3f-abb7-670543b63967.png)

```python
az.summary(pm_idata_3, var_names=["A", "B", "C", "D"])
```
![image](https://user-images.githubusercontent.com/9869969/141693534-a4f593a6-9d62-4fb0-a9bd-1fb3e941b83f.png)

```python
az.summary(pm_idata_4, var_names=["A", "B", "C", "D"])
```
![image](https://user-images.githubusercontent.com/9869969/141693603-bc638df0-1be7-4e0b-a4f6-42fa674d3e31.png)

**Comment by aloctavodia** [comment]
I am seeing the same as @JohnGoertz the models bambi, pm_model_3 and pm_model_4 agree with each other and then pm_idata_1 and pm_idata_2 agree with each other.

prior_sigma has dimension (4,1), but it should be (4,). Change that and you should get the same results for all versions.

You can use 

`np.concatenate([prior['sigma'] for prior in bmb_model.scaler.priors.values()])`

Instead of 

`np.array([prior['sigma'] for prior in bmb_model.scaler.priors.values()])`

**Comment by tomicapretto** [comment]
You're both right. I mixed things up, `pm_data_1` and `pm_idata_2` both agree. Also, I have fixed the shape of `prior_sigma` (i.e. using `(4,)` instead of `(4, 1)`) and all the results match now.

@JohnGoertz could you confirm if this fixes the issue on your side?

Thanks!!

**Comment by JohnGoertz** [comment]
That does fix it! Why was that an issue, though? The values of the dot product are the same, just the shape is different. How does that lead to such different results?

```python
concat = np.concatenate([prior['sigma'] for prior in bmb_model.scaler.priors.values()])
arr = np.array([prior['sigma'] for prior in bmb_model.scaler.priors.values()])
print(np.dot(X, concat).sum())  # 7.105427357601002e-15
print(np.dot(X, arr).sum())  # 7.105427357601002e-15
print(np.dot(X, concat).shape)  # (38,)
print(np.dot(X, arr).shape)  # (38, 1)
```

Thanks very much for your help, everyone.

**Comment by tomicapretto** [comment]
Glad this is fixed!

This is an issue in PyMC. I don't know if it is solved in v4. Tagging @ricardoV94 who may be aware of that.
