### ISSUE TITLE
Unintuitive: order matters in specifying mixed effects?

### ISSUE THREAD

**Issue by No-Stream** [bambinos/bambi#431]
Hi - I've recently been using bambi `0.6.3` with pymc3 `3.11.2` and python 3.8. I spent a while struggling to specify mixed effects - interactions like I'd do in patsy (`*` or `:`) worked fine, but `|` gave me a slope+intercept per observation and OOMed on real data. After a fair bit of unsuccessful effort - I thought bambi thought my continuous variable was a category or that my category was continuous - realized I need to do `feature|group`, not `group|feature`. It's very possible this is standard practice in other bayesian linear model packages, but I find this very unintuitive and suspect others might feel similarly? In case this is a bug, here's code to reproduce on a toy dataset:

```
# debug on toy data
from sklearn.datasets import make_regression


xs, ys = make_regression(
    n_samples=500,
    n_features=5,
    n_informative=5,
    n_targets=1,
    bias=0.0,
    effective_rank=None,
    tail_strength=0.5,
    noise=5e1,
    shuffle=True,
    coef=False,
    random_state=42,
)

feat_names = {i: f"f{i}" for i in range(5)}
xys = pd.concat(
    [pd.DataFrame(xs).rename(columns=feat_names), pd.Series(ys).rename("y")], axis=1
)
# add hierarchy
xys["group_i"] = xys.index // 50
xys["group"] = "g_" + xys.group_i.astype("str")

# add group intercept
xys["y"] = xys.y + 30 * xys.group_i
# add group slope
xys["y"] = xys.y + 1e1 * xys.f0 * xys.group_i

# scale y to unit normal
xys["y"] = (xys.y - xys.y.mean()) / xys.y.std()

# expected behavior: mixed effects
debug_model = bmb.Model(
    "y ~ f0 + f1 + f2 + f3 + f4 + (f0|group_i)",
    data=xys,
)
debug_model
debug_model.build()
debug_model.graph()

# unintuitive behavior: one group per observation!
debug_model = bmb.Model(
    "y ~ f0 + f1 + f2 + f3 + f4 + (group_i|f0)",
    data=xys,
)
debug_model
debug_model.build()
debug_model.graph()
```
expected:
![image](https://user-images.githubusercontent.com/15351234/143728675-6f601554-2f0a-4da0-ad95-80533c765f11.png)

unexpected:
![image](https://user-images.githubusercontent.com/15351234/143728688-e737f932-4d65-447a-b138-b2d22dd290f7.png)

Appreciate your help and am a fan of the package :) rapid progress since I last used it this ~spring. Looking forward to splines!

**Comment by zwelitunyiswa** [comment]
@No-Stream  Bambi already has splines:

https://bambinos.github.io/bambi/main/notebooks/splines_cherry_blossoms.html

**Comment by tomicapretto** [comment]
Hi @No-Stream,

Thanks for opening the issue and the nice words about the package!

Indeed, it is intended behavior. The syntax for a group-specific effect (aka random effect) is `(variable|group)` and operators are not exchangeable as with the other interactions `:` and `*`. This is because the LHS is for the term and the RHS is for the grouping variable.

This is not something we have invented in Bambi, it comes from the `lme4` library in R. There's the [Fitting Linear Mixed-Effects Models Using lme4](https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf) vignette with more information about formulas for mixed-effects models. See Section 2 for more information.


**NB** I think the use of the `|` symbol for random effects was coined for the `nlme` library, but it was `lme4` who made it very popular.

**Comment by No-Stream** [comment]
@zwelitunyiswa thank you!

@tomicapretto makes sense in retrospect. However, I would flag that it's not super clear to someone who doesn't use the comparable R packages / hasn't read their documentation. I dug through all of the Bambi intro documentation and the Formulae intro documentation and didn't find an explicit reference, other than the order used in the examples. (Not saying I didn't miss it!) It could be helpful to explicitly mention this in the mixed effects section of the Bambi docs, since I believe Bambi is meant to be accessible to those familiar with e.g. Patsy? Perhaps even more helpful would be to throw a warning if someone tries to fit a group per observation, since this would rarely be intended?

**Comment by tomicapretto** [comment]
Maybe this can help? https://bambinos.github.io/formulae/notebooks/getting_started.html#Group-specific-effects

**Comment by No-Stream** [comment]
Yes, that would help - just trying to make it so the next person doesn't end up very confused why they have one group per observation. Feel free to close.
