### ISSUE TITLE
Upgrade backend to PYMC v4.0.0

### ISSUE THREAD

**Issue by nikisix** [bambinos/bambi#433]
Upgraded PYMC to v4.0.0 with the Aesara backend. This is now at odds with the PYMC v3 that bambi requires:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your Python environment has Theano(-PyMC) 1.1.2 installed, but you are importing PyMC 4.0.0b1 which uses Aesara as its backend.
For PyMC 4.0.0b1 to work as expected you should uninstall Theano(-PyMC).
See https://github.com/pymc-devs/pymc/wiki for update instructions.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
You are importing PyMC 4.0.0b1, but your environment also has the legacy version PyMC3 3.11.4 installed.
For PyMC 4.0.0b1 to work as expected you should uninstall PyMC3.
See https://github.com/pymc-devs/pymc/wiki for update instructions.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by tomicapretto** [comment]
@nikisix if you use both Bambi and PyMC and want to use PyMC v4, I would recommend having them in different environments. The released version of PyMC v4 is a beta release. I think we're going to move to PyMC v4 once it launches a stable release.

**Comment by nikisix** [comment]
Makes sense.

**Comment by tomicapretto** [comment]
I just wanted to add a comment. I've installed PyMC 3.11.4 and that broke my Bambi installation. I've downgraded to version 3.11.0 and now it works well. I don't know if that's only my case.

**Comment by nikisix** [comment]
That's strange b/c I've been running Bambi on 3.11.4 just fine.

```
bambi                     0.6.3                    pypi_0    pypi
formulae                  0.2.0                    pypi_0    pypi
numpy                     1.19.5           py37h038b26d_2    conda-forge
pandas                    1.3.4            py37he8f5f7f_1    conda-forge
pandas-profiling          3.1.0              pyhd8ed1ab_0    conda-forge
pymc3                     3.11.4                   pypi_0    pypi
scipy                     1.7.3            py37hf2a6cf1_0    conda-forge
statsmodels               0.13.1           py37hb1e94ed_0    conda-forge
theano-pymc               1.1.2                    pypi_0    pypi
```

I did discover today that trying to pump a modin.pandas dataframe through bambi-model-data doesn't work :)

**Comment by tomicapretto** [comment]
I don't know what's going on. I'll keep investigating. 

When did you installed PyMC3? Maybe a problem with Theano-PyMC version? I'm not sure

**Comment by tomicapretto** [comment]
It was a problem with the new release of NumPy (1.22.0). I updated `requirements.txt` to force NumPy < 1.22.0
