### ISSUE TITLE
Port PyMC Radon example

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#439]
[A Primer on Bayesian Methods for Multilevel Modeling](https://docs.pymc.io/projects/examples/en/latest/case_studies/multilevel_modeling.html) is a very popular example in PyMC. 

We could port this example to show how easy is to create those types of hierarchical models using Bambi.

**Comment by juanitorduz** [comment]
Hey! I could work on this. However, the PyMC example is quite long ... shall we mainly focus in explaining how the hierarchical models can be written in `bambi` (which is a good learning for me)? We do not wanna duplicate the material right?

**Comment by juanitorduz** [comment]
I started with a draft PR: https://github.com/bambinos/bambi/pull/440 Can someone take a look into the models specification please? Thanks 😄 !

**Comment by juanitorduz** [comment]
@tomicapretto @aloctavodia Thank you guys for your support! Many learnings and interesting discussions!

**Comment by tomicapretto** [comment]
@juanitorduz  It's been a very interesting experience for me too! Thanks a lot!
