### ISSUE TITLE
Array dimension mismatch error when using `predict` method with out of sample data.

### ISSUE THREAD

**Issue by LeonieMei** [bambinos/bambi#447]
Hi all, 

I was trying to make out-of-sample predictions for a mixed-effects logistic regression model yesterday and ran into a problem. The formula for building the model is:

`'y ~ x1 + (0 + x2|x1) + (0 + x3|x1 + x2)'`

with x1 having 4 levels, x2 having 2 levels and x3 being a continuous variable.

When calling `model.predict(iData, newData)` I got the following error:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/85/y3q1qszx6f14lygqxqvz4kp40000gn/T/ipykernel_18651/2078896284.py in <module>
----> 1 bmbModel.predict(iData, data=newData)

~/miniconda3/envs/project/lib/python3.8/site-packages/bambi/models.py in predict(self, idata, kind, data, draws, inplace)
    802             linear_predictor += np.dot(X, beta_x)
    803         if Z is not None:
--> 804             beta_z = np.vstack(
    805                 [np.atleast_2d(posterior[name]) for name in self.group_specific_terms]
    806             )

<__array_function__ internals> in vstack(*args, **kwargs)

~/miniconda3/envs/project/lib/python3.8/site-packages/numpy/core/shape_base.py in vstack(tup)
    280     if not isinstance(arrs, list):
    281         arrs = [arrs]
--> 282     return _nx.concatenate(arrs, 0)
    283 
    284 

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)
```

I got it to work using the following code (in place of the one in lines 804 - 807 in `models.py`):

```python
beta_z = np.vstack(
                [np.atleast_3d(posterior[name].T).T for name in self.group_specific_terms]
            )
linear_predictor += np.dot(Z, beta_z.reshape(Z.shape[-1], beta_z.shape[-1]))
```

which is quite hacky and just a result of trying until it worked. Maybe someone can fix this in a more elegant and generalizable way. Also, thanks for the great work, it really makes life much easier!

**Comment by tomicapretto** [comment]
Hi @LeonieMei

Thanks for opening the issue and also providing a fix. I'll try to fix it soon.

I'll put any updates here.

**Comment by tomicapretto** [comment]
@LeonieMei could you install from the PR #451 and let me know if it works with your use case?
Otherwise, could you provide a reproducible example please?

**Comment by LeonieMei** [comment]
Yes, it worked! Thanks a lot!
