### ISSUE TITLE
Modelling the variance in linear regression (heteroscedasiticy)

### ISSUE THREAD

**Issue by mohelm** [bambinos/bambi#449]
Hi, 

first many thanks for the fantastic project. It makes it really easy to start with Baysian inference!

I have a quick question: is it possible to provide a model for the variance parameter in linear regression? In other words, can you estimate models that allow for heteroscedasticity?

**Comment by tomicapretto** [comment]
Hi @mohelm 

It's not possible at the moment, but it is something I would like to add. There are a couple of issues more urgent than this one, so this is not happening very soon. But I also expect this not to take too long. I'll post any updates here.

**Comment by mohelm** [comment]
Hey Tomás, thanks for the quick reply. Great to hear that you are interested in this.

So, currently, this would have to be done in pymc3 (for instance) directly, right? Is there a chance you have a reference for this - I only found [this](https://medium.com/@arose13/bayesian-methods-for-heteroscedasticity-6ead8336735b) so far.

**Comment by aloctavodia** [comment]
In Section 4.2 of https://bayesiancomputationbook.com/markdown/chp_04.html you will find another example.

**Comment by mohelm** [comment]
fantastic, thank you both.
