### ISSUE TITLE
ESCS_multiple_regression fails

### ISSUE THREAD

**Issue by palday** [bambinos/bambi#45]
The stack trace is as follows:
```
>>> fitted = model.fit('drugs ~ o + c + e + a + n', samples=2000, njobs=2)
$HOME/Code/bambi/bambi/models.py:227: UserWarning: Current Bayesian model has not been built yet; building it first before sampling begins.
  warnings.warn("Current Bayesian model has not been built yet; "


TypeError                                 Traceback (most recent call last)
<ipython-input-5-02e82ee54338> in <module>()
      1 model = bmb.Model(data)
----> 2 fitted = model.fit('drugs ~ o + c + e + a + n', samples=2000, njobs=2)

$HOME/Code/bambi/bambi/models.pyc in fit(self, fixed, random, priors, family, link, run, categorical, **kwargs)
    227                 warnings.warn("Current Bayesian model has not been built yet; "
    228                               "building it first before sampling begins.")
--> 229                 self.build()
    230             return self.backend.run(**kwargs)
    231 

$HOME/Code/bambi/bambi/models.pyc in build(self)
    181                 self.y.name, str(self.data[self.y.name][event])))
    182 
--> 183         self.backend.build(self)
    184         self.built = True
    185 

$HOME/Code/bambi/bambi/backends.pyc in build(self, spec, reset)
    119             y_prior.args['observed'] = y
    120             y_like = self._build_dist(
--> 121                 spec.y.name, y_prior.name, **y_prior.args)
    122 
    123             self.spec = spec

$HOME/Code/bambi/bambi/backends.pyc in _build_dist(self, label, dist, **kwargs)
     70             return v
     71 
---> 72         kwargs = {k: _expand_args(k, v, label) for (k, v) in kwargs.items()}
     73         return dist(label, **kwargs)
     74 

$HOME/Code/bambi/bambi/backends.pyc in <dictcomp>((k, v))
     70             return v
     71 
---> 72         kwargs = {k: _expand_args(k, v, label) for (k, v) in kwargs.items()}
     73         return dist(label, **kwargs)
     74 

$HOME/Code/bambi/bambi/backends.pyc in _expand_args(k, v, label)
     67             if isinstance(v, Prior):
     68                 label = '%s_%s' % (label, k)
---> 69                 return self._build_dist(label, v.name, **v.args)
     70             return v
     71 

$HOME/Code/bambi/bambi/backends.pyc in _build_dist(self, label, dist, **kwargs)
     71 
     72         kwargs = {k: _expand_args(k, v, label) for (k, v) in kwargs.items()}
---> 73         return dist(label, **kwargs)
     74 
     75     def build(self, spec, reset=True):

/usr/local/lib/python2.7/site-packages/pymc3/distributions/distribution.pyc in __new__(cls, name, *args, **kwargs)
     27             return object.__new__(cls)  # for pickle
     28         else:
---> 29             raise TypeError("needed name or None but got: " + name)
     30 
     31     def __getnewargs__(self):
```
I got the same error for a linear mixed model. The logistic regression example still works.

**Comment by jake-westfall** [comment]
Huh. Seems to have a problem with setting up the prior on the residual SD... but it's not immediately clear where the problem comes from. It didnt print the output from the TypeError at the end (i.e., printing the value of the `name` variable inside pymc3)?

**Comment by palday** [comment]
I already closed the instance in question, but for another instance, the value of `name` was `var_sd` for a `var` in the model. For the mixed model, it was the subject-wise intercepts, but when I dropped that term, the error still occurred but for the dependent variable. I'm guessing it's the sd term for whatever variable happens to get parsed first?

**Comment by jake-westfall** [comment]
As best I can tell, this seems to happen because `isinstance(name, string_types)` in [pymc3/distributions/distribution.py](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/distribution.py) is evaluating to `False`, where `string_types` is imported from [pymc3/vartypes.py](https://github.com/pymc-devs/pymc3/blob/master/pymc3/vartypes.py) and is defined thusly:

    if sys.version_info[0] == 3:
        string_types = str
    else:
        string_types = basestring

I'm guessing you're on python 2? It's possible that the comparison with basestring is somehow interacting badly with the fact that the `var_sd` variable names are created using the % string formatting syntax, i.e., `varname = '%s_%s' % (label, param)`. I don't think any of the other variable names are constructed using this syntax.

Phillip, if you're on python 2, what result do you get from running `isinstance('%s_%s' % ('var', 'sd'), basestring)`?

**Comment by palday** [comment]
I tried this on Python 2.7.12:

```python
In [1]: isinstance('%s_%s' % ('var', 'sd'), basestring)
Out[1]: True
```

I'm getting my Python 3 environment up-to-date and then I'll try the example there.

**Comment by palday** [comment]
So on an up-to-date Python 3 environment, there was no error. I then updated my PyMC3 install on Python 2 and the error has also gone away. So it appears to have been an interaction effect between a slightly outdated PyMC3 install and the current master of bambi (the problem didn't occur on the pip version).

As such, we can consider the issue resolved.
