### ISSUE TITLE
predict method for Categorical family throws errors for pps (posterior_predictive not implemented)

### ISSUE THREAD

**Issue by tjburch** [bambinos/bambi#456]
I was working to try to create a categorical example for #436, but ran into some problems with the predict method. It seems to only return `NoneType`

MWE, using the csv from the testing suite:

```
import bambi as bmb
import pandas as pd
inhaler = pd.read_csv("bambi/tests/data/inhaler.csv")
inhaler["rating"] = pd.Categorical(inhaler["rating"], categories=[1,2,3,4])
model = bmb.Model("rating ~ period", data=inhaler, family="categorical")
idata = model.fit()
type(model.predict(idata))
```
Returns a `NoneType`. This is quiet, so I assume that's why the tests didn't pick it up.

If you instead try to get the posterior predictive:
```
model.predict(idata, kind="pps")
```

It throws a louder error
```
AttributeError                            Traceback (most recent call last)
/Users/tburch/Documents/github/bambi/categorical_test.ipynb Cell 6' in <module>
----> [1]()[ model.predict(idata, kind="pps")

File ~/Documents/github/bambi/bambi/models.py:919, in Model.predict(self, idata, kind, data, draws, inplace)
    ]()[916]()[ if not in_sample and isinstance(self.family, univariate.Binomial):
    ]()[917]()[     pps_kwargs["trials"] = self._design.response._evaluate_new_data(data)
--> ]()[919]()[ pps = self.family.posterior_predictive(**pps_kwargs)
    ]()[921]()[ if "posterior_predictive" in idata:
    ]()[922]()[     del idata.posterior_predictive

AttributeError: 'Categorical' object has no attribute 'posterior_predictive']()
```

**Comment by tjburch** [comment]
Apologies. I forgot that the predict method adds to the InferenceData object so the first half of this is moot, disregard - sorry about that noise.

However, the second part, missing the `posterior_predictive` method is actually probably a concern? I don't see it mentioned in the original merge #426.

**Comment by tomicapretto** [comment]
@tjburch thanks for opening this issue!

At the moment I completely forgot to add this method. Or maybe it was too complicated and I was too lazy haha.
Now we have #458 where this method is added :)
