### ISSUE TITLE
TypeError: can't pickle fortran objects

### ISSUE THREAD

**Issue by cgacian** [bambinos/bambi#459]
I'm working on a laptop with Windows 10 and using Anaconda 64-bit. I have created an environment for working with Pymc3 and bambi,using "conda install -c conda-forge bambi"[https://bambinos.github.io/bambi/main/index.html].
for **bambi**,i was tesing "Comparison of two means (T-test)" at this link[https://bambinos.github.io/bambi/main/notebooks/t-test.html],I run into an error I had not seen with bambi before(TypeError: can't pickle fortran objects),but I could run "Multiple linear regression"[https://bambinos.github.io/bambi/main/notebooks/ESCS_multiple_regression.html]  with success.

# packages in environment
WARNING: Ignoring invalid distribution -ywinpty (f:\anaconda3\envs\pym3\lib\site-packages)
Package              Version
-------------------- ---------
anyio                3.5.0
argcomplete          1.12.3
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
arviz                0.11.4
attrs                21.4.0
Babel                2.9.1
backcall             0.2.0
bambi                0.7.1
bleach               4.1.0
brotlipy             0.7.0
cachetools           5.0.0
certifi              2021.10.8
cffi                 1.15.0
cftime               1.5.2
charset-normalizer   2.0.4
colorama             0.4.4
cryptography         36.0.0
cycler               0.11.0
debugpy              1.5.1
decorator            5.1.1
defusedxml           0.7.1
dill                 0.3.4
entrypoints          0.3
fastprogress         1.0.2
filelock             3.6.0
fonttools            4.29.1
formulae             0.2.0
idna                 3.3
importlib-metadata   4.11.1
ipykernel            6.4.1
ipython              7.31.1
ipython-genutils     0.2.0
jedi                 0.18.1
Jinja2               3.0.2
json5                0.9.6
jsonschema           3.2.0
jupyter-client       7.1.2
jupyter-core         4.9.1
jupyter-server       1.13.5
jupyterlab           3.2.9
jupyterlab-pygments  0.1.2
jupyterlab-server    2.10.3
kiwisolver           1.3.2
Mako                 1.1.6
MarkupSafe           2.1.0
matplotlib           3.5.1
matplotlib-inline    0.1.2
mistune              0.8.4
munkres              1.1.4
nbclassic            0.3.5
nbclient             0.5.11
nbconvert            6.1.0
nbformat             5.1.3
nest-asyncio         1.5.1
netCDF4              1.5.8
notebook             6.4.8
numpy                1.21.5
packaging            21.3
pandas               1.3.4
pandocfilters        1.5.0
parso                0.8.3
patsy                0.5.2
pickleshare          0.7.5
Pillow               9.0.1
pip                  21.2.4
prometheus-client    0.13.1
prompt-toolkit       3.0.20
pycparser            2.21
Pygments             2.11.2
pygpu                0.7.6
pymc3                3.11.4
pyOpenSSL            22.0.0
pyparsing            3.0.7
pyrsistent           0.18.0
PySocks              1.7.1
python-dateutil      2.8.2
pytz                 2021.3
pywin32              302
pywinpty             1.1.6
pyzmq                22.3.0
requests             2.27.1
scipy                1.7.3
semver               2.13.0
Send2Trash           1.8.0
setuptools           58.0.4
six                  1.16.0
sniffio              1.2.0
statsmodels          0.13.2
terminado            0.13.1
testpath             0.5.0
Theano-PyMC          1.1.2
tornado              6.1
traitlets            5.1.1
typing-extensions    3.10.0.2
unicodedata2         14.0.0
urllib3              1.26.8
wcwidth              0.2.5
webencodings         0.5.1
websocket-client     0.58.0
wheel                0.37.1
win-inet-pton        1.1.0
wincertstore         0.2
xarray               0.20.2
zipp                 3.7.0
WARNING: Ignoring invalid distribution -ywinpty (f:\anaconda3\envs\pym3\lib\site-packages)
WARNING: Ignoring invalid distribution -ywinpty (f:\anaconda3\envs\pym3\lib\site-packages)
WARNING: Ignoring invalid distribution -ywinpty (f:\anaconda3\envs\pym3\lib\site-packages)

Model I tried to run is:
            model_1 = bmb.Model("Val ~ Group", df)
            results_1 = model_1.fit()

And the error I get is:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
\Local\Temp/ipykernel_28908/4005395149.py in <module>
      1 model_1 = bmb.Model("Val ~ Group", df)
----> 2 results_1 = model_1.fit()

F:\Anaconda3\envs\PYM3\lib\site-packages\bambi\models.py in fit(self, draws, tune, discard_tuned_samples, omit_offsets, include_mean, method, init, n_init, chains, cores, random_seed, **kwargs)
    288             cores=cores,
    289             random_seed=random_seed,
--> 290             **kwargs,
    291         )
    292 

F:\Anaconda3\envs\PYM3\lib\site-packages\bambi\backend\pymc.py in run(self, draws, tune, discard_tuned_samples, omit_offsets, include_mean, method, init, n_init, chains, cores, random_seed, **kwargs)
     99                 cores,
    100                 random_seed,
--> 101                 **kwargs,
    102             )
    103         elif method.lower() == "advi":

F:\Anaconda3\envs\PYM3\lib\site-packages\bambi\backend\pymc.py in _run_mcmc(self, draws, tune, discard_tuned_samples, omit_offsets, include_mean, init, n_init, chains, cores, random_seed, **kwargs)
    225                     random_seed=random_seed,
    226                     return_inferencedata=True,
--> 227                     **kwargs,
    228                 )
    229             except (RuntimeError, ValueError):

F:\Anaconda3\envs\PYM3\lib\site-packages\pymc3\sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, callback, jitter_max_retries, return_inferencedata, idata_kwargs, mp_ctx, pickle_backend, **kwargs)
    557         _print_step_hierarchy(step)
    558         try:
--> 559             trace = _mp_sample(**sample_args, **parallel_args)
    560         except pickle.PickleError:
    561             _log.warning("Could not pickle model, sampling singlethreaded.")

F:\Anaconda3\envs\PYM3\lib\site-packages\pymc3\sampling.py in _mp_sample(draws, tune, step, chains, cores, chain, random_seed, start, progressbar, trace, model, callback, discard_tuned_samples, mp_ctx, pickle_backend, **kwargs)
   1470         progressbar,
   1471         mp_ctx=mp_ctx,
-> 1472         pickle_backend=pickle_backend,
   1473     )
   1474     try:

F:\Anaconda3\envs\PYM3\lib\site-packages\pymc3\parallel_sampling.py in __init__(self, draws, tune, chains, cores, seeds, start_points, step_method, start_chain_num, progressbar, mp_ctx, pickle_backend)
    421         if mp_ctx.get_start_method() != "fork":
    422             if pickle_backend == "pickle":
--> 423                 step_method_pickled = pickle.dumps(step_method, protocol=-1)
    424             elif pickle_backend == "dill":
    425                 try:

TypeError: can't pickle fortran objects

Can anyone  help?
cgacian

**Comment by tomicapretto** [comment]
Hi @cgacian 

I have never experienced that problem. I think it is related to Windows. It has been reported on PyMC discourse too.
Maybe some of the following links help

https://discourse.pymc.io/t/an-error-message-about-cant-pickle-fortran-objects/1073
https://discourse.pymc.io/t/can-not-pickle-fortran-object/6575

**Comment by cgacian** [comment]
Hi @[tomicapretto]

The links' post is very useful.
 Althought I don't why, when I try cores=1, it works.
Thanks a lot for your help.

**Comment by aloctavodia** [comment]
Closing as the issue needs to be solved upstream
