### ISSUE TITLE
Formulae contrast support

### ISSUE THREAD

**Issue by MartinGrignard** [bambinos/bambi#466]
Hi :wave:

I've been working a lot with `bambi` lately and it proved to be a very nice tool. Thanks for that! :slightly_smiling_face:
I'm currently trying to work with different contrasts than the default dummy one.

Apparently, `formulae` [now supports a variety of other contrasts](https://github.com/bambinos/formulae/pull/61) but they are currently not supported in `bambi`.

By the look of things, it seems like it was originally not in the roadmap to add them (#29). Is this still the case?
If so, what is the recommended way to implement other contrasts such as deviation (sum) in `bambi`?

Thanks,
Martin

**Comment by tomicapretto** [comment]
Hi Martin!

I'm glad Bambi is helping you! 

You're right `formulae` now supports a variety of contrasts (or different encodings for categorical variables). 

I was not aware of #29 to be honest. My idea is to update Bambi to use the last updates in formulae, but I didn't have time to work on it yet.

In the meantime, can't recommend a way to implement other contrasts in Bambi (I need to think about it). 

If it's not urgent, it would be better to wait until Bambi uses the new version of formulae and those alternative encodings are going to be built-in. I expect it not to take too long.

**Comment by tomicapretto** [comment]
@MartinGrignard you could also try to use formulae to construct the design matrix and then extract the terms manually and build the PyMC model by hand. Which type of model are you building? Maybe it's much simpler to write some PyMC code instead of fixing Bambi.
