### ISSUE TITLE
improve FAQ

### ISSUE THREAD

**Issue by aloctavodia** [bambinos/bambi#473]
We need to improve https://bambinos.github.io/bambi/main/faq.html. This may be a good opportunity to ask for help on Twitter.

**Comment by tomicapretto** [comment]
@sreedat from our discussion on #389 it seems you were interested in writing something to the FAQ. Do you still want to do it? 

Otherwise, I think we're going to take this issue.

**Comment by tomicapretto** [comment]
closing in favor of #644
