### ISSUE TITLE
Call to missing pymc3 attribute (dot)

### ISSUE THREAD

**Issue by egorananyev** [bambinos/bambi#48]
Thank you for the wonderful package. I'm running into the following issue though: model.fit() complains that there is a missing attribute in pymc3 (dot):

```
data = pd.DataFrame({ 'one' : pd.Series([5, 4, 3, 1]), 'two' : pd.Series([1, 2, 3, 4]) })
model = bambi.Model(data)
modelFitted = model.fit('one ~ two', samples=2000, njobs=2)
modelFitted.plot(burn_in=50)
```

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-4-32207fab1e9b> in <module>()
>       1 model = bambi.Model(df)
> ----> 2 modelFitted = model.fit('st ~ congr:fam:cued', samples=2000, njobs=2)
>       3 modelFitted.plot(burn_in=50)
> 
> /Library/Python/2.7/site-packages/bambi/models.pyc in fit(self, fixed, random, priors, family, link, run, categorical, **kwargs)
>     218                 warnings.warn("Current Bayesian model has not been built yet; "
>     219                               "building it first before sampling begins.")
> --> 220                 self.build()
>     221             return self.backend.run(**kwargs)
>     222 
> 
> /Library/Python/2.7/site-packages/bambi/models.pyc in build(self)
>     172                     scaler.scale(t)
>     173 
> --> 174         self.backend.build(self)
>     175         self.built = True
>     176 
> 
> /Library/Python/2.7/site-packages/bambi/backends.pyc in build(self, spec, reset)
>     109                     coef = self._build_dist(prefix + label, dist_name,
>     110                                             shape=n_cols, **dist_args)
> --> 111                     self.mu += pm.dot(data, coef)[:, None]
>     112 
>     113             y = spec.y.data
> 
> AttributeError: 'module' object has no attribute 'dot'

All the dependencies for pymc3 seem to be satisfied (I went through pymc3's requirements.txt to make sure), yet:

```
print dir(pymc3)
```

> ['AR1', 'ArrayOrdering', 'Bernoulli', 'Beta', 'BetaBinomial', 'BinaryGibbsMetropolis', 'BinaryMetropolis', 'Binomial', 'Bound', 'CallableTensor', 'Categorical', 'Cauchy', 'CauchyProposal', 'ChiSquared', 'CompoundStep', 'Constant', 'ConstantDist', 'Continuous', 'DensityDist', 'Deterministic', 'DictToArrayBijection', 'DictToVarBijection', 'Dirichlet', 'Discrete', 'DiscreteUniform', 'Distribution', 'ElemwiseCategorical', 'ExGaussian', 'Exponential', 'Factor', 'Flat', 'GARCH11', 'Gamma', 'GaussianRandomWalk', 'Geometric', 'HalfCauchy', 'HalfNormal', 'HalfStudentT', 'HamiltonianMC', 'InverseGamma', 'LKJCorr', 'Laplace', 'LaplaceProposal', 'Lognormal', 'Metropolis', 'Model', 'Multinomial', 'MultivariateNormalProposal', 'MvNormal', 'MvStudentT', 'NUTS', 'NegativeBinomial', 'NoDistribution', 'Normal', 'NormalProposal', 'Pareto', 'Point', 'Poisson', 'PoissonProposal', 'Potential', 'SkewNormal', 'Slice', 'StudentT', 'StudentTpos', 'TensorType', 'Uniform', 'VonMises', 'Wald', 'Weibull', 'Wishart', 'WishartBartlett', 'ZeroInflatedNegativeBinomial', 'ZeroInflatedPoisson', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', '_log', 'advi', 'advi_minibatch', 'approx_hessian', 'arraystep', 'autocorr', 'autocorrplot', 'autocov', 'backends', 'blocking', 'bool_types', 'bpic', 'compilef', 'complex_types', 'compound', 'cont_inputs', 'continuous_types', 'data', 'debug', 'default_type', 'df_summary', 'diagnostics', 'dic', 'discrete_types', 'distributions', 'effective_n', 'eval_univariate', 'fastfn', 'find_MAP', 'find_hessian', 'float_types', 'fn', 'forestplot', 'gelman_rubin', 'get_data_file', 'geweke', 'gibbs', 'glm', 'gradient', 'guess_scaling', 'handler', 'hessian', 'hessian_diag', 'hmc', 'hpd', 'inputvars', 'int_types', 'invlogit', 'iter_sample', 'jacobian', 'join_nonshared_inputs', 'kde2plot', 'kdeplot', 'logging', 'logit', 'logsumexp', 'loo', 'make_shared_replacements', 'math', 'mc_error', 'memoize', 'metropolis', 'model', 'modelcontext', 'np', 'nuts', 'plot_posterior', 'plots', 'quadpotential', 'quantiles', 'sample', 'sample_ppc', 'sample_vp', 'sampling', 'scaling', 'slicer', 'starting', 'stats', 'step_methods', 'summary', 'test', 'tests', 'theanof', 'trace_cov', 'trace_to_dataframe', 'traceplot', 'tuning', 'typefilter', 'variational', 'vartypes', 'waic']

Thanks in advance for your help. My platform is Mac OS 10.10.5, Python 2.7.

**Comment by tyarkoni** [comment]
Looks like the PyMC3 folks just [removed most of the theano tensor operations](https://github.com/pymc-devs/pymc3/commit/f2e08d5da70c465d3ca348e2eeeefb10a7a0fdbe#diff-8e614fd39fe61f50bce18a89c7db527d) from the namespace. We'll need to update the package to import `.dot` and other ops from `theano.tensor` directly instead of relying on the `pm` namespace. I'll try to get to this ASAP (probably tomorrow); if you need it to work before that, you can install an older release of PyMC3 (anything just prior to RC2 should work). Thanks!

**Comment by twiecki** [comment]
Yes, we encourage you to use `pm.math`.

**Comment by jake-westfall** [comment]
I'll do this today.

**Comment by jake-westfall** [comment]
Ready for merging as soon as @tyarkoni takes a quick look.
