### ISSUE TITLE
Hierarchical Partial Pooling Multinomial Model Error

### ISSUE THREAD

**Issue by zwelitunyiswa** [bambinos/bambi#491]
@tomicapretto  

I get an error when I try to fit a partial pooling model ("Input dimension mis-match"). Am I doing something wrong (i.e. this is not possible with multinomial regression) or is it an error in the software? I have attached a screenshot and test data (in feather format, which pandas should be able to read).

I have attached a screenshot and test data.

![Screen Shot 2022-04-22 at 10 16 44 AM](https://user-images.githubusercontent.com/32966743/164736993-3591b88e-a254-49ee-906d-c58c5929daa0.png)

[test_data.feather.zip](https://github.com/bambinos/bambi/files/8541847/test_data.feather.zip)

**Comment by tomicapretto** [comment]
Have a look at #492. I tested the model you shared with your data. First I would do

```python
data_2 = data.groupby("state", as_index=False).sum()
```

and then I would compare 

```python
bmb_model_2 = bmb.Model("c(fu_1, fu_2, fu_3, fu_4) ~ 0 + state", data_2, family="multinomial")
idata_2 = bmb_model_2.fit()
bmb_model_2.predict(idata_2)
az.plot_trace(idata_2);
```

![image](https://user-images.githubusercontent.com/25507629/164878941-d0cecc46-d8ed-4ddf-85fe-ea8adcff8e4f.png)


with 

```python
bmb_model_2 = bmb.Model("c(fu_1, fu_2, fu_3, fu_4) ~ 1 + (1|state)", data_2, family="multinomial", noncentered=False)
idata_2 = bmb_model_2.fit()
bmb_model_2.predict(idata_2)
az.plot_trace(idata_2);
```

![image](https://user-images.githubusercontent.com/25507629/164878963-40a61a01-447c-412b-b820-fae0deb14d16.png)


Notice this

```python
data_2[["fu_1", "fu_2", "fu_3", "fu_4"]].sum(axis=1)
```

```python

0    453274
1     65528
2     50838
dtype: int64
```

why are you looking at a partial pooling effect here?

**Comment by tomicapretto** [comment]
Nevermind about the comments and plots above. I found a mistake in the implementation, I'm trying to fix it.
