### ISSUE TITLE
Shape broadcast error (in PyMC) for model with

### ISSUE THREAD

**Issue by alexjonesphd** [bambinos/bambi#495]
Hello all,

Thanks again for this awesome package! I am having some trouble getting Bambi to build a model with a fairly complex set of terms (a spline term interaction with a categorical predictor, plus a three-way interaction between the same categorical predictor and two continuous, plus a group-specific effect). However the problem does not seem caused by Bambi but in PyMC - `formulae` will build the design matrices (but not convert to a pandas DataFrame) but PyMC throws a `ValueError` when trying to broadcast operands together. I will head to the PyMC repo if needed, but thought I would ask here first!

Here is a minrepex that mimics the data structure and the exact specification I am using, giving the same error, though the actual dataset is much bigger:

```
test_data = {'session': np.repeat([f'pid_{x}' for x in np.arange(0, 10)], 6),  
'state': np.tile(['lonely', 'depressed', 'hopeful', 'stressed', 'positive', 'isolated'], 10),
'level': np.repeat(np.random.normal(0, 1, size=5), 12),
'trait': np.repeat(np.random.normal(0, 1, size=10), 6),
'time': np.repeat(np.arange(0, 5), 12),
'rating': np.random.randint(1, 6, size=60)}

test_data = (pd.DataFrame(test_data)
             .assign(state = lambda x: x['state'].astype('category'),
                     session = lambda x: x['session'].astype('category'))
            )

tester_mod = bmb.Model('rating ~ bs(time, degree=2, df=3) * state + state * level * trait + (1|session)', data=test_data)
tester_mod.build()
```
I get a `ValueError` from PyMC - `operands could not be broadcast together with shapes (5,) (15,)`.  I can't think why this is happening, but the offending term seems to be the `bs(time, degree=2, df=3) * state` term - dropping the interaction leads to the model being built. 

Is this related to the `coords` Bambi/formulae give categorical predictors? I coded my own model in PyMC to work around this using `patsy`, and I noted that the intercept term (and thus one of the `state` level predictions) has basically no variability after estimation, and I am guessing Bambi does something clever behind the scenes to negate this! Any help hugely appreciated!

**Comment by tomicapretto** [comment]
Hey!

Which Bambi version are you using? I think this is related to some changes I've just introduced. Can you install from #493 and check again?

**Comment by alexjonesphd** [comment]
Hey! This was with 0.7.1 from conda forge - do I just `pip install git+https://github.com/tomicapretto/bambi.git` for the #493 fork?

**Comment by tomicapretto** [comment]
You can do

```shell
conda uninstall bambi # or pip uninstall bambi
pip install git+https://github.com/tomicapretto/bambi.git@extract_args
```

the uninstall is needed to make sure the install actually installs something. When the version of what you're installing is the same than the version you already have installed, nothing happens.

**Comment by tomicapretto** [comment]
> Thanks @tomicapretto - I tried the above but still got the same error with the fork (which is still 0.7.1 right?)

Yes, it's still 0.7.1 because we haven't updated it yet. I'll have a look later today to see what may be the root of the problem.

**Comment by tomicapretto** [comment]
@alexjonesphd this was a problem with how formulae was handling levels of interactions involving numerical terms with more than one column (as is in the case of a bs() call). If you install `formulae` from the development version, it should work now.

Do

```shell
pip uninstall formulae
pip install git+https://github.com/bambinos/formulae.git
```

It's working on my side now 

![image](https://user-images.githubusercontent.com/25507629/165397448-f859e9fd-2fdf-47af-8faa-4965416dfcb5.png)

**Comment by alexjonesphd** [comment]
@tomicapretto amazing - thank you so much! I had some difficulty with this after my conda install of bambi, some sort of issue with a package called `fastprogress` that was being removed when conda uninstalled bambi. 

In case this is helpful to anyone before `formulae` and `bambi` are updated, I:
 - Created a clean environment
 - Installed `bambi` via `pip install git+https://github.com/tomicapretto/bambi.git@extract_args`
 - Uninstalled `formulae` via pip 
 - Installed `formulae` via `pip install git+https://github.com/bambinos/formulae.git`

*However* now I am encountering a new issue with these bleeding edge versions (sorry!!) - the full dataset I am using this on is large (~183,000 rows, ~30,000 group effects). My Jupyter kernel dies consistently during the model instantiation phase, which I think is related to `formulae` as I can reproduce the same behaviour with `formulae.design_matrices`.  `formulae` will build the design matrix with a random sample of up to half the data, so it seems an issue of scaling up to large samples.

Interestingly, there are no issues building the full model and design matrix using the conda install - the only issue being the interaction term needed to be omitted, obviously solved above. Let me know if I should file this as an issue over on `formuale` and thanks again!

**Comment by tomicapretto** [comment]
@alexjonesphd I'm sorry about that issue. And yes, please open an issue in formulae to see if we can solve it.
