### ISSUE TITLE
bambi modifies dtypes of DataFrames silently

### ISSUE THREAD

**Issue by alexjonesphd** [bambinos/bambi#498]
Hello all,

I've just come across a bit of a gotcha in the library which may be intentional, but tripped me up for a while - pandas DataFrame `object` dtypes are set to `category` silently after being args in `bambi` model that is built, even if explicitly set using `categorical`.

For example:
```
import bambi as bmb

adults = bmb.data.datasets.load_data('adults')
print(adults.dtypes)
### income, sex, race are object

test = bmb.Model('age ~ sex * race', data=adults)
#test = bmb.Model('age ~ sex * race', categorical=['age', 'sex'], data=adults) # same effects observed with this line
test.build()

print(adults.dtypes)
### income, sex, race are category
```
This can cause some unexpected behaviour if working with the DataFrame post-model building (e.g. `.groupby` behaves differently with categoricals, `query` with categoricals can be strange, etc). 

I think this line, and up to line 139, are the issue: https://github.com/bambinos/bambi/blob/d6a7603af1d1339924b1c8373d8566321ed86ff0/bambi/models.py#L130
Am I right in thinking a `data.copy()` call before line 130 would prevent this? 

Again not sure if this is intentional behaviour for something downstream later but thought I would check here! 

EDIT: This is present in the `extract_args` branch.

**Comment by tomicapretto** [comment]
@alexjonesphd thanks for reporting this issue. It looks like there's an easy fix. I'll try to do it soon.
