### ISSUE TITLE
Unexpected keyword argument to `design_matrices()` when defining model 

### ISSUE THREAD

**Issue by conorhassan** [bambinos/bambi#511]
Following the basic example on the readme, e.g. 
```
import bambi as bmb
import numpy as np
import pandas as pd

data = pd.DataFrame({
    "y": np.random.normal(size=50),
    "g": np.random.choice(["Yes", "No"], size=50),
    "x1": np.random.normal(size=50),
    "x2": np.random.normal(size=50)
})

model = bmb.Model("y ~ x1 + x2", data)
```
When running the line defining the Bambi model, I get the error "`design_matrices()` got an unexpected keyword argument `'eval_env'`". 

Looking at the source code for the `design_matrices()` function, it looks like the argument is `env` rather than `eval_env`, but this is my first time using Bambi, so I am not confident that I know whats going on.

**Comment by tomicapretto** [comment]
@conorhassan thanks for opening this issue!

It's possible you're having that issue because you don't have compatible versions of `formulae` and `bambi`. You can install Bambi version 0.8.0 (last release) with `pip install bambi` and it should update `formulae` to the correct version as well.

**Comment by tomicapretto** [comment]
Haven't heard in a while. I think this is a non-issue.
