### ISSUE TITLE
Is there a Bambi version that works with pymc V4 (main branch)

### ISSUE THREAD

**Issue by sreedta8** [bambinos/bambi#518]
Hi

This is more a clarifying question than an issue. I'm doing testing of ```pymc``` on three  platforms (Windows, Linux, and Macs). For the more complex hierarchical models I usually use ```bambi```. Is there a version of ```bambi``` that works with ```pymc v4 main branch```? If there is, I would love to know how I can install it.

Sree

**Comment by aloctavodia** [comment]
If you install Bambi from main it will run with pymc v4.

**Comment by sreedta8** [comment]
Is ```git``` the preferred way to install Bambi from main using this command ```pip install git+https://github.com/bambinos/bambi.git```?

**Comment by sreedta8** [comment]
@aloctavodia could you also provide me any documentation or examples that show how I can change control parameters such as ```target_accept``` or```max_treedepth```via Bambi?

**Comment by aloctavodia** [comment]
> Is `pip` the preferred way to install Bambi from main using this command `pip install git+https://github.com/bambinos/bambi.git`?

Yes, that's correct.

You can pass those control parameters directly to `.fit()`, see this example.
https://bambinos.github.io/bambi/main/notebooks/radon_example.html

**Comment by sreedta8** [comment]
@aloctavodia thank you so much for both

**Comment by canyon289** [comment]
Thanks for being our first user of the brand new bambi pymc v4 super combo! Closing, if you have any issues please feel free to reopen

**Comment by aloctavodia** [comment]
We love to hear that Bambi is being helpful for you and your team. Thanks for taking the time to write this very encouraging words!
