### ISSUE TITLE
PyMC Jax support

### ISSUE THREAD

**Issue by markgoodhead** [bambinos/bambi#522]
Hello, 

Are there plans to add/support the Jax (and hence GPU) backend for PyMC 4 now that that's been released? I just tried with the latest release (admittedly only out for a couple of hours!) and it looks to be sampling with the CPU still (unsure which backend is being used)?

Thanks very much!

**Comment by tomicapretto** [comment]
@zwelitunyiswa if I recall correctly you did some with JAX? Was it using Bambi or just PyMC?

**Comment by zwelitunyiswa** [comment]
@tomicapretto @canyon289   I was able to get Jax (numpyro and blackjax) working for Bambi (I have an M1 Mac, btw). I installed PYMC 4 first, then Bambi. Then conda install jaxlib, jax and numpyro. I then built the formula and model. Then, using the trick that you and @aloctavodia taught me: I used model.build() and then passed that to PYMC4 and it ran with no problem. I attached a screenshot.

<img width="1368" alt="Screen Shot 2022-06-07 at 9 14 04 AM" src="https://user-images.githubusercontent.com/32966743/172389237-aba3f90f-326b-4daf-9946-9ff7629b26d3.png">

**Comment by canyon289** [comment]
Very cool and thank you for sharing! Would you be willing to add some documentation showing how to do it? if so we can provide some more guidance as well!

**Comment by zwelitunyiswa** [comment]
Here is blackjax:

<img width="1133" alt="Screen Shot 2022-06-07 at 9 29 08 AM" src="https://user-images.githubusercontent.com/32966743/172392521-9479eeb3-ffd1-46c8-9938-1ffc05752a5b.png">

**Comment by zwelitunyiswa** [comment]
> Very cool and thank you for sharing! Would you be willing to add some documentation showing how to do it? if so we can provide some more guidance as well!

Do you mean for the docs on Bambi or just on this thread? Also, do you mean the installation process + model building or just model building? I would be happy to document the process but have no idea how to use Github (lol, I know). If you guys could help me, I would be happy to put together the guide.

**Comment by canyon289** [comment]
@zwelitunyiswa official docs for bambi! We'd be happy to talk you throught github and whatnot. I'll open an issue and tag you

**Comment by zwelitunyiswa** [comment]
@canyon289 Ok. That works. Thanks for the help and opportunity.

**Comment by aloctavodia** [comment]
Thanks @zwelitunyiswa for contributing with this example. 

I think we should change `.fit()` so it can accept Jax-based samplers. Currently, we have `method` argument accepting  the values "mcmc", "vi" or "laplace", we should extend it.

**Comment by tomicapretto** [comment]
> Thanks @zwelitunyiswa for contributing with this example.
> 
> I think we should change `.fit()` so it can accept Jax-based samplers. Currently, we have `method` argument accepting the values "mcmc", "vi" or "laplace", we should extend it.

I agree. We could do that internally. Something like "mcmc-jax" or "mcmc-jax-cpu", "mcmc-jax-gpu", and others if there are more options.

**Comment by zwelitunyiswa** [comment]
> > Thanks @zwelitunyiswa for contributing with this example.
> > I think we should change `.fit()` so it can accept Jax-based samplers. Currently, we have `method` argument accepting the values "mcmc", "vi" or "laplace", we should extend it.
> 
> I agree. We could do that internally. Something like "mcmc-jax" or "mcmc-jax-cpu", "mcmc-jax-gpu", and others if there are more options.

If it is "mcmc-jax", the user cant the user just pass their own kwargs conditional on what they select?  (Numpyro has some different kwargs than Blackjax for example)

**Comment by tomicapretto** [comment]
> > > Thanks @zwelitunyiswa for contributing with this example.
> > > I think we should change `.fit()` so it can accept Jax-based samplers. Currently, we have `method` argument accepting the values "mcmc", "vi" or "laplace", we should extend it.
> > 
> > 
> > I agree. We could do that internally. Something like "mcmc-jax" or "mcmc-jax-cpu", "mcmc-jax-gpu", and others if there are more options.
> 
> If it is "mcmc-jax", the user cant the user just pass their own kwargs conditional on what they select? (Numpyro has some different kwargs than Blackjax for example)

I'm not very familiar with these methods. But what you say makes sense. We need to think what's the best way to include those kwargs in our interface.
