### ISSUE TITLE
Handle offset appropriately

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#528]
The formula interface supports `offsets`, but Bambi does not treat them accordingly. It treats them as any other term when they should receive a coefficient equal to 1.

**Comment by aflaxman** [comment]
I was excited to discover this feature, because I was just hacking around trying to emulate it.  IIUC it is not quite working for me, though.  See this notebook for a minimal example where
```
model = bmb.Model('outcome_cnt ~ x_1 + x_2 + offset(log_patient_days) + (1|hospital)',
                  df, family="poisson", link='log')
fit = model.fit()
```
leads to a `SamplingError`: https://gist.github.com/aflaxman/838fece08770d68e1410320e27289f16
