### ISSUE TITLE
Censored Data in Bambi

### ISSUE THREAD

**Issue by don-jil** [bambinos/bambi#541]
First, I'm delighted to find babmi and formulae, and very much appreciate all the work you are doing in this space. I'm working with some censored data.  I have used brms in R to build models in STAN, but I'd like to transition to python where the data preparation and visualization work occurs.  As a feature request, I would very much like to have the ability to use bambi (and formulae) to build the pymc model for censored data and survival analysis. I am currently working on this in pymc without bambi (and formulae), but I love the Wilkinson formula approach.  If this should be posted on the formulae repo instead, I'd be happy to do that.

**Comment by ipa** [comment]
I was just about to open a similar request... I've built a generic survival model using the pymc-learn API and was thinking about contributing it to bambi. The model uses the Weibull distribution (I don't have a Cox model). However, it has only been tested with 'right' censored data. 

My proposed syntax for the formula would be: `time | censor ~ x1 + x2 + x3`.
`censor` would contain information about censoring as ('left', 'none', 'right', and 'interval') or (-1, 0, 1, and 2) analogous to brms. 

Let's discuss. Would be happy to contribute on this.

**Comment by ipa** [comment]
This requires changes in the formulae package. Instead of `time | censor` it would be cleaner to implement this as a transformation `Surv(time, event)` similar to R.

I opened another issue bambinos/formulae#79

Work in progress on my fork

**Comment by don-jil** [comment]
Just a ping, here.  I love that this is moving along & that there is a really pull-request @ipa!  Is there anything that is missing @tomicapretto?  Anything I can do to help?

**Comment by tomicapretto** [comment]
@ipa @don-jil I haven't had much time to work in Bambi lately. But I'm slowly starting to gain momentum again.

The thing with the PR opened is that it will just work for that particular case. I think we need something more general and that requires working both in formulae and bambi internals if I recall correctly. 

I think I'll have something in my hands in the next 15 days. Would you be interested in helping to test/document stuff?

**Comment by don-jil** [comment]
Sorry for the delayed response, but yes happy to help test and or document.  :-) Will respond in the pull request to that end.

**Comment by tomicapretto** [comment]
I'm working on a proposal for models for censored data in Bambi. The problem is that I'm not very familiar with interval censoring (we can decide not to support this in a first shot), but I would still like to understand how it works.

@ipa @don-jil do you know of any references to interval censoring? Thanks!

**Comment by tomicapretto** [comment]
Closed since #577
