### ISSUE TITLE
Multi-level Regression throws error with blackjax sampler

### ISSUE THREAD

**Issue by SuryaMudimi** [bambinos/bambi#548]
Below error occurred when running [multi-level regression](https://github.com/bambinos/bambi/blob/main/docs/notebooks/multi-level_regression.ipynb) example with `nuts_blackjax` option 

![image](https://user-images.githubusercontent.com/59817370/180039999-27302e08-bd2f-4d73-8992-21e07e10b346.png)

Here are the libraries that I'm using.
![image](https://user-images.githubusercontent.com/16005550/180046670-c90a292a-8f4e-49d6-9845-25f39be34df5.png)

**Comment by tomicapretto** [comment]
Could you try using the development version?

**Comment by SuryaMudimi** [comment]
@tomicapretto Thanks, It worked.
