### ISSUE TITLE
Error on running Bambi on Colab

### ISSUE THREAD

**Issue by fatihbozdag** [bambinos/bambi#549]
Greetings all,

I am trying to run bambi on colab, however I got into some issues;

First problem is as follows; 

```
`NoSectionError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/aesara/configparser.py](https://localhost:8080/#) in fetch_val_for_key(self, key, delete_key)
    236             try:
--> 237                 return self._aesara_cfg.get(section, option)
    238             except InterpolationError:

15 frames
NoSectionError: No section: 'blas'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
KeyError: 'blas__ldflags'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
ModuleNotFoundError: No module named 'mkl'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/aesara/link/c/cmodule.py](https://localhost:8080/#) in check_mkl_openmp()
   2683 you set this flag and don't set the appropriate environment or make
   2684 sure you have the right version you *will* get wrong results.
-> 2685 """
   2686         )
   2687 

RuntimeError: 
Could not import 'mkl'.  If you are using conda, update the numpy
packages to the latest build otherwise, set MKL_THREADING_LAYER=GNU in
your environment for MKL 2018.

If you have MKL 2017 install and are not in a conda environment you
can set the Aesara flag blas__check_openmp to False.  Be warned that if
you set this flag and don't set the appropriate environment or make
sure you have the right version you *will* get wrong results.`
```

Than I've updated mkl via `!pip install mkl -U` and got the second issue;
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-7-e7c20f48c217>](https://localhost:8080/#) in <module>()
----> 1 import bambi as bmb

6 frames
[/usr/local/lib/python3.7/dist-packages/aesara/tensor/nnet/opt.py](https://localhost:8080/#) in <module>()
    492 
    493 # Register Cpu Optimization
--> 494 conv_groupopt = aesara.graph.optdb.LocalGroupDB()
    495 conv_groupopt.__name__ = "conv_opts"
    496 register_specialize_device(conv_groupopt, "fast_compile", "fast_run")

AttributeError: module 'aesara' has no attribute 'graph'
```
Then, I've update tensorflow with `!pip install -U tensorflow-gpu` and I got stuck in third;

```
ValueError                                Traceback (most recent call last)
[<ipython-input-9-e7c20f48c217>](https://localhost:8080/#) in <module>()
----> 1 import bambi as bmb

8 frames
[/usr/local/lib/python3.7/dist-packages/aesara/graph/optdb.py](https://localhost:8080/#) in register(self, name, optimizer, use_db_name_as_tag, *tags, **kwargs)
     69 
     70         if name in self.__db__:
---> 71             raise ValueError(f"The tag '{name}' is already present in the database.")
     72 
     73         if use_db_name_as_tag:

ValueError: The tag 'local_inplace_sparse_block_gemv' is already present in the database.
```
Anybody has the same problem? I am not expert enough to proceed further, can somebody explain what is actually wrong?

Thanks.

**Comment by aloctavodia** [comment]
@canyon289 I think you were trying to fix this or a similar  issue.

**Comment by canyon289** [comment]
Hi @fatihbozdag, for now please run this line in colab in its own cell
```
%env MKL_THREADING_LAYER=GNU
```

An automatic fix in colab is coming *soon*

For additional details follow this discussion
https://github.com/aesara-devs/aesara/discussions/1068

**Comment by fatihbozdag** [comment]
> Hi @fatihbozdag, for now please run this line in colab in its own cell
> 
> ```
> %env MKL_THREADING_LAYER=GNU
> ```
> 
> An automatic fix in colab is coming _soon_
> 
> For additional details follow this discussion [aesara-devs/aesara#1068](https://github.com/aesara-devs/aesara/discussions/1068)

Thank you now it is working!. One last question. Can I use GPU acceleration as well? I'm trying to apply categorical regression and it requires roughly 10 hours of sampling on colab with CPU. Will running on GPU or TPU reduce that time significantly? If that's the case, I will pay for colab pro.

**Comment by fatihbozdag** [comment]
update.

Following  #522 

I've managed to run bambi with jax sampler on Kaggle. 

![bambi_gpu](https://user-images.githubusercontent.com/59308858/180576012-50735844-4ed1-45cf-b828-93867b5720c1.png)

**Comment by hans-ekbrand** [comment]
> Can I use GPU acceleration as well? I'm trying to apply categorical regression and it requires roughly 10 hours of sampling on colab with CPU. Will running on GPU or TPU reduce that time significantly? If that's the case, I will pay for colab pro.

Yes, colab (standard, not PRO) already has a jaxlib with cuda support installed. The only thing needed should be 

```
method = "nuts_numpyro"
``` 
in the `fit()` command

**Comment by fatihbozdag** [comment]
> > Can I use GPU acceleration as well? I'm trying to apply categorical regression and it requires roughly 10 hours of sampling on colab with CPU. Will running on GPU or TPU reduce that time significantly? If that's the case, I will pay for colab pro.
> 
> Yes, colab (standard, not PRO) already has a jaxlib with cuda support installed. The only thing needed should be
> 
> ```
> method = "nuts_numpyro"
> ```
> 
> in the `fit()` command

I did try this and got the following error,
```

/usr/local/lib/python3.7/dist-packages/numpy/linalg/linalg.py:2158: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)
/usr/local/lib/python3.7/dist-packages/bambi/backend/pymc.py:360: RuntimeWarning: invalid value encountered in sqrt
  stds = np.diag(np.linalg.inv(hessian) ** 0.5)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-d6815a73467c>](https://localhost:8080/#) in <module>()
----> 1 idata = model.fit(method = "nuts_numpyro")

4 frames
<__array_function__ internals> in reshape(*args, **kwargs)

[/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py](https://localhost:8080/#) in _wrapfunc(obj, method, *args, **kwds)
     55 
     56     try:
---> 57         return bound(*args, **kwds)
     58     except TypeError:
     59         # A TypeError occurs if the object does have such a method in its

ValueError: cannot reshape array of size 12 into shape (4,8)
```

**Comment by aloctavodia** [comment]
The version of Bambi using jax samplers has not been released yet. You have to install the development version from github. 

Also you have two options for jax samplers nuts_numpyro  and nuts_blackjax.

**Comment by fatihbozdag** [comment]
> I got no problem with the following code;

model.build()

```
with model.backend.model:
    idata=pm.sampling_jax.sample_numpyro_nuts(draws= 10000, tune = 1000, target_accept = .95, chain_method = 'parallel', postprocessing_backend = 'cpu')
```
However, I assume previous problem " `ValueError: cannot reshape array of size 12 into shape (4,8)` " is related to numpy, am I right? 

The problem is that dataset is huge and even with Kaggle GPU, it took more than 4 hours, overall more than 12 hours which is more than allowed in any cloud system. 

`sample: 100%|██████████| 11000/11000 [4:44:32<00:00,  1.55s/it, 1023 steps of size 1.77e-03. acc. prob=0.96]`

Now I am trying to run sampling on google colab (standart) with GPU

`warmup:   6%|▋         | 699/11000 [37:59<**9:42:17**,  3.39s/it, 1023 steps of size 2.09e-03. acc. prob=0.93]
`

I am not sure how I should proceed, and I am open to suggestions.

**Comment by hans-ekbrand** [comment]
> Now I am trying to run sampling on google colab (standart) with GPU
> 
> `warmup: 6%|▋ | 699/11000 [37:59<**9:42:17**, 3.39s/it, 1023 steps of size 2.09e-03. acc. prob=0.93] `
> 
> I am not sure how I should proceed, and I am open to suggestions.

Collect samples semi-manually: set "draws" to a number low enough so that the run finish before the session is interrupted, save the arvis object to disk (with pickle), disconnect the colab instance, wait until your quota on colab is high enough for you to aquire a new GPU, repeat. Do posterior analys only when you have collected enough draws.

**Comment by canyon289** [comment]
To scope this ticket, it sounds like the error for running Bambi on colab has been resolved right? We have a short term fix, and I assure you the long term fix is actively being worked on. If the issue now is slow sampling on colab, thats a very different thing, either requiring model debugging, data thinning, or frankly just paying for colab pro to get more computational speed.

Let me know if my assessment here is correct

**Comment by fatihbozdag** [comment]
> To scope this ticket, it sounds like the error for running Bambi on colab has been resolved right? We have a short term fix, and I assure you the long term fix is actively being worked on. If the issue now is slow sampling on colab, thats a very different thing, either requiring model debugging, data thinning, or frankly just paying for colab pro to get more computational speed.
> 
> 
> 
> Let me know if my assessment here is correct

You right, we got off-topic yet still the focus is on running on colab. Sorry for changing the topic, I can close it with 'solved' tag.

**Comment by canyon289** [comment]
No apologies needed! Were really glad Bambi is useful for you!
