### ISSUE TITLE
Support aesara.config.floatX="float32"

### ISSUE THREAD

**Issue by hans-ekbrand** [bambinos/bambi#550]
For large models, using float32 is great, it reduces the RAM footprint on the GPU to a half, and from what I can see the results are just as good as with float64.

For the first chain, Bambi always succeeds when running under 

`aesara.config.floatX="float32"`

but the initialisation of the second chain (when using `chain_method="sequential"`) always fails. A pure `pymc` implementation did not show this problem:

https://drive.google.com/file/d/1FK6ABqV-S8MJuKRYdwRHrC54uajFAQZp/view?usp=sharing

The first chain outputs this:

```
sample: 100%|██████████| 4000/4000 [02:31<00:00, 26.38it/s, 31 steps of size 1.01e-01. acc. prob=0.95]
```

But the second chain appears to try to take a step so small that it overflows:

```
sample: 100%|██████████| 4000/4000 [00:17<00:00, 235.19it/s, 1 steps of size 1.18e-38. acc. prob=0.00]
```

I suppose never trying to take a step smaller than the smallest float32 should fix the issue?

**Comment by tomicapretto** [comment]
I've experienced similar issues with numpyro sampler (related to step sizes and number of steps). Another option could be to try blackjax sampler instead of numpyro sampler and see if you observe the same issue.

**Comment by hans-ekbrand** [comment]
> I've experienced similar issues with numpyro sampler (related to step sizes and number of steps). Another option could be to try blackjax sampler instead of numpyro sampler and see if you observe the same issue.

I'll try blackjax, but barebone pymc had no trouble with the numpyro sampler. Do you think this is outside the scope of Bambi?

**Comment by tomicapretto** [comment]
I'm not 100% sure, but I think so. To check if it's a Bambi model you should create a PyMC model that reproduces the Bambi model exactly. It is, a PyMC model that matches the PyMC model that is created by Bambi under the hood.

**Comment by tomicapretto** [comment]
@hans-ekbrand do you still see the problem?
