### ISSUE TITLE
Reference for dataset?

### ISSUE THREAD

**Issue by omarcr** [bambinos/bambi#560]
Hello, I am following this tutorial on a dataset called "ESCS":

https://bambinos.github.io/bambi/0.9.0/notebooks/ESCS_multiple_regression.html

The only information provided about the dataset is the following:

```
    "ESCS": FileMetadata(
        filename="ESCS.csv",
        url="https://ndownloader.figshare.com/files/28870722",
        checksum="0195545797a4258de138a205a013a84022bbe23e7ff47782b179055c706300b6",
        description="""
A longitudinal study of hundreds of adults who completed dozens of different self-report and
behavioral measures over the course of 15 years. Among the behavioral measures is an index of
illegal drug use.
```

Where can I find a reference research paper for such a dataset? I assumed this will be contextualized in the tutorial but no further information than the predictor and the variables is provided.

**Comment by tomicapretto** [comment]
@omarcr you can find it in the paper here https://www.jstatsoft.org/article/view/v103i15
