### ISSUE TITLE
Extracting posterior draws with Bambi

### ISSUE THREAD

**Issue by Aminsn** [bambinos/bambi#565]
Is it possible to extract the posterior draws after fitting a model with Bambi? Similar to this in Stan: [Extract posterior draws](https://mc-stan.org/cmdstanr/reference/fit-method-draws.html)

**Comment by canyon289** [comment]
It sure is! The idata object returned will have everything in it. Check out the schema specification

https://arviz-devs.github.io/arviz/schema/schema.html

**Comment by Aminsn** [comment]
> It sure is! The idata object returned will have everything in it. Check out the schema specification
> 
> https://arviz-devs.github.io/arviz/schema/schema.html

Thanks. One more question, when defining the model formula as "y ~ x", is it possible to extract the posteriors of mu (y ~ N(mu, sigma), mu = alpha + beta*x) directly from the fitted object rather than calculating it using the posteriors of alpha and beta? If there is a vignette showing how that can be done I would really appreciate it if you could share it with me.

**Comment by aloctavodia** [comment]
If you want the mean to be automatically computed and saved pass the argument  `include_mean=True` to the `fit` method.

**Comment by canyon289** [comment]
With multiple solution I think were good here
