### ISSUE TITLE
How to do Additive Regression Trees analysis with Bambi?

### ISSUE THREAD

**Issue by fatihbozdag** [bambinos/bambi#568]
Greetings all,

Is there a way to apply BART analysis with Bambi? I've seen in the [roadmap](https://github.com/bambinos/bambi/wiki/Roadmap) that it is to be implemented with `pymc 4 `stable. However, I could not find any further information. Is there a way to create `pymc_bart `model with Bambi?

**Comment by tomicapretto** [comment]
I'm sorry but it's not possible at the moment

**Comment by tomicapretto** [comment]
The discussion may happen in   #578
