### ISSUE TITLE
`predict` fails when formula contains `np.log`

### ISSUE THREAD

**Issue by omrihar** [bambinos/bambi#571]
I've set up a simple Poisson GLM where I need to use an offset. When I try to call `predict` with new data I get an AttributeError:
```python
AttributeError: 'LazyCall' object has no attribute 'name'
```

Minimal example to reproduce the issue:
```python
import numpy as np
import bambi as bmb
import pandas as pd

N = 100
x = np.linspace(0, 10, N)
y = 5 * x + 3
z = np.random.uniform(0, 1, N)

df = pd.DataFrame({'x': x, 'y': y, 'z': z})
model = bmb.Model('y ~ x + offset(np.log(z))', df)
trace = model.fit()

N = 100
x = np.linspace(0, 10, N)
y = 5 * x + 3
z = np.random.uniform(0, 1, N)
df_new = pd.DataFrame({'x': x, 'y': y, 'z': z})
pred = model.predict(idata=trace, data=df_new, inplace=False)
```

Note: it's not important that I didn't choose the family='poisson' or that I just used linear regression with an offset. Changing to a Poisson with a log-link has no impact.

Note: A simple workaround would be to create an already logged column but it's less elegant as a general solution.

**Comment by tomicapretto** [comment]
Thanks for opening this issue! I think it's due to the fact that `offset()` is receiving a function call instead of the name of a variable. 

This is not a problem in Bambi itself, but in the library Bambi uses to parse model formulas.

**Comment by tomicapretto** [comment]
This is already fixed in formulae, since https://github.com/bambinos/formulae/pull/81. If you need this feature, you can update to the development version of formulae. 

Thanks for reporting the issue!

**Comment by omrihar** [comment]
Awesome! Thanks!

For now, until it hits the main branch, I'll just add a logged column ;)
