### ISSUE TITLE
Make it possible to pass arguments to link functions in PyMC backend

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#574]
We have a warning every time we use a model that uses `aesara.tensor.softmax`. This is because it asks to pass the `axis` explicitly. The fix is not too straightforward because we don't have how to pass arguments to link functions in the PyMC backend.

It's it very doable, but it requires a little of thought.

**Comment by tomicapretto** [comment]
This is the warning

```
/home/tomas/anaconda3/envs/bambi/lib/python3.10/site-packages/aesara/tensor/nnet/basic.py:1116: FutureWarning: Softmax now accepts an axis argument. For backwards-compatibility it defaults to -1 when not specified, but in the future the default will be `None`
```

**Comment by zwelitunyiswa** [comment]
I ran into this warning earlier this week. Question: does this mean that
the softmax accepts both long and wide data for the simplex in aesara. If
so, would it not make sense to switch the default to long format for the
simplex in the dataframe, which is the default for the other other families?

**Comment by tomicapretto** [comment]
This warning is not something that impacts how we use data at a high-level. It's mostly an internal thing that won't change any result. It will just remove the warning and make sure Bambi still works the right way when aesara goes with `axis=None` as default.

**Comment by tomicapretto** [comment]
This is a non-issue anymore since we already fixed the issue when it was needed.
