### ISSUE TITLE
bambi and PyMC 4 compatibility

### ISSUE THREAD

**Issue by kuvychko** [bambinos/bambi#576]
I am using PyMC 4.2, and while trying to install bambi (using conda) it is trying to install pymc3 and theano:

```
The following NEW packages will be INSTALLED:

  bambi              conda-forge/label/cf202003/noarch::bambi-0.1.5-py_1
  bottleneck         pkgs/main/win-64::bottleneck-1.3.5-py310h9128911_0
  dill               pkgs/main/noarch::dill-0.3.4-pyhd3eb1b0_0
  fftw               pkgs/main/win-64::fftw-3.3.9-h2bbff1b_1
  icc_rt             pkgs/main/win-64::icc_rt-2022.1.0-h6049295_2
  mkl_fft            pkgs/main/win-64::mkl_fft-1.3.1-py310ha0764ea_0
  mkl_random         pkgs/main/win-64::mkl_random-1.2.2-py310h4ed8f06_0
  numexpr            pkgs/main/win-64::numexpr-2.8.3-py310hb57aa6b_0
  numpy-base         pkgs/main/win-64::numpy-base-1.21.5-py310h206c741_3
  pymc3              pkgs/main/win-64::pymc3-3.11.4-py310haa95532_0
  semver             conda-forge/label/cf202003/noarch::semver-2.9.1-py_0
  statsmodels        pkgs/main/win-64::statsmodels-0.13.2-py310h2bbff1b_0
  theano-pymc        pkgs/main/win-64::theano-pymc-1.1.2-py310h4ed8f06_0
```

Since I didn't want to break my installation of PyMC 4.2 I cancelled bambi install. Is there a plan to update bambi for pymc 4? https://www.pymc.io/blog/v4_announcement.html

**Comment by kuvychko** [comment]
@tomicapretto - I tried both links from this page (with with the same result): https://anaconda.org/conda-forge/bambi

**Comment by tomicapretto** [comment]
Can you try creating a new conda environment, using one of the Python versions officially supported (now the are 3.8, 3.9, or 3.10), and installing either with `pip` or `conda`?

**Comment by kuvychko** [comment]
I am running Python 3.9. I just tried installing via pip and it worked (I also checked that I can import bambi):
`Successfully installed bambi-0.9.1 formulae-0.3.4 numpy-1.21.6`

It looks like this is only an issue when installing via conda.

**Comment by tomicapretto** [comment]
I'm happy it was resolved!

**Comment by kuvychko** [comment]
@tomicapretto - thank you for your help! 👍
