### ISSUE TITLE
Docs: Malformed hyperlink in Getting Started page

### ISSUE THREAD

**Issue by hectormz** [bambinos/bambi#597]
The hyperlink to `rstanarm` in the Priors section on Getting Started is malformed:
![image](https://user-images.githubusercontent.com/23343812/204104042-99e891a6-efb2-4405-ab4e-6064d6fd8776.png)

The [notebook that generates the page](https://github.com/bambinos/bambi/blob/main/docs/notebooks/getting_started.ipynb) looks fine. I'm guessing the notebooks are converted by Sphinx and something about backticks + link mess it up. I also like the backticks here, but unless someone knows how to fix it, dropping the backticks might be the best solution. Links to `lme4` elsewhere in the docs don't have backticks, so maybe that's okay.

**Comment by tomicapretto** [comment]
Fixed in https://github.com/bambinos/bambi/commit/aed96be6547c357b56c6a55298882362ff9fac1d

We just needed to remove the backticks from the name within the brackets.
