### ISSUE TITLE
Add Governance

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#600]
I've been chatting with @aloctavodia about adding a Governance structure and document to the project. The current governance of ArviZ looks appealing as a starting point. 

Anyone who reads this and is interested in participating in the governance of Bambi, please comment here or send me a message. The ultimate goal is to make this a more transparent and robust project that doesn't rely completely, and by (lack of) design, on one or two self-selected core developers.

**Comment by canyon289** [comment]
I'm interested

**Comment by zwelitunyiswa** [comment]
I am interested too.

**Comment by tomicapretto** [comment]
Closed #709
