### ISSUE TITLE
Issues installing bambi with pip

### ISSUE THREAD

**Issue by omrihar** [bambinos/bambi#602]
I'm not sure if this is only an issue with my current system, but when I try to install bambi with `pip install bambi` it fails after claiming that the dependency for numpy is  `numpy<1.22.0, >=1.16.1` which I know is wrong (i.e. related to an old version). However, the wheel that was downloaded is for bambi 0.9.1 which should depend on pymc and numpy>1.22. I tried running pip with `--no-cache-dir` but this made no difference. 
When I installed the version directly from github it installed correctly, but I still cannot fit a model because I get erros related to 
```python
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.212, but found None. Extra debug information: force_compile=False, _need_reload=True
```
which I'm guessing is related to some weird python dependency issue.

System details:
manjaro linux 5.10.154-1
python 3.11.0
installed via pyenv
I tried installing in a brand new virtualenv. I also tried specifying numpy version explicitly, as in `pip install numpy=1.23.5 bambi=0.9.1` but this also didn't work.

I'm not sure if this is a bambi packaging issue or something weird happening on my system, but any hints as to how to solve it would be greatly appreciated.

**Comment by tomicapretto** [comment]
I had similar issues in the past, and it's been always a pain. I had problems with NumPy, SciPy, Numba, PyMC, Aesara, and their lower-level dependencies. But I never had the same error as you. 

From the system details, I imagine it could be related to the Python version (3.11). Does it work if you use 3.10.X or 3.9.X? Notice Bambi and PyMC are both tested on Python 3.8, 3.9 and 3.10.

**Comment by omrihar** [comment]
I manage to install bambi in a virtualenv with python 3.10 (tried on 3.10.4), it still doesn't install the correct version of numpy (shows the same requirementn `numpy<1.22.0, >=1.16.1` as above, but the install succeeds. When I try to fit a model with bambi, though, it fails with compilation error, at the `.fit()` stage.

This is the code I used:

```python
data = pd.DataFrame({'x': [1,2,3], 'y': [3,2,4]})
model = bmb.Model("y ~ x", data)
```
This worked, then running `model.fit()` fails loudly with a huge traceback that ends with
```
CompileError: Compilation failed (return status=1):
/usr/bin/g++ -shared -g -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -march=skylake -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -mno-sse4a -mno-fma4 -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512er -mno-avx512pf -mno-avx512vbmi -mno-avx512ifma -mno-avx5124vnniw -mno-avx5124fmaps -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mno-clwb -mno-clzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mno-hle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mno-mwaitx -mno-pconfig -mno-pku -mno-prefetchwt1 -mprfchw -mno-ptwrite -mno-rdpid -mrdrnd -mrdseed -mno-rtm -mno-serialize -msgx -mno-sha -mno-shstk -mno-tbm -mno-tsxldtrk -mno-vaes -mno-waitpkg -mno-wbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=4096 -mtune=skylake -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/home/omri/.pyenv/versions/3.10.4/envs/experiment_3/lib/python3.10/site-packages/numpy/core/include -I/home/omri/.pyenv/versions/3.10.4/include/python3.10 -I/home/omri/.pyenv/versions/3.10.4/envs/experiment_3/lib/python3.10/site-packages/aesara/link/c/c_code -L/home/omri/.pyenv/versions/3.10.4/lib -fvisibility=hidden -o /home/omri/.aesara/compiledir_Linux-5.10--MANJARO-x86_64-with-glibc2.36--3.10.4-64/lazylinker_ext/lazylinker_ext.so /home/omri/.aesara/compiledir_Linux-5.10--MANJARO-x86_64-with-glibc2.36--3.10.4-64/lazylinker_ext/mod.cpp -lpython3.10
/usr/bin/ld: /home/omri/.pyenv/versions/3.10.4/lib/libpython3.10.a(pythonrun.o): warning: relocation against `_Py_UnhandledKeyboardInterrupt' in read-only section `.text'
/usr/bin/ld: /home/omri/.pyenv/versions/3.10.4/lib/libpython3.10.a(bytearrayobject.o): relocation R_X86_64_PC32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

Does this seem somewhat familiar? What I'm most confused about are the specification of the `numpy` requirements, that seem to come out of nowhere, since bambi does not specify them in this form, as far as I know.

**Comment by tomicapretto** [comment]
Double checking the repository and the latest release it does look like the latest release imposes that restriction. Sorry for that!

See here

https://github.com/bambinos/bambi/blob/0.9.1/requirements.txt

Is it possible for you to install it from the github repository?

**Comment by tomicapretto** [comment]
@omrihar there's a new release available. You should be able to install with `pip` now without this issue. Let me know if that works so we can close the issue :)

**Comment by omrihar** [comment]
Hi @tomicapretto I am indeed able to install `bambi` at the latest version, using `pip install bambi`. However you now have a different issue - since the `pymc` team decided to fork `aesara` and they no-longer rely on it, but you still do, if I don't install it explicitly I cannot import `bambi` (get `ModuleNotFoundError`).  I guess it would be an easy fix - just replace all instances of `aesara` with `pytensor`... 

Thanks! I'll close this one since it is indeed a different bug.
