### ISSUE TITLE
Figure in Sleepstudy example not being reproducible

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#606]
Seems the code used to generate the scatterplot is not working anymore 

![image](https://user-images.githubusercontent.com/25507629/205733068-862bd150-b434-4594-90f1-6b95a0f792ea.png)

I'm trying this but I don't like the end result 

```python
idata.posterior.plot.scatter(
    x="1|Subject", y="Days|Subject",
    hue="Subject__factor_dim",
    hue_style="discrete",
    add_colorbar=False,
    add_legend=False,
    ax=ax
)
```

![image](https://user-images.githubusercontent.com/25507629/205732938-bd64787e-ea6e-4679-afa3-04f3849d5b19.png)

I have ArviZ 0.14.0 and xarray 2022.11.0

**Comment by aloctavodia** [comment]
What about?


idata.posterior.plot.scatter(
    x="1|Subject", y="Days|Subject",
    hue="Subject__factor_dim",
    add_colorbar=False,
    add_legend=False,
    cmap="tab20",
    edgecolors=None,
)


![índice](https://user-images.githubusercontent.com/1338958/205906769-740fcde0-8317-4596-bd67-26f78b3c5269.png)

**Comment by tomicapretto** [comment]
looks better!
