### ISSUE TITLE
Drop documentation of previous releases

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#610]
I don't remember the reason why we wanted our documentation to keep track of the documentation in the previous releases. I think the reason was it is nice to be able to spot when something changed. 

However, it's making things more painful now. Not only do we have more dependencies, but old versions depend on old libraries that may not be installable anymore. And honestly, I don't want to do a bunch of work to keep this feature alive. It doesn't seem to be that important.

Should we drop the versioned documentation?

**Comment by tjburch** [comment]
Especially with the major recent changes in pymc/pytensor/etc. I think the costs of maintaining versioned docs vastly outweighs the benefits, so I support dropping.

**Comment by canyon289** [comment]
Drop it
