### ISSUE TITLE
TruncatedNormal in Hierarchical Setting

### ISSUE THREAD

**Issue by SuryaMudimi** [bambinos/bambi#617]
Hi All, Merry Christmas.

Bounds are working
`prior = {'x1':bmb.Prior("TruncatedNormal", mu=10,sigma=5,lower=0, upper=50)}`
`bmb.model('y ~ x1 + x2 + x3')`

Bounds are not working
`prior = {'x1|level':bmb.Prior('Normal',mu=bmb.Prior("TruncatedNormal", mu=10,sigma=5,lower=0, upper=50),sigma = 5)}`
`bmb.model('y ~ x1|level + x2 + x3')`

I am a noob. Any guidance is appreciated. Thanks

**Comment by tomicapretto** [comment]
Thanks for opening the issue! 

Could you provide a snippet I could copy, paste, and run to see the problem? 

I could simulate some data to see what's going on but that doesn't guarantee it's the same setting than yours.

**Comment by SuryaMudimi** [comment]
Sorry for delayed responce, hope this notebook helps
[bambi_hierarchical_TruncatedNormal.zip](https://github.com/bambinos/bambi/files/10366682/bambi_hierarchical_TruncatedNormal.zip)

**Comment by tomicapretto** [comment]
I'm not saying it makes sense to do the following, but it works. See the `noncentered=False`.

```python

covariate_priors2 = {
    "floor": bmb.Prior("Normal", mu=0, sigma=10),
    "log_u": bmb.Prior("Normal", mu=0, sigma=10),
    "floor|county": bmb.Prior(
        "TruncatedNormal", 
        mu=bmb.Prior("Normal", mu=0, sigma=2), 
        sigma=bmb.Prior("Exponential", lam=1),
        lower=-0.2,
        upper=0.2
    ),
    "sigma": bmb.Prior("Exponential", lam=1),
}

covariate_model2 = bmb.Model(
    formula="log_radon ~ floor + log_u + (floor|county)",
    data=df,
    priors=covariate_priors2,
    noncentered=False
 )

covariate_results2 = covariate_model2.fit()
az.summary(covariate_results2, var_names=["floor|county"])['mean'].describe()
```
```
count    85.000000
mean     -0.001788
std       0.024497
min      -0.077000
25%      -0.011000
50%      -0.002000
75%       0.010000
max       0.051000
Name: mean, dtype: float64
```

**Comment by SuryaMudimi** [comment]
Thank you @tomicapretto 

How do I understand the below difference ? 
with prior `{"floor|county": bmb.Prior("Normal", mu=0, sigma=bmb.Prior("Exponential", lam=1)} `  
![image](https://user-images.githubusercontent.com/16005550/211163474-724afae6-12be-4148-962c-f3df965be304.png)
with prior 
` "floor|county": bmb.Prior("TruncatedNormal", 
                              mu = bmb.Prior("Normal", mu=0, sigma=2), 
                              sigma = bmb.Prior("Exponential", lam=1),
                              lower=-0.2,upper=0.2)`
![image](https://user-images.githubusercontent.com/16005550/211163581-6fee8ca3-6ac5-4952-ac9f-f175e6aa48b6.png)

**Comment by SuryaMudimi** [comment]
@tomicapretto If I want to specify unpooled priors how should I do it ?

**Comment by tomicapretto** [comment]
> @tomicapretto If I want to specify unpooled priors how should I do it ?

Could you provide more information about which variable you want to consider in an unpooled manner? If it is `county`, the following formula does that `log_radon ~ 0 + floor + log_u + (0 + floor|county)`. See the slope for `floor` is still partially pooled. Then you would just need to pass a dictionary of priors (`{"floor": bmb.Prior(...)}`).

If you also want `floor` to be unpooled with respect to `county` you would use a regular interaction term.

`" log_radon ~ 0 + floor + floor:county + log_u"`

**Comment by SuryaMudimi** [comment]
@tomicapretto Thank you
