### ISSUE TITLE
Model do not converge using inference_method="nuts_numpyro"

### ISSUE THREAD

**Issue by lt-brs** [bambinos/bambi#620]
Hello,

I try to use `numpyro` sampling to shorten computation time but when I use `inference_method='nuts_numpyro'`, I get incoherent results and my chains do not converge to the same result while it does if I use the `inference_method='mcmc'`.

```
import bambi as bmb
import pandas as pd 
import arviz as az

data = pd.read_csv('no_convergence_numpyro.csv', index_col=0)
formula = 'target ~ 0 + '+' + '.join([cname for cname in data.columns if cname !='target'])

bmb_model = bmb.Model(formula=formula, data=data)
fit_output = bmb_model.fit(
    inference_method='nuts_numpyro'
    )

az.plot_trace(fit_output)
```

[no_convergence_numpyro.csv](https://github.com/bambinos/bambi/files/10351136/no_convergence_numpyro.csv)

- I first suspect that init strategy differ between pymc and numpyro looking at `bambi.backend.pymc`, but both seem to use jitter as init strategy. 
- I also tried to set JAX to a default 64bits for float `from jax.config import config`
`config.update("jax_enable_x64", True)`

Plot trace with `'mcmc'`: 
![image](https://user-images.githubusercontent.com/98035944/210752224-7045f9eb-09ea-4003-857b-cda71073a389.png)

Plot trace with `'nuts_numpyro'` : 
![image](https://user-images.githubusercontent.com/98035944/210752363-be6758ca-e511-40ab-868a-083cfb026790.png)

**Comment by zwelitunyiswa** [comment]
I tried your model and you are right, the sampling via jax (numpyro and
blackjax) is a mess. I tried increasing the target_accept to .99 and
increased the tuning to 5000 and even 20_000 to test. Still looked bad. I
also changed some inits but that did not help.

**Comment by tomicapretto** [comment]
I'm not completely sure, but I suspect it may be due to the difference in the initialization algorithms? The difference is very large, though.

Could you try with the following formula

```python
formula = 'target ~ 0 + '+' + '.join([f"scale({cname})" for cname in data.columns if cname !='target'])
```

**Comment by lt-brs** [comment]
Thank you for your answer @tomicapretto , indeed replacing the formula lead to chains convergence, and I obtain similar results running fit with "mcmc" or "nuts_numpyro". 
But if I run with "mcmc" with previous formula and "nuts_numpyro" with formula with scale and unscale the posterior I do not get similar results at all so I suppose pymc is not standard scaling data.

**Comment by zwelitunyiswa** [comment]
That's good to know. I have had convergence issues with numpyro with some models. Thanks @lt-brs / @tomicapretto . Something to keep in the mind.

**Comment by tomicapretto** [comment]
The scales of the variables are very different and that usually makes things harder for the sampler. `scale()` is helping here but it does not mean it will have such an impact in all cases.

I don't think the PyMC sampler is standardizing stuff (I don't know), but it seems to have a better sampling strategy so it's working even with the large differences in the scales of the variables.

And yes, it's expected not to get the same coefficients when scaling vs not-scaling the data

**Comment by tomicapretto** [comment]
@lt-brs if the question is answered please close the issue :D

**Comment by lt-brs** [comment]
Thank you for your help!
To some extent the problem is identified but not really solved. Since we add a scaling, we are bypassing the problem by fitting a different model and proposing an unlinear solution. 
The best solution would be to identify what are the difference between the two sampling strategy and if possible use the same strategy when inference_method="nuts_numpyro" as inference_method="mcmc".

Nevertheless, thank you for help and I will continue to investigate and try to find a solution. 
For sure I will let you know if I find relevant content

**Comment by tomicapretto** [comment]
Well, the transformation is linear. You can always unscale the parameters back to their original scale. See the first response here https://stats.stackexchange.com/questions/74622/converting-standardized-betas-back-to-original-variables

And for the sampling difference, I think this question is more appropriate in the PyMC repository where the PyMC sampler is actually implemented. 

I'm not completely sure you will be able to use the exact same algorithm when doing inference with both NumPyro and PyMC. There are some features, like mass matrix adaptation, that I'm not sure you can control in both cases such they are the same
