### ISSUE TITLE
Allow to use custom PyMC distributions as priors

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#630]
Currently we write priors in Bambi as 

```python
prior = bmb.Prior("DistributionName", param1=value1, param2=value2)
```

And then Bambi goes and looks for a distribution called `DistributionName` in PyMC. But what if a user wants to pass a custom function that returns the prior?

I have two alternatives in mind

```python
def CustomPrior(a, b):
    return pm.SomeDist(a) + pm.OtherDist(b)

# Alternative 1: Pass a callable
bmb.Prior(CustomPrior, a = 1, b = 2)

# Alternative 2: Still pass a name, but also pass a callable
bmb.Prior("CustomPrior", a = 1, b = 2, CustomPrior)
```

I'm slightly in favor of Alternative 2.

Note: Don't take the example seriously!

**Comment by canyon289** [comment]
I like #2, its more verbose but I think will be an easier API to maintain since the first arg will always be a string, and we dont need to do checking behind the scenes to figure out what type of prior it is

**Comment by tomicapretto** [comment]
I agree option 2 will be easier to maintain. Another pro is that the signature is similar to what we have for custom likelihoods. I think I'll get started with option 2, but I'll try not to forget about option 1 because I like it's conciseness may be beneficial as well.
