### ISSUE TITLE
How to create bounded distribution?

### ISSUE THREAD

**Issue by hyang57** [bambinos/bambi#638]
I am a beginner who has just started learning Bayesian regression. Thank you for developing Bambi, it greatly reduces the barrier and enables me to quickly get started. However, I encountered some issues while using it.

Due to the presence of some collinear factors, I want to ensure that all coefficients are positive to reduce the impact of collinearity. In classical linear regression, I can use np.exp(w_i) to ensure non-negativity of the factors. I would like to know how to create bounded distribution in Bambi to achieve this goal. 

I found some methods at https://docs.pymc.io/en/v3/api/bounds.html, but when I set family='gamma', the program doesn't run and gives an error:

My model:
```
Formula: Y ~X1+X2+X3+X4+X5
Family name: Gamma
Link: inverse
Observations: 3649
Priors:
  Common-level effects
    Intercept ~ Normal(mu: 0, sigma: 2.5244)
    X1 ~ Normal(mu: 0, sigma: 5.8012)
    X2 ~ Normal(mu: 0, sigma: 4.58)
    X3 ~ Normal(mu: 0, sigma: 9.146)
    X4 ~ Normal(mu: 0, sigma: 6.6306)
    X5 ~ Normal(mu: 0, sigma: 4.7666)

  Auxiliary parameters
    alpha ~ HalfCauchy(beta: 1)
```
Error
```
SamplingError: Initial evaluation of model at starting point failed!
Starting values:
{'Intercept': array(-0.58207916), 'X1': array(-0.42567191), 'X2': array(-0.28414028), 'X3': array(-0.64732721), 'X4': array(0.74060219), 'X5': array(-0.35786542), 'Y_alpha_log__': array(0.869518)}

Initial evaluation results:
{'Intercept': -2.14, 'X1': -2.68, 'X2': -2.44, 'X3': -3.13, 'X4': -2.82, 'X5': -2.48, 'Y_alpha': -1.48, 'Y': -inf}
```

Here's the description of my data:

<img width="309" alt="screenshot" src="https://user-images.githubusercontent.com/46363237/216802725-2d661b06-b23d-4e77-8800-26ae93a80739.png">

**Comment by zwelitunyiswa** [comment]
Maybe this is helpful? https://discourse.pymc.io/t/custom-zero-inflated-binomial-in-bambi/11209/5?u=zweli

**Comment by hyang57** [comment]
> Maybe this is helpful? https://discourse.pymc.io/t/custom-zero-inflated-binomial-in-bambi/11209/5?u=zweli

Thank you for your reply. I will carefully read the code and try to define my own distribution function.

**Comment by tomicapretto** [comment]
@hyang57 if you want to make sure that all the coefficients are positive, you can use bounded priors for those coefficients. You don't need to write custom code for this. One alternative would be to use a `HalfNormal` prior in all the cases. From the model summary above I see you're using `Normal` priors. 

On the other hand, the error you're getting is because the draw for the coefficients leads to an invalid value of the mean parameter in the Gamma distribution, and that's why it says "-Inf". You could change the link function (use a `'log'` function for example).

**Comment by hyang57** [comment]
> @hyang57 if you want to make sure that all the coefficients are positive, you can use bounded priors for those coefficients. You don't need to write custom code for this. One alternative would be to use a `HalfNormal` prior in all the cases. From the model summary above I see you're using `Normal` priors.
> 
> On the other hand, the error you're getting is because the draw for the coefficients leads to an invalid value of the mean parameter in the Gamma distribution, and that's why it says "-Inf". You could change the link function (use a `'log'` function for example).

Hi @tomicapretto, thank you for your reply and I think I've solved my problems. I appreciate your help!
