### ISSUE TITLE
Weights option

### ISSUE THREAD

**Issue by chakra1166** [bambinos/bambi#639]
In BRMS we can give differents weights to each sample as shown below:

`brm(
mvbind(stflife, happy)|weights(anweight) ~ 1 + (1|(cntry)),
        data = X, chains = 2, cores = 2, control = list(max_treedepth = 15))`

Is it possible to do the same in Bambi?

**Comment by tomicapretto** [comment]
It's not possible right now but it shouldn't be too difficult to add in the future. Right now we're concentrating on other features but it's likely we add support for weights soon.
