### ISSUE TITLE
Not consistent naming requirements in plot_cap

### ISSUE THREAD

**Issue by michaelraczycki** [bambinos/bambi#645]
While learning to use Bambi's plotting functionalities I've noticed that in plot_cap there's something either I can't understand, or is inconsistent. Screenshot below shows the model definition and the internal params:
![Zrzut ekranu 2023-02-25 o 16 54 02](https://user-images.githubusercontent.com/119355382/221366669-0102135e-fda5-47ed-9a59-c260e040856e.png)
and the dataset I'm interested in:
![Zrzut ekranu 2023-02-25 o 16 56 21](https://user-images.githubusercontent.com/119355382/221366728-30efb559-8894-48e7-ae58-cccdb52813fb.png)
As you can see, in the dataset both predictor variable (Length1) and the result variable (Weight) are without log(), it's defined like that later in the model.
idata obtained from model.fit() can be found below:
![Zrzut ekranu 2023-02-25 o 16 54 30](https://user-images.githubusercontent.com/119355382/221366827-70e5da26-5117-47b5-ad19-dc29b7fc4bb3.png)

So here comes the confusion:
![Zrzut ekranu 2023-02-25 o 16 54 11](https://user-images.githubusercontent.com/119355382/221366846-5704764e-b511-47ed-b331-8661a607e939.png)
If I can define 'Length1' as a covariate, why I need to refer to result (Weight) as log(Weight) in order to apply transformation to it?
In model definition both vars were defined as log(var) -> model = bmb.Model("log(Weight) ~ 1+ log(Length1)", data)
and in the dataset neither of them is already transformed to log scale. 
If I misunderstood something please help me understand it

**Comment by tomicapretto** [comment]
Sorry for the long delay!

The third argument, `covariates`, contains the **covariates** that will vary in the plot. On the other hand, `transforms`, contains how to transform **terms**. Why this difference is needed is more relevant when you have multiple terms affected by the same covariate. For example, in `log(y) ~ 1 + x + x:z`. When you do `covariates=["x"]`, the values of `x` will affect both `x` and `x:z`.

**Comment by tomicapretto** [comment]
I'm closing this as I consider it to be answered (and on top of that the interface also changed, we now have `bambi.interpret`). Feel free to reopen if it's not clear.
