### ISSUE TITLE
Plotly Backend for plot_cap()

### ISSUE THREAD

**Issue by hxk1633** [bambinos/bambi#649]
Hello,

I'd like to use the plotly back-end for plotting CAP graphs. Is there a way to do this without overhauling the entire code for creating the CAP graphs?

Thanks,
Harrison

**Comment by tomicapretto** [comment]
Hi! Thanks for opening the issue!

Currently it's not possible. You would have to write your own plotly code. I recommend you to use the `create_cap_data` function defined here https://github.com/bambinos/bambi/blob/ce7b0605d5e0df552538e1aa170e1dd0eca4e0a7/bambi/plots/plot_cap.py#L21 to save some work.
