### ISSUE TITLE
Add Bill's HSGP talk to the example notebooks

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#650]
The talk is not available on YouTube yet. Once the video is there, we can link it in our HSGP example notebooks.

**Comment by SuryaMudimi** [comment]
Here is the link to that talk right ?
https://www.youtube.com/watch?v=ri5sJAdcYHk

**Comment by 5hv5hvnk** [comment]
@SuryaMudimi Yes I think that's the one @tomicapretto  is referring to

**Comment by tomicapretto** [comment]
exactly!

**Comment by 5hv5hvnk** [comment]
We just need to add them to `notebooks/hsgp_1d.ipynb` and `notebooks/hsgp_1d.ipynb` right?

**Comment by tomicapretto** [comment]
You mean `hsgp_1d` and `hsgp_2d`? Yes, that's the case :)
