### ISSUE TITLE
How to give custom truncated distribution as prior

### ISSUE THREAD

**Issue by SuryaMudimi** [bambinos/bambi#652]
`pm.TruncatedNormal` is available, But how to give `Truncated` `Cauchy` or `Laplace`

https://www.pymc.io/projects/docs/en/latest/api/distributions/generated/pymc.Truncated.html

**Comment by tomicapretto** [comment]
`pm.Truncated` is not a distribution itself, it's some kind of transformation that takes a distribution and gives a truncated version of it. 

If you want to use a PyMC distribution as a Prior, `bmb.Prior("DistributionName", param1=value1, param2=value2) should work. 

If not, you can pass a function that returns a custom prior. For example

```python
def CustomPrior(name, *args, dims=None, **kwargs):
    return pm.Normal(name, *args, dims=dims, **kwargs)

data = load_data("my_data")

priors = {"x": Prior("CustomPrior", mu=0, sigma=5, dist=CustomPrior)}
model = Model("y ~ x", data, priors=priors)
```

Inside `CustomPrior` you can do whatever you want

**Comment by SuryaMudimi** [comment]
I could not find this documentation. I think it would be better if its mentioned, Should I add and raise a PR ? either in FAQ or as a subsection in https://bambinos.github.io/bambi/notebooks/getting_started.html#Specifying-priors

**Comment by tomicapretto** [comment]
@SuryaMudimi that would be awesome. I think it could either be something in the Specifying priors section, or something in the FAQ. PR more than welcomed :)
