### ISSUE TITLE
Use `import bambi as bmb` in tests

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#653]
I don't know why we are importing specific objects only. Tests don't look like regular Bambi code because of this.

**Comment by YuvrajSinghJadon** [comment]
i would like to work on this issue.

# I have to ** import bambi as bmb ** in all test files right?

**Comment by tomicapretto** [comment]
Hi @YuvrajSinghJadon!

It's a little more than that. We need to import bambi as bmb, as well as replace all the imporst that could be replaced. Also, we need to do changes like `Model(...)` --> `bmb.Model(...)`
