### ISSUE TITLE
Minor plotting error in `plot_cap`

### ISSUE THREAD

**Issue by drbenvincent** [bambinos/bambi#685]
Working with a toy dataset I notice that I get a great plot from `plot_cap`. This is from the model `y ~ 0 + C(group)`. Note how the line colour and shading colour match up.
![Screenshot 2023-06-18 at 09 43 37](https://github.com/bambinos/bambi/assets/6765047/ad45e5f7-7fe9-4b3a-b08b-4793134a8490)

But there seems to be an issue in an example with the model `y ~ 1`. Now, the line colour and fill colour no longer match up
![Screenshot 2023-06-18 at 09 44 19](https://github.com/bambinos/bambi/assets/6765047/51238c2c-87ae-4c8b-8b96-7499e64223bf)

Data was generated with:
```python
groups = 3
samples_per_group = 10
N = groups * samples_per_group
x = np.tile(np.linspace(0, 10, samples_per_group), groups)
group = np.repeat(np.arange(groups), samples_per_group)
y = 2 + -0.5 * group + rng.normal(0, 0.1, N)
df = pd.DataFrame({"x": x, "group": group, "y": y})
```

**Comment by tjburch** [comment]
Was trying to dig into this but am unable to personally reproduce. Using the current version on pip (0.12.0), I get the following, which looks as expected:

![plot_cap_bug](https://github.com/bambinos/bambi/assets/16945590/5a24a3ea-fb4e-4e35-a8da-df7ae0106820)

However looking back at the commit history, it's not clear to me that there were any updates in version 0.12.0 since this bug was submitted. @drbenvincent - is this still happening? Which version are you using?

(For completeness, here's what I ran, just in ipython)

```
In [1]: groups = 3
   ...: samples_per_group = 10
   ...: N = groups * samples_per_group
   ...: x = np.tile(np.linspace(0, 10, samples_per_group), groups)
   ...: group = np.repeat(np.arange(groups), samples_per_group)
   ...: y = 2 + -0.5 * group + rng.normal(0, 0.1, N)
   ...: df = pd.DataFrame({"x": x, "group": group, "y": y})
   ...:
   ...: model2 = bmb.Model("y ~ 1", df)
   ...: results2 = model2.fit()
   ...: ax = sns.scatterplot(df, x="x", y="y", hue="group")
   ...: plot_cap(model2, results2, ["x", "group"], ax=ax)
   ...: plt.show()
   
In [2]: bmb.__version__
Out[2]: '0.12.0'
```
   
Since there was a pretty heavy update of plots/plotting.py I'll also note that it still works on the dev version right now.

**Comment by drbenvincent** [comment]
Hi @tjburch. Thanks for looking into it.

The error does not happen when you fit with `y ~ 1` and then call `plot_cap(model2, results2, ["x", "group"], ax=ax)`. Though this is a strange thing to do because there is no `group` variable.

The error happens when you fit with `y ~ 1` and then call `plot_cap(model2, results2, "x", ax=ax)`.

Full MWE:

```python
import numpy as np
import pandas as pd
import bambi as bmb
from bambi.plots import plot_cap
import seaborn as sns
import matplotlib.pyplot as plt

RANDOM_SEED = 1234
rng = np.random.default_rng(RANDOM_SEED)

groups = 3
samples_per_group = 10
N = groups * samples_per_group
x = np.tile(np.linspace(0, 10, samples_per_group), groups)
group = np.repeat(np.arange(groups), samples_per_group)
y = 2 + -0.5 * group + rng.normal(0, 0.1, N)
df = pd.DataFrame({"x": x, "group": group, "y": y})

model2 = bmb.Model("y ~ 1", df)
results2 = model2.fit()
ax = sns.scatterplot(df, x="x", y="y", hue="group")
plot_cap(model2, results2, "x", ax=ax)
plt.show()
```

And this is with '0.12.0'.

**Comment by tjburch** [comment]
Whoops, sorry about the oversight there. Just created #698 to resolve.
