### ISSUE TITLE
Add ability to add interactions

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#7]
Currently there's no way to add interaction terms to models; users have to take the products of columns by hands (and this is much too cumbersome in the case of categoricals). We should extend the API to handle this via, e.g., an add_interaction() method that takes a list of names of existing Terms as its main argument. It should also, by default, create terms for main effects if they don't already exist (though this will only make sense if the user wants the same priors applied to all generated terms).

**Comment by tyarkoni** [comment]
Downgrading priority on this one, and may close it altogether, as it's not clear that this is a pressing need.

**Comment by twiecki** [comment]
Doesn't `patsy` give you that for free?

**Comment by tyarkoni** [comment]
If you use the formula interface, yes, but the thought was to also add the ability to add interactions via `add_term` calls, which are post-patsy (i.e., the formula interface basically wraps `add_term`). But since there's rarely a reason not to use formulas, and users can easily create interaction variables outside Bambi (e.g., by concatenating two string columns) and then pass them in as-is, this seems kind of unnecessary.

**Comment by jake-westfall** [comment]
Going to go ahead and close this one, given the discussion above.
