### ISSUE TITLE
Error setting priors

### ISSUE THREAD

**Issue by lucamagnasco** [bambinos/bambi#711]
Hi! I have two doubts that would be awesome if someone can help me:

1. **I have an issue specifying the priors. In my case i want to use a negative half normal for elasticity prior, but i have the following error:**
ValueError: Trying to set hyperprior on 'price'. Can't set a hyperprior on common effects.

2. Doesn't seem to use the prior of "x" for the interaction term "x:z". is that the case?

**Code:**
```
import bambi as bmb
from bambi.priors import Prior

class NegativeHalfNormalPrior(Prior):
    def __init__(self, mu=1, beta=1, *args, **kwargs):
        super().__init__("HalfNormal", sd=beta, *args, **kwargs)
        self.mu = mu  # Mean
        self.sd = beta  # Standard deviation
        self.transform = -1  # Apply a negative transformation
priors = {
    'price': NegativeHalfNormalPrior(mu=1, beta=bmb.Prior("Normal", beta=0.5))
}

formula = 'quantity ~  price  + price : C(product) + C(day_name) + year + week_of_year'
model = bmb.Model(formula, data=subset_data, family='poisson', priors=priors)
model.build()
```

**Comment by tomicapretto** [comment]
I'm not 100% sure I understand what you want to do. You have a regression where `price` is one of the predictors, and you want to make sure that the slope for `price` is negative so you try to put a negative half-normal distribution on it. Is that correct? 

The second thing I see is that you're trying to put a hyperprior for `mu`, the mean of the `price` coefficient. In Bambi, this is known as a common effect (or fixed effect in classic notation). If you want to use a hierarchical term you need a different syntax .

Regarding the first problem, I've never seen a negative half-normal distribution and that's something you would need to build yourself. Maybe, you can create a variable that is the negative of the price and then you put a half-normal prior on that?
