### ISSUE TITLE
Drop support for Python 3.8

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#713]
Right now our tests run on 3.8, 3.9, and 3.10. They should run on 3.9, 3.10, and 3.11.

**Comment by 5hv5hvnk** [comment]
We just need a small edit [here](https://github.com/bambinos/bambi/blob/ae00f268b63bb2043747d2b55e29af901bdb0643/.github/workflows/test.yml#L14) right?

**Comment by tomicapretto** [comment]
@5hv5hvnk yes! And also this line https://github.com/bambinos/bambi/blob/ae00f268b63bb2043747d2b55e29af901bdb0643/pyproject.toml#L70

**Comment by tomicapretto** [comment]
Hi @5hv5hvnk I'm doing this in #720 because my CI was broken since one of the libraries we use to build the docs doesn't support Python 3.8 anymore
