### ISSUE TITLE
Adding Mister P Docs

### ISSUE THREAD

**Issue by NathanielF** [bambinos/bambi#715]
I have an open ticket on the pymc examples page to demonstrate the technique of Multilevel Regression and post stratification, but while working on this I found that it's much simpler and probably recommended to implement in Bambi. 

I can add an example documented here if you think that would fit?

**Comment by zwelitunyiswa** [comment]
@NathanielF this might be a good guide

**Comment by NathanielF** [comment]
Added a draft PR here: https://github.com/bambinos/bambi/pull/716

I tried using those new functions but they broke for me with my Mr P model. Aside from that i think i have everything in there i wanted to say, but would appreciate any feedback you might have.

**Comment by GStechschulte** [comment]
> Added a draft PR here: #716
> 
> I tried using those new functions but they broke for me with my Mr P model. Aside from that i think i have everything in there i wanted to say, but would appreciate any feedback you might have.

These issues are being resolved in PR #721

**Comment by tomicapretto** [comment]
Closed since #716
