### ISSUE TITLE
Log compilation/sampling time

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#72]
One of the benefits of having interfaces to multiple sampling packages is that we can compare the results both in terms of estimates and performance. It would probably make sense to add some basic features to the `MCMCResults` class that report on time taken to compile the model and run the sampler; that way we can eventually build towards a helper function like `compare_backends` that takes an unfitted `Model` and a list of backend names as input, and returns results for all backends plus some comparative output.

**Comment by aloctavodia** [comment]
Closing as for the moment we have only one backend. Also sampling time is stored in the InferenceData object
