### ISSUE TITLE
interpret.plot_slopes ignores prob argument and az.rcParams['stats.hdi_prob' : ...]

### ISSUE THREAD

**Issue by jt-lab** [bambinos/bambi#748]
@GStechschulte, we noticed that plot_slope seems to ignore the hdi prob arguments. We noticed it due to mismatches between the plot and the tabulated results. Neither changing the prob argument not the az rcParams seems to have an effect:

```
fig, ax = bmb.interpret.plot_slopes(
    model=model,
    idata=idata,
    wrt="factor2",
    average_by=["factor3", "factor1"],
    subplot_kwargs={"main": "factor3", "panel": "factor1"},
    fig_kwargs={"figsize": (16, 4), "sharey": True},
    legend=False,
    eps = 1,
    prob = 0.90
)

fig, ax = bmb.interpret.plot_slopes(
    model=model,
    idata=idata,
    wrt="factor2",
    average_by=["factor3", "factor1"],
    subplot_kwargs={"main": "factor3", "panel": "factor1"},
    fig_kwargs={"figsize": (16, 4), "sharey": True},
    legend=False,
    eps = 1,
    prob = 0.99
)

import arviz as az
az.rcParams["stats.hdi_prob"] = 0.999

fig, ax = bmb.interpret.plot_slopes(
    model=model,
    idata=idata,
    wrt="factor2",
    average_by=["factor3", "factor1"],
    subplot_kwargs={"main": "factor3", "panel": "factor1"},
    fig_kwargs={"figsize": (16, 4), "sharey": True},
    legend=False,
    eps = 1
)
```
These plots should be different:
![image](https://github.com/bambinos/bambi/assets/16053195/3a2c4bfe-9f49-4c24-86d1-eee1f76aca4c)

Code to reproduce the observation
```
import pandas as pd
import bambi as bmb
from matplotlib.pylab import plt

df = pd.read_csv('simulated-data.csv')

model = bmb.Model('p(correct, count) ~ factor1*factor2*factor3 + (factor3+factor2|individual)',
                  df, family='binomial')
idata = model.fit(tune=500, draws=1000, target_accept=0.7, init='adapt_diag')
```
(and the the above plotting code)

Dataset:
[simulated-data.csv](https://github.com/bambinos/bambi/files/13237636/simulated-data.csv)

Also found a little type in the doc string: ``az.rcParam["stats.hdi_prob"]`` --> ``az.rcParams["stats.hdi_prob"]``

As always, many thanks in advance!

**Comment by GStechschulte** [comment]
@jt-lab Again, thanks for raising the issue and providing the code. Indeed, this is a bug. This is because the `probs` variable in `def slopes()` was never passed to the method `.get_estimate()` and thus `probs` defaulted to 0.94. After passing `probs`, I get the following plots:

```python3
fig, ax = bmb.interpret.plot_slopes(
    model=model,
    idata=idata,
    wrt="factor2",
    average_by=["factor3", "factor1"],
    subplot_kwargs={"main": "factor3", "panel": "factor1"},
    fig_kwargs={"figsize": (16, 4), "sharey": True},
    legend=False,
    eps = 1,
    prob = 0.90
)

fig, ax = bmb.interpret.plot_slopes(
    model=model,
    idata=idata,
    wrt="factor2",
    average_by=["factor3", "factor1"],
    subplot_kwargs={"main": "factor3", "panel": "factor1"},
    fig_kwargs={"figsize": (16, 4), "sharey": True},
    legend=False,
    eps = 1,
    prob = 0.99
)

import arviz as az
az.rcParams["stats.hdi_prob"] = 0.999

fig, ax = bmb.interpret.plot_slopes(
    model=model,
    idata=idata,
    wrt="factor2",
    average_by=["factor3", "factor1"],
    subplot_kwargs={"main": "factor3", "panel": "factor1"},
    fig_kwargs={"figsize": (16, 4), "sharey": True},
    legend=False,
    eps = 1
)
```
![image](https://github.com/bambinos/bambi/assets/63432018/3368fb0a-898e-4203-86fc-06f7832c6368)
![image](https://github.com/bambinos/bambi/assets/63432018/031f3482-a0db-4eb5-8aa3-cd7f2c9d7af4)
![image](https://github.com/bambinos/bambi/assets/63432018/0d54a69c-fe2c-4ae5-8e5c-5a83be3f2388)

**Comment by jt-lab** [comment]
Many thanks for update & looking into this!

**Comment by GStechschulte** [comment]
> Many thanks for update & looking into this!

PR has been opened!
