### ISSUE TITLE
Bambi Returning wrong values for simple binomial model

### ISSUE THREAD

**Issue by canyon289** [bambinos/bambi#756]
Bambi seems to be returning values that are incorrect from a simplistic dataset and model. Are folks seeing the same issue that I am?

```
# Generate two random groups
p_a, samples_a = .6, 10000
p_b, samples_b = .7, 10000


df_a = pd.DataFrame({"samples": stats.bernoulli(p=p_a).rvs(samples_a)}).assign(group="A")
df_b = pd.DataFrame({"samples": stats.bernoulli(p=p_b).rvs(samples_b)}).assign(group="B")

df = pd.concat([df_a, df_b])#.groupby("group").agg({len, sum})

model = bmb.Model("samples ~ 0 + group", data=df, family="bernoulli")
ab_test = model.fit()
az.plot_posterior(ab_test);
```

<img width="371" alt="image" src="https://github.com/bambinos/bambi/assets/7213793/e26f2dcc-0c6f-425a-8741-79ad68ec4082">

<img width="1130" alt="image" src="https://github.com/bambinos/bambi/assets/7213793/051190ae-a5ea-4de0-8239-66553e4819dd">

<img width="1087" alt="image" src="https://github.com/bambinos/bambi/assets/7213793/7fceece0-92cb-4800-ba41-1a9cfd968a8e">

**Comment by canyon289** [comment]
PyMC gets the right values
```
with pm.Model() as model:
    p = pm.Beta("p", 2, 2, shape=2)
    obs = pm.Bernoulli("obs", p=p[idx.codes], observed = df["samples"])
    idata = pm.sample()
```
<img width="1088" alt="image" src="https://github.com/bambinos/bambi/assets/7213793/1f85e0fe-336d-4e72-a7fe-0abe1a10db9c">

**Comment by tomicapretto** [comment]
This is because you're visualizing the regression coefficients, while what you want are the success probabilities. You need the inverse link function:

```python
from scipy.special import expit
az.plot_posterior(expit(ab_test.posterior))
```

and you get the plot you want

**Comment by canyon289** [comment]
:facepalm:
