### ISSUE TITLE
Custom link function

### ISSUE THREAD

**Issue by zaizibai** [bambinos/bambi#771]
Dear bambi developers,

I am wondering is it possible to use a custom link function? Since link function like exp or log or squared, they all have a nonlinear mapping. Function like softplus: log(1+exp(x)) is widely used in deep learning model. When x>0, the mapping between x and output is linear. 

Best,
mqguo

**Comment by tomicapretto** [comment]
Hi @zaizibai, yes this is possible. Have a look at the documentation here https://bambinos.github.io/bambi/api/Link.html
and the test here https://github.com/bambinos/bambi/blob/1a3cf8ad49add076c7daea6c29e7b09a267f2cb7/tests/test_priors.py#L153-L169.

We probably need a better example though

**Comment by tomicapretto** [comment]
@zaizibai feel free to re-open if you think the question is not answered :)
