### ISSUE TITLE
Example "Hierarchical Logistic regression with Binomial family" not working

### ISSUE THREAD

**Issue by jsevo** [bambinos/bambi#784]
Following the example:

https://bambinos.github.io/bambi/notebooks/hierarchical_binomial_bambi.html

leads to an error message:

```
in ....site-packages/formulae/terms/call_resolver.py:272, in LazyCall.eval(self, data_mask, env)
    269 args = [arg.eval(data_mask, env) for arg in self.args]
    270 kwargs = {name: arg.eval(data_mask, env) for name, arg in self.kwargs.items()}
--> 272 return callee(*args, **kwargs)

```

Code to reproduce:

```
import bambi as bmb
df = bmb.load_data("batting")

# Then clean some of the data
df["AB"] = df["AB"].replace(0, np.nan)
df = df.dropna()
df["batting_avg"] = df["H"] / df["AB"]
df = df[df["yearID"] >= 2016]
df = df.iloc[0:15] 

model_non_hierarchical = bmb.Model("p(H, AB) ~ 0 + playerID", df, family="binomial")
model_non_hierarchical
```

`

**Comment by jsevo** [comment]
UPDATE:

This issue arises from the usage of `p(H, AB)`, replacing this alias with `proportion(H, AB)` in the formula solved it.

**Comment by tomicapretto** [comment]
Hi @jsevo, thanks for letting us know about this. It should work if you use the latest release of formule (0.5.3), the library we use to parse model formulas (you can do `pip install formulae --upgrade`)

**Comment by tomicapretto** [comment]
Feel free to re-open if you still see the problem :)
