### ISSUE TITLE
No likelihood for Ordinal model

### ISSUE THREAD

**Issue by zaizibai** [bambinos/bambi#789]
Hi devs, thanks for making bambi this wonderful software. I noticed that ordinal regression was introduced after 0.12.0 bambi. I tried the cumulative model in bambi, but when i tried to do the model comparison, I found that returned xarray file does not include the log-likelihood estimation so that there is no way to do model comparison for cumulative ordinal model? Thanks a lot!

**Comment by GStechschulte** [comment]
Hey @zaizibai thanks for raising the issue. When doing `model.fit(...)` are you passing the following kwargs `model.fit(..., idata_kwargs = {"log_likelihood": True})`?

**Comment by GStechschulte** [comment]
Hey @zaizibai did this resolve your problem? Cheers!

**Comment by tomicapretto** [comment]
Feel free to re-open if the suggested approach doesn't work :)
