### ISSUE TITLE
Notation of random

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [bambinos/bambi#79]
Congrats to the authors for this great package!

Looking at the first example in the documentation, where can I read more about what `random` 
in this expression `random=['condition|subject', '1|stimulus']` means and this syntax?

``` python
from bambi import Model

# Assume we already have our data loaded
model = Model(data)
results = model.fit('rt ~ condition', random=['condition|subject', '1|stimulus'], samples=5000)
results.plot(burn_in=1000)
results.summary(1000)
```

**Comment by tyarkoni** [comment]
By convention, the `|` is a grouping operator. In the above example, `condition|subject` means that a separate set of subject effects is being estimated for each (dummy-coded) level of the `condition` factor; the `1|stimulus` means we want a random intercept parameter for each stimulus. You can search for documentation on some of the R packages (e.g., lmer) for a much more detailed explanation. I'm closing this issue though, as it isn't specific to this package. An explanation of the distinction between fixed and random effects is also beyond the scope of the README, but there are plenty of resources on the web for that.

**Comment by amelio-vazquez-reina** [comment]
Thank you, very helpful. On a somewhat unrelated note, looking at the README I see every example makes a reference to `data` as if it had been already loaded, as well as specific columns that are assumed to be part of the data. Any advice on how to get data with the columns used in the examples?

**Comment by tyarkoni** [comment]
I suggest working with the notebooks in the `examples/` folder, as those have bundled data.
