### ISSUE TITLE
Release after pymc 5.13.1

### ISSUE THREAD

**Issue by ferrine** [bambinos/bambi#805]
Hi, @tomicapretto, here is the PR that is going to happen soon, but it can break the existing bambi release in nixpkgs. Is a release coming soon?

https://github.com/NixOS/nixpkgs/pull/296665#issuecomment-2058580372

**Comment by tomicapretto** [comment]
Yes. How urgent is it? We could cut a release now. But ideally I would want to have https://github.com/bambinos/bambi/pull/804 merged, which requires solving this https://github.com/pymc-devs/pymc/issues/7258

**Comment by ferrine** [comment]
it is not urgent, I can proceed there after you finish

**Comment by danieltomasz** [comment]
Hi, https://github.com/bambinos/bambi/pull/804 is merged, will be there a new release soon?  
I am starting a new project using bambi and I don't know if I should stick to old version or try to use the dev version (the new version change syntax in some examples which I am using)

**Comment by tomicapretto** [comment]
@danieltomasz @GStechschulte we have Bambi 0.14.0 now, please let us know if you have any trouble with it :)
