### ISSUE TITLE
Better docs

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#81]
With the upcoming major release, the package is now probably feature-rich enough that it makes sense to start thinking about moving to full-featured documentation using sphinx and/or readthedocs.

**Comment by ejolly** [comment]
Hey guys I was playing with Bambi this weekend and just made some *really* simple sphinx documentation based on your existing docstrings so I could more easily mess around with stuff (pull request sent). Hopefully that's helpful in getting this started!

**Comment by tyarkoni** [comment]
This is awesome, thanks Eshin! Taking a look right now, will probably merge shortly.

**Comment by camenpihor** [comment]
On it!
