### ISSUE TITLE
Broken link in 1D HGSP example

### ISSUE THREAD

**Issue by wd60622** [bambinos/bambi#814]
In the documentation page for [hsgp_1d](
https://bambinos.github.io/bambi/notebooks/hsgp_1d.html), there is a broken link for [transformation.py](https://bambinos.github.io/bambi/notebooks/bambi/transformations.py) in [this section](https://bambinos.github.io/bambi/notebooks/hsgp_1d.html#how-does-hsgp-work)

**Comment by tomicapretto** [comment]
Thanks! I modified it in #804
