### ISSUE TITLE
MCMCResults --> MultiTrace

### ISSUE THREAD

**Issue by tyarkoni** [bambinos/bambi#82]
The move away from PyMC's `MultiTrace` to a generic `MCMCResults` class makes sense given our goal of being backend-independent, but since PyMC is likely to have much better support for summarizing/plotting results for the foreseeable future, it would be good to add a `to_multitrace` method on the `MCMCResults` class that allows users to easily take advantage of all the functionality in PyMC. For the `PyMC3BackEnd` we can just cheat and return the `MultiTrace` directly. (We don't need to go overboard, since some of the `MultiTrace` attributes are pretty hard to set without the model context, but the basic stuff should be fairly easy to get right, since we've done it before).

@twiecki, do you think there would be any appetite among the PyMC3 devs for trying to more cleanly separate the `MultiTrace` class from the PyMC model stack that generated it? I'm guessing not, as it's not really clear what the benefit would be for your guys... but if there were interest in such a thing, we would seriously consider redirecting part of our efforts to making those changes in PyMC itself, and then we could just reuse the generic `MultiTrace` class for our other `BackEnd` objects in Bambi.

**Comment by twiecki** [comment]
@tyarkoni We would definitely consider such a PR. It does seem like a cleaner abstraction and if it's useful to you I'd support it. Main question is added code complexity.

**Comment by aloctavodia** [comment]
It seems this is another area where ArviZ can help.

**Comment by tyarkoni** [comment]
@aloctavodia totally agree! On an initial cursory look at what's in ArviZ, it looks like we can probably get rid of just about everything currently in `MCMCResults`, with the exception of some object references (most importantly, to the original bambi `Model`) and metadata. But it seems very reasonable to turn this into just a thin wrapper around an xarray `Dataset` returned by ArviZ.

One thing I haven't thought through is whether ArviZ's converters are sufficient to replace all of the standardization we currently do. @ahartikainen, does ArviZ impose its own standardized naming conventions, or does it pretty much only care about standardizing the data? One issue for us is that the names/terms produced in plots etc. have to align with what's in the bambi `Model`, and if I recall correctly, there's a bunch of hacky but necessary code in there right now that works around nomenclature differences between PyMC3 and Stan. I suppose in the worst case, it would still be much cleaner to just write a set of postprocessors (one per backend) that standardize names in the `Dataset`.

**Comment by ahartikainen** [comment]
ArviZ inference data keeps parameters in nD structure (chain x draw x *shape) (scalar values are chain x draw).

We expect that sample_params are without trailing _ (`energy` for plots and stats), `divergent` --> `diverging` (for plots) for stan and elementwise log_likelihood is kept under sample_params (for loo + compare).

But really there is no restriction, all of this just convention.

**Comment by ahartikainen** [comment]
Also there is a possibility to add more material to InferenceData object / Group (xarray.Dataset), we have just implemented the main parts.
