### ISSUE TITLE
Fix math in negative binomial example

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#835]
The following is not precise as it's not as the two things are not equal (the thing on the right is g(mu)).

![image](https://github.com/user-attachments/assets/5f4a1894-4008-4f16-a234-9cfdf2fa201e)

https://bambinos.github.io/bambi/notebooks/negative_binomial.html

**Comment by CodingWithError** [comment]
can you provide me some more details what are the changes you want in that.

**Comment by HarshvirSandhu** [comment]
Hi @tomicapretto 
I would like to work on this issue

**Comment by tomicapretto** [comment]
Hi @CodingWithError @HarshvirSandhu, sorry for the lack of response. 

The problem in that math is that it says the logarithm of the response variable (Y) is equal to the linear predictor. However, what's equal to the linear predictor is the logarithm of the expected value of Y.

$$
\log(\mathbb{E}(Y_i)) = \log(\mu_i) = \beta_1 \text{Academic}_i + \dots
$$

**Comment by tanishy7777** [comment]
Hey, I have made a PR for this issue. I hope it solves the problem. Please let me know if I need to add any more changes regarding this issue @tomicapretto
