### ISSUE TITLE
Intercept, treatment and sd

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [bambinos/bambi#84]
Consider the following simple data:
```
   treatment  flight_uid        CPA
0    control  0F0NyaEZ0I -91.912057
1    control  0F2QJqI6aG  22.596265
2    control  0F41vqNS98 -19.187072
3    control  0F4C34cVsi  -1.983102
4    control  0F4VfWQiwq  15.392051
...
53   exposed  0FwCdqHGJ1  28.934246
54   exposed  0FyEmF4PTx   6.787299
55   exposed  0FynOY4NKz  27.081798
56   exposed  0FzDoxRHho -33.652136
57   exposed  0FzWV6jZnV -47.540311
```

When I run:

``` python
model = Model(test)
results = model.fit('CPA ~ treatment')
results.plot(500)
```

I get the following results:

<img width="1187" alt="screen shot 2017-03-30 at 4 47 14 pm" src="https://cloud.githubusercontent.com/assets/1993919/24525517/907a030e-1568-11e7-9717-2abc1b00ed7c.png">

My assumption is that we fit the following regression model:

```
CPA = coefficient * treatment + intercept + error
```
Is that correct? 
* If so, what **encoding** did it use? (i.e. which treatment is encoded as "1" and which one as "0"?)
* Also, what's the meaning of the letter **`b`** in **`b_Intercept`** and in **`b_treatment`**?

**Comment by tyarkoni** [comment]
Yes, that's right. In the above, `b_treatment` is the treatment parameter and `b_intercept` is the intercept parameter. `CPA_sd` is the model error.

The treatment is most likely coded alphabetically, but you can check patsy's documentation to make sure (or inspect the internal data representation by looking at `model.terms['treatment'].data`). If you want to be sure it's coded the way you want, I'd suggest coding it yourself prior to feeding the data in.

The `b` and `u` prefixes are included to indicate fixed and random effects, by convention. But they're going to disappear in the next major release (coming in the next few days), in favor of the `|` operator to distinguish fixed vs. random effects. So you can safely ignore them.

**Comment by amelio-vazquez-reina** [comment]
Phenomenal. Thank you @tyarkoni !

**Comment by amelio-vazquez-reina** [comment]
On this note, what are the default priors here? (for the intercept and the slope). I read the following in the documentation:

> By default, Bambi will intelligently generate weakly informative priors for all model terms, by loosely scaling them to the observed data. While the default priors will behave well in most typical settings, there are many cases where an analyst will want to specify their own priors--and in general, when informative priors are available, it's a good idea to use them.

Any way to inspect what prior is used?

**Comment by tyarkoni** [comment]
You can inspect the priors in, e.g., `model.terms['term_name'].prior` (though you'll probably need to look at the `.args` attribute). You can also try calling `.plot()` on the model. I'm not sure if that works in the current master (I think it should), but if not, it will work in the next few days once the [Stan](https://github.com/bambinos/bambi/tree/stan/bambi) branch is merged.
