### ISSUE TITLE
Investigate and fix our failing CI

### ISSUE THREAD

**Issue by tomicapretto** [bambinos/bambi#840]
See for example https://github.com/bambinos/bambi/actions/runs/10722117848/job/29732285418

There's something happening when bambi tries to download data for the tests.

**Comment by GStechschulte** [comment]
Looks like this issue has been fixed? (based on seeing our CI is passing?)

**Comment by tomicapretto** [comment]
Yes, this particular issue is fixed I think. We may still have problems due to bayeux and related dependencies.. I'm gonna close this one.
