### ISSUE TITLE
"Getting started" page lists compound distributions as "To be added"

### ISSUE THREAD

**Issue by j0ma** [bambinos/bambi#848]
It seems like the the ["Getting started" page](https://bambinos.github.io/bambi/notebooks/getting_started.html#families) still lists the Beta-Binomial and Dirichlet-Multinomial as "To be added" even though they seem to have been implemented in #659 . Happy to submit a PR to fix this. :)

![image](https://github.com/user-attachments/assets/81b64a9a-920b-40b2-922d-0f181275ffc2)

**Comment by j0ma** [comment]
Ah nvm, they seem to link to example notebooks. My bad, didn't read it properly earlier.

**Comment by tomicapretto** [comment]
No problem!
