### ISSUE TITLE
I cannot set priors on auxillary parameters in distributional regressions

### ISSUE THREAD

**Issue by zwelitunyiswa** [bambinos/bambi#854]
Thanks for the ongoing work on this great package. My issue is that I cannot set priors on auxillary parameters in distributional regressions.

For example, I am using a beta_binomial likelihood, and my prior for mu is recognized, by my priors for kappa are ignored:

<img width="949" alt="Screenshot 2024-11-06 at 6 00 36 AM" src="https://github.com/user-attachments/assets/f39fbe16-ddbb-457e-a8ce-113a55e01d43">

Same thing when I change the formula for kappa:

<img width="984" alt="Screenshot 2024-11-06 at 6 03 24 AM" src="https://github.com/user-attachments/assets/95202f5b-5384-4aeb-b793-0d4261680fee">

I have had issues when I have tried other distributions as well.

**Comment by tomicapretto** [comment]
I think you need a nested dictionary, like 

```python
priors = {
    "mu": {"1|snf_id": bmb.Prior(...)},
    "kappa":  {"Intercept": bmb.Prior(...), "snf_id": bmb.Prior(...)}.
}
```

Let me know if that doesnt work and I can double check

**Comment by zwelitunyiswa** [comment]
Perfect. That works! Thank you.
