### ISSUE TITLE
Errors in example notebooks

### ISSUE THREAD

**Issue by arokem** [bambinos/bambi#87]
Hi - seems like the error reported in #78 is indeed gone. Thanks! 

Instead, there are now two other errors (using `master`): 

1. `model.fit` (in cell 5) does not have a key-word argument `chains`, leading to an error at that point.

2. Assuming you have over-come that error (e.g., by removing that key-word argument), the resulting`fitted` object now doesn't have a `to_df` method (needed 6 cells further down). 

LMK if these are just experiments, that you don't intend for people to use with current master, and I will stop reporting these.

**Comment by arokem** [comment]
This might come in handy, if you want to test these notebooks in your CI: 

https://github.com/computationalmodelling/nbval

**Comment by tyarkoni** [comment]
Did you make sure to update the whole package (PyPI should be fine), and not just the notebook? There are major changes in 0.1.0, and they should solve both of those issues. If they don't, let us know and we'll explore further.

**Comment by arokem** [comment]
Sorry about the noise. It works as expected. I must've been running some stale installation of this. Thanks!

**Comment by tyarkoni** [comment]
No worries, and thanks for the nbval tip, that's definitely something that will help us out!
