### ISSUE TITLE
Interpretation of the new notation in the output

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [bambinos/bambi#90]
I have a dataset that looks like the one below. CPA is an observed result from an experiment (treatment) on different flights, where a given campaign can contain multiple flights.

      campaign_uid  flight_uid treatment         CPA
    0   0C2o4hHDSN  0FBU5oULvg   control  -50.757370
    1   0C2o4hHDSN  0FhOqhtsl9   control   10.963426
    2   0C2o4hHDSN  0FwPGelRRX   exposed  -72.868952
    3   0C5F8ZNKxc  0F0bYuxlmR   control   13.356081
    4   0C5F8ZNKxc  0F2ESwZY22   control  141.030900
    5   0C5F8ZNKxc  0F5rfAOVuO   exposed   11.200450
    6   0C5F8ZNKxc  0F7eEd1BZn   control   -8.058984

I fit a model like the following one:

    model.fit('CPA ~ treatment',  random=['1|campaign_uid'])

To my knowledge, this model simply says:
* We have a slope for treatment
* We have a global intercept
* We also have an intercept per campaign

so one would just get **one** **posterior** for **each such variable**.

However, looking at the results below, I also get posteriors for the following variables:

* `1|campaign_uid_offset`
* `1|campaign_uid`
* `1|campaign_uid_sd`
* `CPA_sd`

What exactly do these variables represent?  What I am missing in my understanding of the model?

[![enter image description here][1]][1]

PS: I have this question also in [SE.CV](http://stats.stackexchange.com/q/272490/2798), so happy to close it here if we think that's a better forum for these types of questions.

  [1]: https://i.stack.imgur.com/73d9m.png

**Comment by jake-westfall** [comment]
Posting these questions on StackExchange is definitely good, but CrossValidated is not the appropriate SE forum for questions that are purely about software, even if it's statistical software (hence why the question just got closed there). If you repost the question on StackOverflow and post the link here, I'll answer it there.

**Comment by jake-westfall** [comment]
BTW, please also include the exact commands that you used to produce the output that you posted.

**Comment by amelio-vazquez-reina** [comment]
Thanks @jake-westfall I left the SE.SO question with the code [here](http://stackoverflow.com/questions/43294508/interpretation-of-bambi-variables-in-multi-level-regression-with-random-effects). Please let me know if there is anything else I can provide.
