### ISSUE TITLE
Default, auto_scaled priors differ between python2 vs. python3?

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#94]
Based on my admittedly brief examination of two whole test cases (from `bambi/tests/test_priors.py::test_update_term_priors_after_init`), it appears that the default, auto_scaled priors are non-trivially different between python2 and python3 in at least some cases. In the two test cases I examined, the python3 priors were about 13% wider and 44% wider than the python2 priors.

The auto_scaling process depends on some `statsmodels` functionality, however, I verified that the same version of `statsmodels` is being used by both python versions. So, I'm a bit baffled at the moment about what's going on.

**Comment by aloctavodia** [comment]
Is this still a problem?
