### ISSUE TITLE
Specifying the reference level in treatment (dummy) coding

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [bambinos/bambi#99]
Say I have the following treatment levels: 
``` python
['C (P.OD)', 'C (P.SD)', 'C (RTG.OD)', 'E']
```
For the sake of simplicity, say I need to fit a model of the type using dummy coding:
``` python
model = bmb.Model(data)
model.fit("y ~ treatment", samples=1000)
```
I am assuming this would use alphabetical ordering by default.Is there any way for me to specify the reference (base) level? 

Thanks!

**Comment by jake-westfall** [comment]
Yes, the dummy codes are constructed by Patsy, so you can use all the Patsy functionality to specify things like the reference level to use ([link to the docs](http://patsy.readthedocs.io/en/latest/API-reference.html#handling-categorical-data)). In your case, I think something like the following as the formula string should work to designate the 'E' group as the reference category:
`y ~ C(treatment, Treatment('E'))`

**Comment by amelio-vazquez-reina** [comment]
Thank you @jake-westfall 

That's great. Just for completeness for others, in case they run into this discussion, it looks like bambi follows a slightly different syntax from `statsmodels` which can ingest the encoding in the following two formats:

``` python
ols("y ~ C(treatment, patsy.Treatment(reference='E'))", data=my_data)
```
``` python
ols("y ~ C(treatment, levels=['E', 'C (P.OD)', 'C (P.SD)', 'C (RTG.OD)'], data=my_data)
```
